# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=959486ed06
# 
# 

# ********RoostGPT********
# test_store_order.py

import pytest
from requests import HTTPError

@pytest.mark.parametrize("order_id, expected_status", [
    (1, 200),  # Valid ID
    (10, 200),  # Valid ID
    (0, 400),  # Invalid ID (below minimum)
    (11, 400),  # Invalid ID (above maximum)
    (999, 404),  # Non-existent ID
])
def test_get_order_by_id(api_client, schema_validator, order_id, expected_status):
    """Test fetching order by ID with various scenarios."""
    endpoint = f"v2/store/order/{order_id}"
    response = api_client.make_request(endpoint)

    assert response.status_code == expected_status

    if response.status_code == 200:
        order_data = response.json()
        assert schema_validator.validate_schema_order(order_data)
    elif response.status_code in [400, 404]:
        assert 'error' in response.json()

@pytest.mark.parametrize("api_key, expected_status", [
    (pytest.lazy_fixture('valid_api_key'), 200),  # Valid API key
    (pytest.lazy_fixture('invalid_api_key'), 401),  # Invalid API key
    (None, 401),  # Missing API key
])
def test_get_order_by_id_with_auth(api_client, api_key, expected_status):
    """Test fetching order by ID with authentication scenarios."""
    endpoint = "v2/store/order/1"
    headers = {'Authorization': f'Bearer {api_key}'} if api_key else {}
    response = api_client.make_request(endpoint, headers=headers)

    assert response.status_code == expected_status

def test_get_order_by_id_with_oauth(api_client, oauth2_token):
    """Test fetching order by ID with OAuth2 token."""
    endpoint = "v2/store/order/1"
    headers = {'Authorization': f'Bearer {oauth2_token}'}
    response = api_client.make_request(endpoint, headers=headers)

    assert response.status_code == 200
    order_data = response.json()
    assert 'id' in order_data

# Instructions for running the tests
# 1. Ensure pytest is installed: pip install pytest
# 2. Set environment variables for API_HOST, api_key, and AUTH_TOKEN.
# 3. Run the tests using the command: pytest test_store_order.py
