# ********RoostGPT********

# Test generated by RoostGPT for test testTimedout using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /context/{context_id}/environment-variable/{env_var_name}_delete for http method type DELETE 
# RoostTestHash=32e36d7953
# 
# 

# ********RoostGPT********
"""
Pytest test suite for the API endpoint: /context/{context_id}/environment-variable/{env_var_name}

This suite tests the DELETE method for removing an environment variable from a context.
It covers various scenarios including successful deletion, unauthorized access, and entity not found.

Instructions for running the tests:
- Ensure pytest is installed in your environment.
- Place this test file in the same directory as the JSON test data file.
- Execute the tests using the command: pytest <test_file_name>.py
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load the API specification for validation
api_spec_path = Path(__file__).parent / 'api.json'
validator = SwaggerSchemaValidator(api_spec_path)

# Load test data from JSON file
TEST_DATA_FILENAME = 'context_context_id_environment-variable_env_var_na.json'
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME

def _load_json_file(path):
    with open(path, 'r') as file:
        return json.load(file)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"{case['scenario']}" for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_environment_variable(api_client, config_test_data, scenario_case):
    """
    Test DELETE /context/{context_id}/environment-variable/{env_var_name}
    """
    context_id = scenario_case.get('context_id', config_test_data['context_id'])
    env_var_name = scenario_case.get('env_var_name', config_test_data['env_var_name'])
    expected_status_code = scenario_case['statusCode']

    endpoint = f"/context/{context_id}/environment-variable/{env_var_name}"

    # Perform DELETE request
    try:
        response = api_client.delete(endpoint)
    except requests.exceptions.HTTPError as e:
        response = e.response

    # Validate response status code
    assert response.status_code == expected_status_code, f"Expected {expected_status_code}, got {response.status_code}"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(endpoint, 'DELETE', str(expected_status_code), response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

    # Additional assertions based on scenario
    if expected_status_code == 200:
        assert 'message' in response.json(), "Response JSON should contain 'message' key"
    elif expected_status_code == 401:
        assert response.json().get('message') in [
            "Invalid token provided.",
            "New format tokens are needed to authenticate this API endpoint. Create a new API token for access.",
            "Support for query parameter authentication has been deprecated to improve security. Please use a supported authentication method such as header-based, or basic authentication."
        ], "Unexpected error message for 401 response"
    elif expected_status_code == 404:
        assert response.json().get('message') in [
            "Context not found.",
            "Organization does not exist.",
            "User does not exist.",
            "Project does not exist.",
            "Group does not exist.",
            "Orb does not exist."
        ], "Unexpected error message for 404 response"
    elif expected_status_code == 429:
        assert response.json().get('message') == "Rate limit exceeded.", "Unexpected error message for 429 response"
    elif expected_status_code == 500:
        assert response.json().get('message') == "Internal server error.", "Unexpected error message for 500 response"
