# ********RoostGPT********

# Test generated by RoostGPT for test testTimedout using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /context/{context_id}/restrictions/{restriction_id}_delete for http method type DELETE 
# RoostTestHash=ac183fbd06
# 
# 

# ********RoostGPT********
"""
Pytest test suite for the API endpoint /context/{context_id}/restrictions/{restriction_id}

Setup:
- Ensure the `conftest.py` and `validator.py` are in the same directory.
- The `config.yml` file should be configured with the necessary API host and authentication details.
- The JSON test data file `context_context_id_restrictions_restriction_id.json` should be present in the same directory.

Run the tests using the command:
pytest <test_file_name>.py
"""

import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Constants
TEST_DATA_FILENAME = 'context_context_id_restrictions_restriction_id.json'
API_SPEC_PATH = 'api.json'
ENDPOINT = '/context/{context_id}/restrictions/{restriction_id}'
METHOD = 'DELETE'

# Load test data
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME
with open(_endpoint_data_path, 'r') as f:
    _ENDPOINT_DATA = json.load(f)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case['scenario'] for case in _ENDPOINT_DATA]

# Initialize SwaggerSchemaValidator
validator = SwaggerSchemaValidator(API_SPEC_PATH)

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_context_restriction(api_client, config_test_data, scenario_case):
    """
    Test the DELETE /context/{context_id}/restrictions/{restriction_id} endpoint.
    """
    context_id = config_test_data['context_id']
    restriction_id = config_test_data['restriction_id']
    endpoint = ENDPOINT.format(context_id=context_id, restriction_id=restriction_id)

    # Prepare headers
    headers = {
        'Authorization': f"Bearer {api_client.auth['api_key_header']}"
    }

    # Make API request
    response = api_client.delete(endpoint, headers=headers)

    # Validate response status code
    assert response.status_code == scenario_case['statusCode'], f"Expected {scenario_case['statusCode']}, got {response.status_code}"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(endpoint, METHOD, str(response.status_code), response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

    # Validate response message
    response_data = response.json()
    assert response_data['message'] == scenario_case['message'], f"Expected message '{scenario_case['message']}', got '{response_data['message']}'"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_delete_context_restriction_invalid_auth(api_client, config_test_data, scenario_case):
    """
    Test the DELETE /context/{context_id}/restrictions/{restriction_id} endpoint with invalid authentication.
    """
    context_id = config_test_data['context_id']
    restriction_id = config_test_data['restriction_id']
    endpoint = ENDPOINT.format(context_id=context_id, restriction_id=restriction_id)

    # Prepare headers with invalid token
    headers = {
        'Authorization': 'Bearer invalid_token'
    }

    # Make API request
    response = api_client.delete(endpoint, headers=headers)

    # Validate response status code
    assert response.status_code == 401, f"Expected 401, got {response.status_code}"

    # Validate response schema
    validation_result = validator.validate_schema_by_response(endpoint, METHOD, '401', response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

    # Validate response message
    response_data = response.json()
    expected_message = "Invalid token provided."
    assert response_data['message'] == expected_message, f"Expected message '{expected_message}', got '{response_data['message']}'"
