# ********RoostGPT********

# Test generated by RoostGPT for test api-test-pytest-circleci using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /project/{project-slug}/checkout-key/{fingerprint}_get for http method type GET 
# RoostTestHash=5885ecc23a
# 
# 

# ********RoostGPT********
"""
PyTest suite for RESTful API endpoint: GET /project/{project-slug}/checkout-key/{fingerprint}

Summary:
- Endpoints:
  - GET /project/{project-slug}/checkout-key/{fingerprint}
- Security Schemas:
  - API Key via header: Circle-Token
  - API Key via query param: circle-token
- Responses:
  - 200: CheckoutKey (application/json)
  - default: Error response (application/json)

Instructions:
- Ensure config.yml is present alongside conftest.py and environment variables are set as needed.
- Place api.json (OpenAPI spec) and project_project-slug_checkout-key_fingerprint.json (ENDPOINT_TEST_DATA) in the same directory as this test file.
- Run: pytest -m smoke -q (for smoke) or pytest -q (for all)

Notes:
- This suite uses:
  - Fixtures from conftest.py: api_client, config_test_data, auth_headers, auth_params
  - SwaggerSchemaValidator from validator.py for response schema validation
- Table-driven scenarios loaded from project_project-slug_checkout-key_fingerprint.json are merged over config_test_data.
- Tests gracefully skip if required auth or required path params are absent to avoid false negatives.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import quote as urlquote

import pytest

from validator import SwaggerSchemaValidator


TEST_DATA_FILENAME = "project_project-slug_checkout-key_fingerprint.json"

_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME
_spec_path = _here / "api.json"


def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        # If test data file is missing, provide an empty list to avoid collection errors
        return []
    data = json.loads(raw) if raw.strip() else []
    if not isinstance(data, list):
        raise ValueError(f"Endpoint test data must be a list of scenarios, got: {type(data)}")
    return data


def _param_ids(cases: List[Dict[str, Any]]) -> List[str]:
    ids: List[str] = []
    for i, c in enumerate(cases):
        base = c.get("scenario") or f"case-{i+1}"
        ps = c.get("project-slug") or ""
        fp = (c.get("fingerprint") or "")[:7]
        code = c.get("statusCode")
        suffix = []
        if ps:
            suffix.append(ps.split("/")[-1] or "ps")
        if fp:
            suffix.append(fp)
        if code is not None:
            suffix.append(str(code))
        if suffix:
            base = f"{base}::{'|'.join(suffix)}"
        ids.append(base)
    return ids


def _merge_dicts(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    merged = dict(base or {})
    for k, v in (override or {}).items():
        merged[k] = v
    return merged


def _build_endpoint_path(project_slug: str, fingerprint: str) -> str:
    # Per spec, "/" may appear in project-slug and should be URL-escaped.
    # sha256 fingerprints should be URL-encoded as well.
    project_seg = urlquote(project_slug or "", safe="")  # encode "/" and all reserved chars
    fingerprint_seg = urlquote(fingerprint or "", safe="")
    # Do not include leading slash here because APIClient joins with base_url cleanly.
    return f"project/{project_seg}/checkout-key/{fingerprint_seg}"


# Load endpoint test data at module import time
_ENDPOINT_DATA: List[Dict[str, Any]] = _load_json_file(_endpoint_data_path)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)

# Initialize schema validator once for the module
_VALIDATOR = SwaggerSchemaValidator(str(_spec_path))


def _validate_response_schema(resp, status_code_key: str) -> None:
    """
    Validate response against the OpenAPI schema using the given status code key.
    status_code_key must be "200" or "default" to match spec response map.
    """
    result = _VALIDATOR.validate_schema_by_response(
        endpoint="/project/{project-slug}/checkout-key/{fingerprint}",
        method="get",
        status_code=status_code_key,
        response=resp,
    )
    assert result.get("valid"), f"Schema validation failed for {status_code_key}: {result}"


@pytest.mark.smoke
@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_checkout_key_smoke_success(api_client, config_test_data, auth_headers, auth_params, scenario_case):
    """
    Smoke test for GET /project/{project-slug}/checkout-key/{fingerprint}
    - Uses only required path params (project-slug, fingerprint)
    - Asserts status code equals 'statusCode' in scenario data
    - Validates response schema for 200 or default based on actual status
    - Skips if auth is missing or required params are unavailable
    """
    # Skip if auth is not provided; authentication tests handled elsewhere
    token_hdr = (auth_headers or {}).get("Circle-Token", "")
    token_q = (auth_params or {}).get("circle-token", "")
    if not token_hdr and not token_q:
        pytest.skip("Authentication token not provided via header or query; skipping smoke test")

    # Merge default config test data with endpoint scenario case; scenario overrides defaults
    merged = _merge_dicts(config_test_data or {}, scenario_case or {})

    # Extract required path params
    project_slug = (merged.get("project-slug") or "").strip()
    fingerprint = (merged.get("fingerprint") or "").strip()

    # Handle missing required fields gracefully
    if not project_slug or not fingerprint:
        pytest.skip("Required path params missing (project-slug or fingerprint) for this scenario")

    # Construct endpoint path with URL-encoding rules applied
    endpoint_path = _build_endpoint_path(project_slug, fingerprint)

    # Request validation (no explicit request body schema to validate for GET with path params only)

    # Execute request
    resp = api_client.get(endpoint_path)

    # Determine expected status code strictly from scenario
    if "statusCode" not in scenario_case:
        pytest.skip("No expected statusCode provided in ENDPOINT_TEST_DATA for this scenario")

    expected_status = int(scenario_case["statusCode"])
    assert resp.status_code == expected_status, (
        f"Expected status {expected_status} but got {resp.status_code} "
        f"for project-slug={project_slug}"
    )

    # Schema validation against spec
    if str(resp.status_code) == "200":
        _validate_response_schema(resp, "200")
    else:
        # For default block: ensure not a 2xx success
        assert not (200 <= resp.status_code < 300), f"Unexpected 2xx with no matching schema for {resp.status_code}"
        _validate_response_schema(resp, "default")


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_checkout_key_response_schema_any_status(api_client, config_test_data, auth_headers, auth_params, scenario_case):
    """
    General schema validation test:
    - Sends request with available required params (if present), otherwise skips.
    - Validates '200' schema on success, 'default' schema otherwise.
    - Does not assert a specific status code to allow broader coverage.
    """
    token_hdr = (auth_headers or {}).get("Circle-Token", "")
    token_q = (auth_params or {}).get("circle-token", "")
    if not token_hdr and not token_q:
        pytest.skip("Authentication token not provided via header or query; skipping")

    merged = _merge_dicts(config_test_data or {}, scenario_case or {})

    project_slug = (merged.get("project-slug") or "").strip()
    fingerprint = (merged.get("fingerprint") or "").strip()

    if not project_slug or not fingerprint:
        pytest.skip("Required path params missing (project-slug or fingerprint) for this scenario")

    endpoint_path = _build_endpoint_path(project_slug, fingerprint)

    resp = api_client.get(endpoint_path)

    if str(resp.status_code) == "200":
        _validate_response_schema(resp, "200")
    else:
        assert not (200 <= resp.status_code < 300), f"Unexpected 2xx with non-200 status {resp.status_code}"
        _validate_response_schema(resp, "default")
