# ********RoostGPT********

# Test generated by RoostGPT for test api-test-pytest-circleci using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /webhook/{webhook-id}_get for http method type GET 
# RoostTestHash=04eed72dbb
# 
# 

# ********RoostGPT********
"""
Summary of API specification and test plan

Endpoints:
- GET /webhook/{webhook-id}: Retrieve an outbound webhook by its UUID.

Security Schemas:
- API Key via HTTP header 'Circle-Token' (and optionally query param 'circle-token').
  Authentication is provided through shared pytest fixtures (auth_headers, auth_params, api_client).
  Authentication-specific tests are covered in a dedicated test_authentication.py and are skipped here.

Responses:
- 200 (application/json): Webhook object with required fields:
  [id, scope, name, events, url, verify-tls, signing-secret, created-at, updated-at]
- default (application/json): Error object with 'message' string.

Parameters:
- Path parameter 'webhook-id' (string, uuid) is required.

Request/Response Validation Strategy:
- Request validation: No request body is required for this endpoint. If the validator exposes a validate_json method and a suitable schema exists, it will be used dynamically. Otherwise, path parameter checks rely on test-data presence.
- Response validation: Uses SwaggerSchemaValidator.validate_schema_by_response bound to (endpoint='/webhook/{webhook-id}', method='GET', and actual status code).

Test Data:
- Table-driven tests are sourced from webhook_webhook-id.json (same folder).
- Scenario-specific data from the JSON overrides the base config test_data from conftest.py via a merge strategy.
- Each test function iterates all scenario objects. Missing fields are handled gracefully via conditional checks and pytest.skip as needed.

How to run:
- Ensure config.yml, api.json, and webhook_webhook-id.json are present in the same directory as this test file and conftest.py.
- Provide necessary environment variables to populate config.yml (e.g., API_HOST, Circle-Token).
- Execute: pytest -q
"""

import json
from pathlib import Path
from typing import Any, Dict, List, Iterable

import pytest
from validator import SwaggerSchemaValidator


# -----------------------------
# Module-level configuration and test data loading
# -----------------------------

_TEST_DATA_FILENAME = "webhook_webhook-id.json"
_SPEC_FILENAME = "api.json"

_here = Path(__file__).resolve().parent
_spec_path = _here / _SPEC_FILENAME
_endpoint_data_path = _here / _TEST_DATA_FILENAME


def _load_json_file(path: Path) -> Any:
    if not path.exists():
        # Provide a clear failure that the file is required for table-driven tests
        raise RuntimeError(f"Required test data file not found: {path}")
    try:
        with path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Invalid JSON in test data file {path}: {e}") from e


def _param_ids(cases: Iterable[Dict[str, Any]]) -> List[str]:
    ids: List[str] = []
    for idx, c in enumerate(cases):
        scenario = c.get("scenario") or f"case-{idx+1}"
        ids.append(str(scenario))
    return ids


def _merge_test_data(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    """
    Shallow merge where scenario-specific keys override base config test_data values.
    """
    merged = dict(base or {})
    for k, v in (override or {}).items():
        if v is None:
            # remove key if explicitly None
            merged.pop(k, None)
        else:
            merged[k] = v
    return merged


# Load endpoint-specific table-driven data at import time
_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)
if not isinstance(_ENDPOINT_DATA, list):
    raise RuntimeError(f"Expected an array of test cases in: {_endpoint_data_path}")

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)


# -----------------------------
# Fixtures
# -----------------------------

@pytest.fixture(scope="session")
def validator() -> SwaggerSchemaValidator:
    """
    Session-scoped validator for OpenAPI schema validations.
    """
    return SwaggerSchemaValidator(str(_spec_path))


@pytest.fixture(scope="session")
def endpoint_path_template() -> str:
    """
    The OpenAPI path template used for response validation.
    """
    return "/webhook/{webhook-id}"


# -----------------------------
# Helper utilities
# -----------------------------

def _build_endpoint(path_template: str, webhook_id: str) -> str:
    """
    Build the concrete endpoint path by substituting the path parameter.
    """
    # Note: CircleCI OpenAPI style uses hyphenated param name.
    return path_template.replace("{webhook-id}", webhook_id)


def _expect_status_and_validate_schema(
    validator: SwaggerSchemaValidator,
    endpoint_path_template: str,
    response,
    expected_status: Any,
) -> None:
    """
    Assert status code and validate response schema against OpenAPI.
    Handles special 'default' response declaration as a non-2xx expectation.
    """
    status = response.status_code

    # Handle explicit codes vs 'default'
    if isinstance(expected_status, int):
        assert status == expected_status, f"Unexpected status: got {status}, expected {expected_status}"
    elif isinstance(expected_status, str) and expected_status.lower() == "default":
        assert not (200 <= status < 300), f"Expected non-2xx status for default response but got {status}"
    else:
        # If expected_status is missing, we proceed but log a soft assertion via pytest skip
        pytest.skip("No expected status code provided in test data; skipping strict assertion")

    # Run schema validation only for codes that exist in the spec
    # The provided spec defines explicit '200' and a 'default' response
    # The validator helper requires a concrete code; it does not resolve 'default',
    # so we only validate explicit status codes present in the spec (e.g., 200).
    status_key = str(status)
    if status_key == "200":
        result = validator.validate_schema_by_response(
            endpoint=endpoint_path_template,
            method="GET",
            status_code=status_key,
            response=response,
        )
        assert result.get("valid", False), f"Response schema validation failed: {result}"
    else:
        # For non-200, the validator does not fall back to 'default'; skip schema assertion
        pytest.skip(f"No explicit schema block for status {status} in spec; skipping schema validation")


# -----------------------------
# Tests
# -----------------------------

@pytest.mark.smoke
@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_webhook_by_id_smoke_success(api_client, config_test_data, validator, endpoint_path_template, scenario_case):
    """
    Smoke test for GET /webhook/{webhook-id}
    - Uses only required request data (path parameter).
    - Validates the response schema for 200 as per the OpenAPI spec.
    - Test data is sourced from config_test_data and overridden by endpoint-specific JSON.
    """
    # Merge default test_data with scenario overrides
    merged = _merge_test_data(config_test_data, scenario_case)

    # Required path parameter: webhook-id
    webhook_id = merged.get("webhook-id")
    if not webhook_id:
        # If not available in either scenario or base config, skip to avoid sending invalid request
        pytest.skip('Missing required path parameter "webhook-id" in test data')

    # If the validator exposes request data validation against a named schema and such schema exists,
    # it can be invoked here. The provided validator API does not include a named param schema for path vars.
    # Hence, request validation for path param is not applied beyond presence checks.

    # Build endpoint and send request
    endpoint = _build_endpoint(endpoint_path_template, webhook_id)
    response = api_client.get(endpoint)

    # Expected status code from scenario (dynamic, not hardcoded)
    expected_status = scenario_case.get("statusCode")
    if expected_status is None:
        # Without expected status in test data, we do not enforce status assertions
        pytest.skip("No expected statusCode provided in ENDPOINT_TEST_DATA for this scenario")

    # Assert and validate schema
    _expect_status_and_validate_schema(
        validator=validator,
        endpoint_path_template=endpoint_path_template,
        response=response,
        expected_status=expected_status,
    )


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_webhook_by_id_error_default_cases(api_client, config_test_data, validator, endpoint_path_template, scenario_case):
    """
    Negative path coverage for GET /webhook/{webhook-id}
    - Covers default (error) responses when such scenarios are provided by the ENDPOINT_TEST_DATA.
    - If the current scenario expects 200 or lacks a default/error expectation, the test is skipped.
    """
    merged = _merge_test_data(config_test_data, scenario_case)
    webhook_id = merged.get("webhook-id")
    if not webhook_id:
        pytest.skip('Missing required path parameter "webhook-id" in test data')

    expected_status = scenario_case.get("statusCode")
    if expected_status is None:
        pytest.skip("No expected statusCode provided for this scenario")

    # Only run this test if scenario explicitly targets non-200 or 'default'
    if isinstance(expected_status, int) and expected_status == 200:
        pytest.skip("This scenario targets success response; skipping default error validation path")
    if isinstance(expected_status, str) and expected_status.lower() != "default":
        pytest.skip("This scenario does not target a default error response; skipping")

    endpoint = _build_endpoint(endpoint_path_template, webhook_id)
    response = api_client.get(endpoint)

    # For default error expectation, ensure we did not get a 2xx
    _expect_status_and_validate_schema(
        validator=validator,
        endpoint_path_template=endpoint_path_template,
        response=response,
        expected_status=expected_status,
    )
