# ********RoostGPT********

# Test generated by RoostGPT for test api-test-pytest-circleci using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /pipeline/{pipeline-id}/config_get for http method type GET 
# RoostTestHash=44d8f0ed9d
# 
# 

# ********RoostGPT********
"""
Pytest test suite for: GET /pipeline/{pipeline-id}/config

Summary of endpoints and security schemas
- Endpoint:
  - GET /pipeline/{pipeline-id}/config
- Security:
  - API Key via HTTP header: Circle-Token (see config.yml -> auth.api_key_header)
  - API Key via query parameter: circle-token (see config.yml -> auth.api_key_query)

Response status codes (from API spec)
- 200: Returns PipelineConfig object with required properties: source (string), compiled (string)
- default: Error response with schema: { "message": "string" }

Request/Response schemas and data models
- Path parameter:
  - pipeline-id (string, uuid) [required]
- Response body (200):
  - PipelineConfig object:
    - required: ["source", "compiled"]
    - properties:
      - source: string
      - compiled: string
      - setup-config: string (optional)
      - compiled-setup-config: string (optional)
- Response body (default):
  - object: { message: string }

Notes
- All dynamic values (like pipeline-id) are loaded from:
  1) ENDPOINT_TEST_DATA JSON file: pipeline_pipeline-id_config.json
  2) Default test_data from config.yml via conftest.py fixture config_test_data (used as fallback/override base)
- Authentication tests are intentionally skipped in this module; they belong in test_authentication.py

How to run
- Ensure the following files exist in the same directory:
  - api.json               (OpenAPI spec)
  - config.yml             (configuration with api.host and auth tokens)
  - pipeline_pipeline-id_config.json (ENDPOINT_TEST_DATA array)
  - conftest.py            (shared fixtures and APIClient)
  - validator.py           (SwaggerSchemaValidator implementation)
- Set environment variables if needed for config.yml variable expansion (e.g., API_HOST, Circle-Token).
- Execute:
  - pytest -q

"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List

import pytest
import requests

from validator import SwaggerSchemaValidator


# -----------------------
# Module-level constants
# -----------------------

_HERE = Path(__file__).resolve().parent
TEST_DATA_FILENAME = "pipeline_pipeline-id_config.json"
_SPEC_PATH = _HERE / "api.json"
_ENDPOINT_DATA_PATH = _HERE / TEST_DATA_FILENAME

# OpenAPI spec validator instance (used for all schema validations)
_VALIDATOR = SwaggerSchemaValidator(str(_SPEC_PATH))

# API spec path strings (as defined in api.json)
SPEC_ENDPOINT_PATH = "/pipeline/{pipeline-id}/config"
HTTP_METHOD = "get"


# -----------------------
# Utilities
# -----------------------

def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    try:
        text = path.read_text(encoding="utf-8")
        data = json.loads(text)
        if isinstance(data, list):
            return data
        if isinstance(data, dict):
            # Normalize to list
            return [data]
        return []
    except Exception as exc:
        raise RuntimeError(f"Failed to load JSON test data from {path}: {exc}") from exc


def _param_ids(cases: Iterable[Dict[str, Any]]) -> List[str]:
    ids: List[str] = []
    for idx, c in enumerate(cases):
        scenario = c.get("scenario") or f"case-{idx}"
        pid = c.get("pipeline-id") or "no-pipeline-id"
        scode = c.get("statusCode")
        ids.append(f"{scenario} | pipeline-id={pid} | expected={scode}")
    return ids


def _build_endpoint(pipeline_id: str) -> str:
    # Construct the concrete endpoint using the provided pipeline-id
    return f"/pipeline/{pipeline_id}/config"


# Load ENDPOINT_TEST_DATA at import time for parametrization
_ENDPOINT_DATA: List[Dict[str, Any]] = _load_json_file(_ENDPOINT_DATA_PATH)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)


# -----------------------
# Factories and helpers
# -----------------------

def _merge_scenario_with_defaults(defaults: Dict[str, Any], scenario: Dict[str, Any]) -> Dict[str, Any]:
    """
    Merge scenario-specific test data onto defaults from config_test_data.
    Scenario values take precedence.
    """
    merged = dict(defaults or {})
    for k, v in (scenario or {}).items():
        merged[k] = v
    return merged


def _validate_response_schema_or_assert(endpoint_path: str, method: str, status_code_key: str, response: requests.Response) -> None:
    """
    Validate response JSON against the schema defined under paths[endpoint_path][method][responses][status_code_key].
    Will assert if invalid.
    """
    result = _VALIDATOR.validate_schema_by_response(endpoint_path, method, status_code_key, response)
    assert isinstance(result, dict), "Validator must return a dictionary"
    assert result.get("valid") is True, f"Schema validation failed for {endpoint_path} {method.upper()} {status_code_key}: {result}"


# -----------------------
# Parametrized Tests
# -----------------------

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
@pytest.mark.smoke
def test_get_pipeline_config_smoke_success(api_client, config_test_data: Dict[str, Any], scenario_case: Dict[str, Any]) -> None:
    """
    Smoke: Happy path – only required request data used.
    - Validates 200 response and response schema (PipelineConfig).
    - Uses only required path parameter 'pipeline-id'.
    """
    # Compose effective test data by overriding defaults with scenario
    eff_data = _merge_scenario_with_defaults(config_test_data, scenario_case)

    # Required path param: pipeline-id
    pipeline_id = eff_data.get("pipeline-id")
    if not pipeline_id:
        pytest.skip("No pipeline-id provided in scenario or defaults; skipping smoke test case")

    # No request body to validate for this endpoint; only path parameter is required.
    # Build endpoint and execute request.
    endpoint = _build_endpoint(pipeline_id)
    response = api_client.get(endpoint)

    # Expected status code comes from ENDPOINT_TEST_DATA
    expected_status = scenario_case.get("statusCode")
    if expected_status is None:
        pytest.skip("No expected statusCode provided in scenario; skipping")

    assert response.status_code == int(expected_status), f"Unexpected status code for {endpoint}"

    # Validate response against OpenAPI schema for 200
    _validate_response_schema_or_assert(SPEC_ENDPOINT_PATH, HTTP_METHOD, "200", response)


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_config_invalid_pipeline_id_returns_default(api_client, config_test_data: Dict[str, Any], scenario_case: Dict[str, Any]) -> None:
    """
    Negative: Use an invalid pipeline-id (derived dynamically from provided one).
    - Expect non-2xx status code.
    - Validate against 'default' error schema.
    """
    eff_data = _merge_scenario_with_defaults(config_test_data, scenario_case)
    base_pipeline_id = eff_data.get("pipeline-id")

    if not base_pipeline_id:
        pytest.skip("No pipeline-id provided to derive invalid id; skipping negative case")

    # Derive an invalid UUID-like value from provided pipeline-id without hardcoding constants.
    invalid_pipeline_id = f"{base_pipeline_id.replace('-', '')}x"

    # Execute request with invalid id
    endpoint = _build_endpoint(invalid_pipeline_id)
    response = api_client.get(endpoint)

    # Per spec, default error applies; ensure not 2xx
    assert not (200 <= response.status_code < 300), f"Expected non-2xx for invalid pipeline-id, got {response.status_code}"

    # Validate response against OpenAPI schema for default error
    _validate_response_schema_or_assert(SPEC_ENDPOINT_PATH, HTTP_METHOD, "default", response)


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_config_missing_pipeline_id_skipped(config_test_data: Dict[str, Any], scenario_case: Dict[str, Any]) -> None:
    """
    Boundary: If neither scenario nor defaults provide pipeline-id, skip this case.
    This ensures table-driven iteration never errors out due to missing required fields.
    """
    eff_data = _merge_scenario_with_defaults(config_test_data, scenario_case)
    if eff_data.get("pipeline-id"):
        pytest.skip("pipeline-id present; boundary (missing param) scenario not applicable")
    pytest.skip("Missing required path parameter pipeline-id; skipping per instructions")


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pipeline_config_auth_enforcement_skipped(scenario_case: Dict[str, Any]) -> None:
    """
    Authentication variants (valid/invalid/missing) are handled in a dedicated test_authentication.py.
    This test is intentionally skipped per instructions.
    """
    pytest.skip("Authentication tests are covered in test_authentication.py by design")
