# ********RoostGPT********

# Test generated by RoostGPT for test api-test-pytest-circleci using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /project/{project-slug}_delete for http method type DELETE 
# RoostTestHash=caa6efeb67
# 
# 

# ********RoostGPT********
"""
Pytest suite for REST API endpoint: DELETE /project/{project-slug}

Summary (Step 1: Analysis)
- Endpoints:
  - DELETE /project/{project-slug}
- Security schemas:
  - API Key via HTTP header "Circle-Token" (configured via config.yml -> auth.api_key_header)
  - API Key via query param "circle-token" (configured via config.yml -> auth.api_key_query)
- Parameters:
  - Path parameter "project-slug" (string, required). The "/" characters may be URL-escaped; allowReserved: true
- Responses:
  - 200 (application/json): components schema "MessageResponse" { message: string } with message required
  - default (application/json): generic error { message?: string }
- Request/Response schemas and data models:
  - Request body: none for DELETE endpoint
  - Response: 200 -> "MessageResponse"; default -> generic error with "message" string
- Required vs Optional:
  - Required: path parameter "project-slug"
  - Optional: none

Instructions
- Configure host and authentication via config.yml and environment variables.
- Provide scenario test data in project_project-slug.json (ENDPOINT_TEST_DATA) alongside this test file.
- Authentication tests are handled in a separate test_authentication.py, so this suite focuses on endpoint behavior and schema validation.
- This test performs destructive operation (DELETE). Ensure you run against a controlled environment.

Running the tests
- Use pytest in the project directory: pytest -q
- To enable smoke success tests that require authentication, ensure tokens are supplied via env/config as per config.yml.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Iterable
from urllib.parse import quote

import pytest
from validator import SwaggerSchemaValidator


# Constants derived from the provided API spec
PATH_TEMPLATE = "/project/{project-slug}"
OP_METHOD = "DELETE"
SUCCESS_CODE = "200"
DEFAULT_CODE = "default"


@pytest.fixture(scope="session")
def swagger_validator() -> SwaggerSchemaValidator:
    """
    Session-scoped validator initialized from the OpenAPI spec file api.json.
    """
    spec_path = Path(__file__).resolve().parent / "api.json"
    return SwaggerSchemaValidator(str(spec_path))


@pytest.fixture(scope="session")
def endpoint_test_data() -> List[Dict[str, Any]]:
    """
    Load ENDPOINT_TEST_DATA from the JSON file located alongside this test module.
    The file name is derived from the endpoint 'project_project-slug.json'.
    """
    data_path = Path(__file__).resolve().parent / "project_project-slug.json"
    if not data_path.exists():
        raise FileNotFoundError(f"Required test data file not found: {data_path}")
    with data_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("ENDPOINT_TEST_DATA must be a JSON array")
    return data


@pytest.fixture(scope="session")
def merged_cases(config_test_data: Dict[str, Any], endpoint_test_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Merge default test_data from config.yml with scenario-specific ENDPOINT_TEST_DATA.
    Scenario data overrides default values.

    Ensures that required 'project-slug' key is available in each case after merge.
    """
    merged: List[Dict[str, Any]] = []
    for i, row in enumerate(endpoint_test_data):
        case = dict(config_test_data)
        case.update(row or {})
        # normalize keys and ensure types
        case["statusCode"] = int(case.get("statusCode")) if "statusCode" in case else None
        case["project-slug"] = str(case.get("project-slug") or "").strip()
        merged.append(case)
    return merged


@pytest.fixture(scope="session")
def has_auth(default_headers: Dict[str, str], default_query_params: Dict[str, str]) -> bool:
    """
    Determine if authentication tokens are configured via config.yml/env.
    We skip success smoke tests if auth is not present, since auth tests are handled elsewhere.
    """
    header_token = default_headers.get("Circle-Token", "").strip()
    query_token = default_query_params.get("circle-token", "").strip()
    return bool(header_token or query_token)


def _iter_cases(cases: List[Dict[str, Any]]) -> Iterable[Dict[str, Any]]:
    """
    Utility iterator to iterate over all cases ensuring project-slug presence.
    """
    for case in cases:
        yield case


def _build_delete_path(project_slug: str, url_escape_slashes: bool = False) -> str:
    """
    Build endpoint path for DELETE operation with optional URL-escape of slashes.
    - allowReserved is true in the spec, so both raw and URL-escaped slashes should be valid.
    """
    if url_escape_slashes:
        # Encode all reserved characters including "/" to form a single path segment after '/project/'
        encoded_slug = quote(project_slug, safe="")
        return f"/project/{encoded_slug}"
    # Keep slashes as-is to represent path traversal through multiple segments
    return f"/project/{project_slug}"


def _validate_response_schema(
    swagger_validator: SwaggerSchemaValidator,
    response,
    status_key: str,
) -> None:
    """
    Validate a response against the OpenAPI spec for the given status key.
    status_key must be "200" for success or "default" for error block per the spec.
    """
    result = swagger_validator.validate_schema_by_response(
        endpoint=PATH_TEMPLATE,
        method=OP_METHOD,
        status_code=status_key,
        response=response,
    )
    assert result.get("valid", False), f"Schema validation failed: {result}"


@pytest.mark.smoke
def test_delete_project_success_smoke(
    api_client,
    swagger_validator: SwaggerSchemaValidator,
    merged_cases: List[Dict[str, Any]],
    has_auth: bool,
):
    """
    Smoke: DELETE /project/{project-slug} should return 200 with MessageResponse when authenticated
    - Uses only REQUIRED parameter (project-slug)
    - All values sourced via fixtures (config_test_data + ENDPOINT_TEST_DATA)
    - Skips if auth not configured to avoid coupling with authentication tests
    """
    if not has_auth:
        pytest.skip("Authentication not configured; skipping smoke success test per instructions.")

    for case in _iter_cases(merged_cases):
        project_slug = case.get("project-slug", "")
        expected_status = int(case.get("statusCode", 200))

        if not project_slug:
            pytest.skip("Required path parameter 'project-slug' not provided in config/test data")

        # Request validation: No body to validate for DELETE; path param is required and checked above.

        endpoint_path = _build_delete_path(project_slug, url_escape_slashes=False)
        resp = api_client.delete(endpoint_path)

        # Assert status code strictly follows scenario expectations
        assert (
            resp.status_code == expected_status
        ), f"Unexpected status code for {endpoint_path}. Expected {expected_status}, got {resp.status_code}. Body: {resp.text}"

        # Validate response schema against spec for "200"
        _validate_response_schema(swagger_validator, resp, SUCCESS_CODE)


def test_delete_project_error_scenarios(
    api_client,
    swagger_validator: SwaggerSchemaValidator,
    merged_cases: List[Dict[str, Any]],
):
    """
    Error scenarios for DELETE /project/{project-slug}
    - Derives invalid/edge values from provided data without hardcoding external fixtures
    - Validates response against 'default' schema block as per spec
    - Does not rely on authentication, as error can be due to invalid resource or auth; both must conform to 'default'
    """
    for case in _iter_cases(merged_cases):
        base_slug = case.get("project-slug", "")
        if not base_slug:
            pytest.skip("Required path parameter 'project-slug' not provided in config/test data")

        # Produce an invalid/non-existent slug by namespacing with a suffix to avoid hardcoding arbitrary literals
        # This remains derived from provided test data.
        invalid_slug = f"{base_slug}--invalid--not-found--{os.getpid()}"

        endpoint_path = _build_delete_path(invalid_slug, url_escape_slashes=False)
        resp = api_client.delete(endpoint_path)

        # Any non-200 is considered error; we use the 'default' schema block for validation as per API spec.
        assert resp.status_code != 200, f"Delete unexpectedly succeeded for invalid slug. Body: {resp.text}"

        _validate_response_schema(swagger_validator, resp, DEFAULT_CODE)


def test_delete_project_with_url_escaped_slug(
    api_client,
    swagger_validator: SwaggerSchemaValidator,
    merged_cases: List[Dict[str, Any]],
    has_auth: bool,
):
    """
    Validate handling of URL-escaped slashes in 'project-slug' per spec (allowReserved: true).
    - Uses the provided slugs but URL-escapes slashes to form a single segment.
    - If authentication is not configured, skip to avoid coupling with auth tests.
    - Response could be success (200) or an error depending on resource existence/state.
      We validate the response strictly against appropriate schema:
        - If 200 -> validate against success schema
        - Else -> validate against default error schema
    """
    if not has_auth:
        pytest.skip("Authentication not configured; skipping URL-escaped slug test per instructions.")

    for case in _iter_cases(merged_cases):
        project_slug = case.get("project-slug", "")
        if not project_slug:
            pytest.skip("Required path parameter 'project-slug' not provided in config/test data")

        endpoint_path = _build_delete_path(project_slug, url_escape_slashes=True)
        resp = api_client.delete(endpoint_path)

        if resp.status_code == 200:
            _validate_response_schema(swagger_validator, resp, SUCCESS_CODE)
        else:
            _validate_response_schema(swagger_validator, resp, DEFAULT_CODE)
