# ********RoostGPT********

# Test generated by RoostGPT for test api-test-pytest-circleci using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /project/{project-slug}/schedule_get for http method type GET 
# RoostTestHash=1376419304
# 
# 

# ********RoostGPT********
"""
API Test Suite: list schedules for a project

Summary (Step 1: Analysis)
- Endpoint:
  - GET /project/{project-slug}/schedule
- Security Schemas:
  - API key via header: Circle-Token (preferred)
  - API key via query: circle-token (legacy)
- Parameters:
  - Path:
    - project-slug (string, required) in the form "vcs/org/repo"
  - Query:
    - page-token (string, optional)
- Responses:
  - 200: application/json { items: [...], next_page_token: string|null } (A sequence of schedules)
  - default: application/json { message: string } (Error response)
- Request/Response Schemas:
  - Response: 200 schema defines list of Schedule objects with required fields (id, name, timetable, description, project-slug, actor, created-at, updated-at, parameters)
  - No request body for this endpoint

Instructions for setup and execution:
- Ensure config.yml is present next to conftest.py (see provided CONFIG YML DATA) and that:
  - api.host is configured (defaults to https://circleci.com/api/v2)
  - auth tokens are supplied via environment or config (Circle-Token or circle-token) if you expect 200 responses
- Place api.json (OpenAPI spec) and project_project-slug_schedule.json (ENDPOINT_TEST_DATA) in the same folder as this test file
- Run tests: pytest -q
"""

from __future__ import annotations
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional

import pytest

from validator import SwaggerSchemaValidator


# Constants and table-driven data setup (Step 3.1)
SPEC_PATH = "api.json"
SPEC_ENDPOINT_PATTERN = "/project/{project-slug}/schedule"
TEST_DATA_FILENAME = "project_project-slug_schedule.json"

_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME


def _load_json_file(path: Path) -> List[Dict[str, Any]]:
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return []
    try:
        data = json.loads(raw)
        if isinstance(data, list):
            return data
        return []
    except json.JSONDecodeError:
        return []


def _param_ids(cases: Iterable[Mapping[str, Any]]) -> List[str]:
    ids: List[str] = []
    for i, c in enumerate(cases, 1):
        sid = c.get("scenario") or c.get("project-slug") or f"case-{i}"
        ids.append(str(sid))
    return ids


def _merge_test_data(base: Mapping[str, Any], override: Mapping[str, Any]) -> Dict[str, Any]:
    # Endpoint test data overrides default config_test_data when values are non-empty
    merged = dict(base or {})
    for k, v in (override or {}).items():
        if v is not None and v != "":
            merged[k] = v
    return merged


def _endpoint_from_slug(project_slug: str) -> str:
    # Keep the slug as-is to preserve path segments (e.g., gh/org/repo)
    # APIClient will join with base_url; do not URL-encode to keep behavior consistent with spec examples.
    return f"project/{project_slug}/schedule"


def _build_query_params(case: Mapping[str, Any]) -> Dict[str, Any]:
    params: Dict[str, Any] = {}
    # Optional pagination token
    if "page-token" in case and case.get("page-token") not in (None, ""):
        params["page-token"] = case["page-token"]
    return params


def _expected_status(case: Mapping[str, Any]) -> Optional[str]:
    # Returns "200", "default", or None
    raw = (case.get("statusCode") or "").strip()
    if not raw:
        return None
    if raw.isdigit():
        return raw
    # Allow literal "default" as specified by OpenAPI
    if raw.lower() == "default":
        return "default"
    return None


# Load ENDPOINT_TEST_DATA at import time to avoid lazy fixture issues in parametrize
_ENDPOINT_DATA: List[Dict[str, Any]] = _load_json_file(_endpoint_data_path)
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = _param_ids(_ENDPOINT_DATA)


@pytest.fixture(scope="session")
def schema_validator() -> SwaggerSchemaValidator:
    # Initialize validator once per session
    spec_file = _here / SPEC_PATH
    if not spec_file.exists():
        pytest.skip(f"OpenAPI spec not found at {spec_file}")
    return SwaggerSchemaValidator(str(spec_file))


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
@pytest.mark.smoke
def test_list_schedules_smoke_success(
    api_client,
    config_test_data: Dict[str, Any],
    schema_validator: SwaggerSchemaValidator,
    auth_headers: Dict[str, str],
    scenario_case: Dict[str, Any],
):
    """
    Smoke test: Happy path with only REQUIRED params.
    - Sends GET /project/{project-slug}/schedule with no optional query parameters
    - Requires a configured token to reliably receive 200 responses in most CircleCI environments
    """
    if not _PARAM_CASES:
        pytest.skip(f"Endpoint test data file missing or empty: {TEST_DATA_FILENAME}")

    # Merge config defaults with scenario overrides
    merged = _merge_test_data(config_test_data, scenario_case)

    project_slug = merged.get("project-slug")
    if not project_slug:
        pytest.skip("Required 'project-slug' not configured in config.yml test_data or ENDPOINT_TEST_DATA")

    # Enforce token presence for smoke success
    if not auth_headers.get("Circle-Token"):
        pytest.skip("Smoke success requires a valid 'Circle-Token' configured in config.yml or environment")

    # Request validation: no request body; path/query types are simple (validated server-side)
    endpoint = _endpoint_from_slug(project_slug)
    response = api_client.get(endpoint, params=None)

    # Expect success in smoke path
    assert response.status_code == 200, f"Expected 200 for smoke path, got {response.status_code}"

    # Response schema validation against OpenAPI
    res = schema_validator.validate_schema_by_response(
        SPEC_ENDPOINT_PATTERN,
        "get",
        "200",
        response,
    )
    assert res.get("valid"), f"Schema validation failed: {res}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_list_schedules_responses_schema(
    api_client,
    config_test_data: Dict[str, Any],
    schema_validator: SwaggerSchemaValidator,
    auth_headers: Dict[str, str],
    scenario_case: Dict[str, Any],
):
    """
    General schema validation covering both success (200) and default error.
    - Iterates all table-driven cases from project_project-slug_schedule.json
    - Uses optional 'page-token' when provided in the scenario
    - Validates response against status-specific schema using validator
    - If scenario specifies statusCode=200 and token is present, assert 200 strictly
    - Otherwise, accept non-2xx as default error and validate accordingly
    """
    if not _PARAM_CASES:
        pytest.skip(f"Endpoint test data file missing or empty: {TEST_DATA_FILENAME}")

    merged = _merge_test_data(config_test_data, scenario_case)
    project_slug = merged.get("project-slug")
    if not project_slug:
        pytest.skip("Required 'project-slug' not configured in config.yml test_data or ENDPOINT_TEST_DATA")

    expected = _expected_status(scenario_case)

    params = _build_query_params(scenario_case)
    endpoint = _endpoint_from_slug(project_slug)

    # No request body to validate for GET; response schema validation is performed below
    response = api_client.get(endpoint, params=params)

    has_token = bool(auth_headers.get("Circle-Token"))

    if response.status_code == 200:
        # If scenario expects 200 and credentials configured, assert strictly
        if expected == "200" and has_token:
            assert response.status_code == 200

        # Validate against 200 response schema
        res = schema_validator.validate_schema_by_response(
            SPEC_ENDPOINT_PATTERN,
            "get",
            "200",
            response,
        )
        assert res.get("valid"), f"200 response schema validation failed: {res}"
    else:
        # default error path must not be 2xx
        assert not (200 <= response.status_code < 300), f"Expected non-2xx for default error, got {response.status_code}"
        res = schema_validator.validate_schema_by_response(
            SPEC_ENDPOINT_PATTERN,
            "get",
            "default",
            response,
        )
        assert res.get("valid"), f"Default error schema validation failed: {res}"


@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_list_schedules_pagination_follow_next_token(
    api_client,
    config_test_data: Dict[str, Any],
    schema_validator: SwaggerSchemaValidator,
    scenario_case: Dict[str, Any],
):
    """
    Pagination boundary test:
    - First request uses required params (and optional page-token if present in scenario)
    - If 200 and response provides next_page_token, calls the endpoint again with that token
    - Validates schema for both responses
    """
    if not _PARAM_CASES:
        pytest.skip(f"Endpoint test data file missing or empty: {TEST_DATA_FILENAME}")

    merged = _merge_test_data(config_test_data, scenario_case)
    project_slug = merged.get("project-slug")
    if not project_slug:
        pytest.skip("Required 'project-slug' not configured in config.yml test_data or ENDPOINT_TEST_DATA")

    initial_params = _build_query_params(scenario_case)
    endpoint = _endpoint_from_slug(project_slug)

    # Initial call
    response = api_client.get(endpoint, params=initial_params)

    if response.status_code != 200:
        # Validate default error and exit early (cannot paginate)
        res_err = schema_validator.validate_schema_by_response(
            SPEC_ENDPOINT_PATTERN,
            "get",
            "default",
            response,
        )
        assert res_err.get("valid"), f"Default error schema validation failed: {res_err}"
        pytest.skip(f"Initial request did not return 200; status={response.status_code}. Skipping pagination follow-up.")

    # Validate initial 200
    res_ok = schema_validator.validate_schema_by_response(
        SPEC_ENDPOINT_PATTERN,
        "get",
        "200",
        response,
    )
    assert res_ok.get("valid"), f"200 response schema validation failed: {res_ok}"

    # Attempt to follow next_page_token if present and not null
    try:
        body = json.loads(response.text)
    except Exception:
        pytest.skip("Could not parse JSON body for pagination check; skipping follow-up")

    next_token = body.get("next_page_token")
    if not next_token:
        pytest.skip("No next_page_token present; pagination boundary not applicable for this case")

    follow_params = dict(initial_params)
    follow_params["page-token"] = next_token

    response_follow = api_client.get(endpoint, params=follow_params)

    if response_follow.status_code == 200:
        res_ok2 = schema_validator.validate_schema_by_response(
            SPEC_ENDPOINT_PATTERN,
            "get",
            "200",
            response_follow,
        )
        assert res_ok2.get("valid"), f"200 follow-up schema validation failed: {res_ok2}"
    else:
        # Validate using default error schema for follow-up
        assert not (200 <= response_follow.status_code < 300), f"Expected non-2xx for default error, got {response_follow.status_code}"
        res_def2 = schema_validator.validate_schema_by_response(
            SPEC_ENDPOINT_PATTERN,
            "get",
            "default",
            response_follow,
        )
        assert res_def2.get("valid"), f"Default error follow-up schema validation failed: {res_def2}"
