# ********RoostGPT********

# Test generated by RoostGPT for test azure-karate-apitest using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Testing the Laureates API (GET)

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Verify the Laureate API request
    Given path '/2.1/laureates'
    And param offset = '<offset>'
    And param limit = '<limit>'
    And param sort = '<sort>'
    And param ID = '<id>'
    When method get
    Then status '<status>'
    And match each response == '#object'
    * def actual = response
    * match each actual.laureates[*].id contains '<id>'

    Examples: 
    | offset | limit | sort | id  | status | 
    | 10     | 5    | asc  |  1  | 200    |
    |  0     | 10   | desc |  2  | 200    |
    |  5     | 3    | asc  |  3  | 200    |
    |  2     | 7    | desc |  4  | 200    |
