# ********RoostGPT********

# Test generated by RoostGPT for test azure-karate-apitest using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: GET requests for Nobel Prizes API

  Given path '/2.1/nobelPrizes'
  And param offset = '<offset>'
  And param limit = '<limit>'
  And param sort = '<sort>'
  And param nobelPrizeYear = '<nobelPrizeYear>'
  And param yearTo = '<yearTo>'
  And param nobelPrizeCategory = '<nobelPrizeCategory>'
  And param format = '<format>'
  And param csvLang = '<csvLang>'
  When method get
  Then status 200
  And match response contains {nobelPrizes: '#array'}
  And match each response.nobelPrizes[*] contains {awardYear: '#integer', category: '#string', dateAwarded: '#string', prizeAmount: '#integer', prizeAmountAdjusted: '#integer'}
  
  Examples: 
    |offset | limit | sort | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
    | 1     |  2    | asc  | 1990            | 1992   | eco                | json   | en      |
    | 2     |  3    | desc | 2000            | 2002   | phy                | csv    | se      |

Scenario Outline: Test error scenarios for Nobel Prizes API

  Given path '/2.1/nobelPrizes'
  And param offset = '<offset>'
  And param limit = '<limit>'
  And param sort = '<sort>'
  And param nobelPrizeYear = '<nobelPrizeYear>'
  And param yearTo = '<yearTo>'
  And param nobelPrizeCategory = '<nobelPrizeCategory>'
  And param format = '<format>'
  And param csvLang = '<csvLang>'
  When method get
  Then status <status>
  And match response contains {code: '#string', message: '#string'}
  
  Examples: 
    |offset | limit | sort | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang | status |
    | 1     |  2    | asc  | 1980            | 1982   | abc                | json   | en      | 400    |
    | 2     |  3    | desc | 2000            | 2002   | phy                | csv    | se      | 422    |
