# ********RoostGPT********

# Test generated by RoostGPT for test karate-sample-api-claude using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=adfce3f1d2
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Get Nobel Prize by category and year
  Given path '/2.1/nobelPrize/<category>/<year>'
  When method GET
  Then status 200
  And match response.nobelPrize.awardYear == <year>
  And match response.nobelPrize.category.en == <categoryEn>
  And match response.nobelPrize.categoryFullName.en == <categoryFullNameEn>
  And match response.nobelPrize.dateAwarded == '#? _ =~ /\\d{4}-\\d{2}-\\d{2}/'
  And match response.nobelPrize.prizeAmount == '#number'
  And match response.nobelPrize.prizeAmountAdjusted == '#number'
  And match response.nobelPrize.topMotivation.en == '#string'
  And match each response.nobelPrize.laureates == 
  """
  {
    id: '#number',
    name: {
      en: '#string'  
    },
    portion: '#string',
    sortOrder: '#string',
    motivation: {
      en: '#string'
    },
    links: '#[] link'
  }
  """
  
  Examples:
    | category | year | categoryEn | categoryFullNameEn |
    | che      | 2020 | Chemistry  | Chemistry          |
    | eco      | 2019 | Economic Sciences | Economic Sciences |
    | lit      | 2018 | Literature | Literature         |
    | pea      | 2017 | Peace      | Peace              |  
    | phy      | 2016 | Physics    | Physics            |
    | med      | 2015 | Medicine   | Physiology or Medicine |

Scenario Outline: Get Nobel Prize with invalid category
  Given path '/2.1/nobelPrize/<category>/<year>'
  When method GET
  Then status 400
  And match response == 
  """
  {
    code: '400',
    message: 'Bad request.The request could not be understood by the server due to malformed syntax, modifications needed.'
  }
  """

  Examples:
    | category | year |
    | invalid  | 2020 |
    | test     | 2019 |

Scenario Outline: Get Nobel Prize with invalid year
  Given path '/2.1/nobelPrize/<category>/<year>'
  When method GET 
  Then status 404
  And match response ==
  """
  {
    code: '404',
    message: 'Not Found. The requested resource could not be found but may be available again in the future.'  
  }
  """

  Examples:
    | category | year |
    | che      | 1800 |
    | eco      | 2100 |

Scenario Outline: Get Nobel Prize with invalid category and year
  Given path '/2.1/nobelPrize/<category>/<year>'
  When method GET
  Then status 422 
  And match response ==
  """
  {
    code: '422',
    message: 'Unprocessable Entity. The request was well-formed but was unable to be followed due to semantic errors.'
  }  
  """

  Examples:
    | category | year |
    | invalid  | 1800 |
    | test     | 2100 |
