# ********RoostGPT********

# Test generated by RoostGPT for test api-karate-petstore-v3 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /pet/{petId}_delete for http method type DELETE 
# RoostTestHash=1909018834
# 
# 

# ********RoostGPT********
Feature: Validate /pet/{petId} API Endpoint Functionality

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Validate DELETE /pet/{petId} API with different inputs
    Given path 'pet', <petId>
    And method DELETE
    And header api_key = <api_key>
    When status <expectedStatus>
    Then assert response contains
      """
      <expectedResponse>
      """

    Examples:
      | petId | api_key    | expectedStatus | expectedResponse                 |
      |  1001 | null       |            200 | { "description": "Pet deleted" } |
      |  1002 | "test_key" |            200 | { "description": "Pet deleted" } |
