# ********RoostGPT********

# Test generated by RoostGPT for test api-karate-customer-management-v3 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /user/{username}_get for http method type GET 
# RoostTestHash=c0fb7cdf2c
# 
# 

# ********RoostGPT********
Feature: Test API endpoint: /user/{username}
  Description: Validate the functionality of the /user/{username} endpoint by performing HTTP requests and verifying responses.

  Background:
    Given karate.properties['URL_BASE'] || karate.get('urlBase', 'http://localhost:4010')
    And configure baseUrl = urlBase
    And configure headers =
      """
      {
        Authorization: "#(karate.properties['AUTH_TOKEN'])"
      }
      """

  Scenario Outline: Get user by username - Successful operation
    Given path 'user', <username>
    When method GET
    Then status 200
    And match response ==
      """
      {
        id: "#number",
        username: "#string",
        firstName: "#string",
        lastName: "#string",
        email: "#string",
        password: "#string",
        phone: "#string",
        userStatus: "#number"
      }
      """

    Examples:
      | read('user_username_get.csv') |

  Scenario Outline: Get user by username - Invalid username supplied
    Given path 'user', <username>
    When method GET
    Then status 400
    And match response ==
      """
      {
        message: "#string"
      }
      """

    Examples:
      | username     |
      | invalid_user |

  Scenario Outline: Get user by username - User not found
    Given path 'user', <username>
    When method GET
    Then status 404
    And match response ==
      """
      {
        message: "#string"
      }
      """

    Examples:
      | username          |
      | non_existing_user |
