// ********RoostGPT********
/*
Test generated by RoostGPT for test dm-rest-assured-test using AI Type AWS Bedrock Runtime AI and AI Model eu.anthropic.claude-3-7-sonnet-20250219-v1:0

Test generated for /ip.json_get for http method type GET in rest-assured framework

RoostTestHash=b9106bf55e

[
  {
    "ScenarioID": "1",
    "TestName": "testValidIPLookupReturns200",
    "Description": "Test a valid request with proper IP address parameter",
    "Execution": {
      "Arrange": "Prepare a valid IP address '8.8.8.8' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with correct API key and query param",
      "Assert": "Check for 200 status and response body contains IP information including ip, type, continent_code, country_name, etc."
    },
    "Validation": "Ensures API successfully returns correct IP information for a valid IP address"
  },
  {
    "ScenarioID": "2",
    "TestName": "testMissingQueryParameterReturns400",
    "Description": "Test request without required 'q' parameter",
    "Execution": {
      "Arrange": "Prepare a request with valid API key but without 'q' parameter",
      "Act": "Send GET request to /v1/ip.json without query parameter",
      "Assert": "Check for 400 status code and error response with code 1003 and message 'Parameter 'q' not provided.'"
    },
    "Validation": "Ensures API correctly handles missing required parameter"
  },
  {
    "ScenarioID": "3",
    "TestName": "testMissingAPIKeyReturns401",
    "Description": "Test request without API key authentication",
    "Execution": {
      "Arrange": "Prepare a valid IP address '8.8.8.8' for query param 'q' but no API key",
      "Act": "Send GET request to /v1/ip.json with query param but without API key",
      "Assert": "Check for 401 status code and error response with code 1002 and message 'API key not provided'"
    },
    "Validation": "Ensures API enforces authentication requirement correctly"
  },
  {
    "ScenarioID": "4",
    "TestName": "testInvalidAPIKeyReturns401",
    "Description": "Test request with invalid API key",
    "Execution": {
      "Arrange": "Prepare a valid IP address '8.8.8.8' for query param 'q' and invalid API key",
      "Act": "Send GET request to /v1/ip.json with query param and invalid API key",
      "Assert": "Check for 401 status code and error response with code 2006 and message 'API key provided is invalid'"
    },
    "Validation": "Ensures API correctly validates API key authenticity"
  },
  {
    "ScenarioID": "5",
    "TestName": "testAPIKeyExceededQuotaReturns403",
    "Description": "Test request with API key that has exceeded quota",
    "Execution": {
      "Arrange": "Prepare a valid IP address and API key that has exceeded its monthly quota",
      "Act": "Send GET request to /v1/ip.json with query param and over-quota API key",
      "Assert": "Check for 403 status code and error response with code 2007 and message 'API key has exceeded calls per month quota.'"
    },
    "Validation": "Ensures API correctly enforces quota limitations"
  },
  {
    "ScenarioID": "6",
    "TestName": "testInvalidIPAddressFormatReturns400",
    "Description": "Test request with improperly formatted IP address",
    "Execution": {
      "Arrange": "Prepare an invalid IP address format '999.999.999.999' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with invalid IP address format",
      "Assert": "Check for 400 status code and error response with code 1006 and message containing 'No location found matching parameter'"
    },
    "Validation": "Ensures API correctly validates IP address format"
  },
  {
    "ScenarioID": "7",
    "TestName": "testNonExistentIPAddressReturns400",
    "Description": "Test request with non-existent IP address",
    "Execution": {
      "Arrange": "Prepare a non-existent IP address '0.0.0.0' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with non-existent IP address",
      "Assert": "Check for 400 status code and error response with code 1006 and message 'No location found matching parameter'"
    },
    "Validation": "Ensures API correctly handles non-existent IP addresses"
  },
  {
    "ScenarioID": "8",
    "TestName": "testIPv6AddressLookupReturns200",
    "Description": "Test a valid request with an IPv6 address",
    "Execution": {
      "Arrange": "Prepare a valid IPv6 address '2001:4860:4860::8888' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with IPv6 address",
      "Assert": "Check for 200 status and response body contains IPv6 information with type field showing 'ipv6'"
    },
    "Validation": "Ensures API successfully processes IPv6 addresses"
  },
  {
    "ScenarioID": "9",
    "TestName": "testEmptyQueryParameterReturns400",
    "Description": "Test request with empty 'q' parameter",
    "Execution": {
      "Arrange": "Prepare an empty string '' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with empty query parameter",
      "Assert": "Check for 400 status code and appropriate error response"
    },
    "Validation": "Ensures API correctly handles empty parameter values"
  },
  {
    "ScenarioID": "10",
    "TestName": "testDisabledAPIKeyReturns403",
    "Description": "Test request with disabled API key",
    "Execution": {
      "Arrange": "Prepare a valid IP address and API key that has been disabled",
      "Act": "Send GET request to /v1/ip.json with query param and disabled API key",
      "Assert": "Check for 403 status code and error response with code 2008 and message 'API key has been disabled.'"
    },
    "Validation": "Ensures API correctly handles disabled API keys"
  },
  {
    "ScenarioID": "11",
    "TestName": "testInsufficientSubscriptionPlanReturns403",
    "Description": "Test request with API key that doesn't have access to this resource",
    "Execution": {
      "Arrange": "Prepare a valid IP address and API key with insufficient subscription plan",
      "Act": "Send GET request to /v1/ip.json with query param and API key with insufficient permissions",
      "Assert": "Check for 403 status code and error response with code 2009 and message containing 'API key does not have access to the resource'"
    },
    "Validation": "Ensures API correctly enforces subscription plan limitations"
  },
  {
    "ScenarioID": "12",
    "TestName": "testSpecialCharactersInIPAddressReturns400",
    "Description": "Test request with special characters in 'q' parameter",
    "Execution": {
      "Arrange": "Prepare a string with special characters '192.168.1.1@#$' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with special characters in IP address",
      "Assert": "Check for 400 status code and appropriate error response"
    },
    "Validation": "Ensures API correctly handles invalid input with special characters"
  },
  {
    "ScenarioID": "13",
    "TestName": "testMultipleIPAddressesInParameterReturns400",
    "Description": "Test request with multiple IP addresses in one parameter",
    "Execution": {
      "Arrange": "Prepare multiple IP addresses '8.8.8.8,8.8.4.4' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with multiple IP addresses",
      "Assert": "Check for 400 status code as the endpoint expects a single IP address"
    },
    "Validation": "Ensures API correctly handles attempts to query multiple IPs at once"
  },
  {
    "ScenarioID": "14",
    "TestName": "testVeryLongStringAsIPAddressReturns400",
    "Description": "Test request with very long string as IP address",
    "Execution": {
      "Arrange": "Prepare a very long string (1000+ characters) for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with very long string",
      "Assert": "Check for 400 status code and appropriate error response"
    },
    "Validation": "Ensures API correctly handles excessively long input parameters"
  },
  {
    "ScenarioID": "15",
    "TestName": "testAlphabeticalStringAsIPAddressReturns400",
    "Description": "Test request with alphabetical string as IP address",
    "Execution": {
      "Arrange": "Prepare an alphabetical string 'notanipaddress' for query param 'q' and valid API key",
      "Act": "Send GET request to /v1/ip.json with alphabetical string",
      "Assert": "Check for 400 status code and error response with code 1006"
    },
    "Validation": "Ensures API correctly validates that input is an IP address format"
  }
]

*/

// ********RoostGPT********
package org.springframework.RoostTest;

import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class IpJsonGetTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/org/springframework/RoostTest/ip.jsonGetTest.JSON");
    }


    @Test
    public void IpJsonGet_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "https://api.weatherapi.com/v1";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/ip.json";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "/var/tmp/Roost/RoostGPT/dm-rest-assured-test/61bece4e-22fb-4a2a-8d15-3463f21d5d8d/weather.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("get".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "get");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: IpJsonGet_Test\n", testNumber++);
            System.out.println("Request: GET " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
