// ********RoostGPT********
/*
Test generated by RoostGPT for test dm-rest-assured-test using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219

Test generated for /timezone.json_get for http method type GET in rest-assured framework

RoostTestHash=fe6df42816

[
  {
    "ScenarioID": "1",
    "TestName": "testValidZipcodeReturnsCorrectTimezone",
    "Description": "Test that a valid US zipcode returns the correct timezone information",
    "Execution": {
      "Arrange": "Prepare a valid API key and US zipcode '10001' as query parameter",
      "Act": "Send GET request to /v1/timezone.json?q=10001 with API key in header",
      "Assert": "Check for 200 status code and response contains expected timezone data for New York"
    },
    "Validation": "Ensures API successfully returns timezone data for a valid US zipcode"
  },
  {
    "ScenarioID": "2",
    "TestName": "testValidCityNameReturnsCorrectTimezone",
    "Description": "Test that a valid city name returns the correct timezone information",
    "Execution": {
      "Arrange": "Prepare a valid API key and city name 'London' as query parameter",
      "Act": "Send GET request to /v1/timezone.json?q=London with API key in header",
      "Assert": "Check for 200 status code and response contains expected timezone data for London"
    },
    "Validation": "Ensures API successfully returns timezone data for a valid city name"
  },
  {
    "ScenarioID": "3",
    "TestName": "testValidLatLongReturnsCorrectTimezone",
    "Description": "Test that valid latitude/longitude coordinates return the correct timezone information",
    "Execution": {
      "Arrange": "Prepare a valid API key and coordinates '40.71,-74.01' as query parameter",
      "Act": "Send GET request to /v1/timezone.json?q=40.71,-74.01 with API key in header",
      "Assert": "Check for 200 status code and response contains expected timezone data for New York"
    },
    "Validation": "Ensures API successfully returns timezone data for valid latitude/longitude coordinates"
  },
  {
    "ScenarioID": "4",
    "TestName": "testValidIPAddressReturnsCorrectTimezone",
    "Description": "Test that a valid IP address returns the correct timezone information",
    "Execution": {
      "Arrange": "Prepare a valid API key and IP address '8.8.8.8' as query parameter",
      "Act": "Send GET request to /v1/timezone.json?q=8.8.8.8 with API key in header",
      "Assert": "Check for 200 status code and response contains timezone data for the IP location"
    },
    "Validation": "Ensures API successfully returns timezone data for a valid IP address"
  },
  {
    "ScenarioID": "5",
    "TestName": "testMissingQueryParameterReturns400",
    "Description": "Test that omitting the required 'q' parameter returns a 400 error",
    "Execution": {
      "Arrange": "Prepare a valid API key but no query parameter",
      "Act": "Send GET request to /v1/timezone.json without the 'q' parameter",
      "Assert": "Check for 400 status code and error code 1003 with message 'Parameter 'q' not provided'"
    },
    "Validation": "Ensures API correctly handles missing required query parameter"
  },
  {
    "ScenarioID": "6",
    "TestName": "testEmptyQueryParameterReturns400",
    "Description": "Test that providing an empty 'q' parameter returns a 400 error",
    "Execution": {
      "Arrange": "Prepare a valid API key and empty query parameter 'q='",
      "Act": "Send GET request to /v1/timezone.json?q= with API key in header",
      "Assert": "Check for 400 status code and appropriate error message"
    },
    "Validation": "Ensures API correctly handles empty query parameter"
  },
  {
    "ScenarioID": "7",
    "TestName": "testInvalidLocationReturns400",
    "Description": "Test that providing an invalid location returns a 400 error",
    "Execution": {
      "Arrange": "Prepare a valid API key and invalid location 'NonExistentCity12345' as query parameter",
      "Act": "Send GET request to /v1/timezone.json?q=NonExistentCity12345 with API key in header",
      "Assert": "Check for 400 status code and error code 1006 with message 'No location found matching parameter'"
    },
    "Validation": "Ensures API correctly handles invalid location input"
  },
  {
    "ScenarioID": "8",
    "TestName": "testMissingAPIKeyReturns401",
    "Description": "Test that omitting the API key returns a 401 error",
    "Execution": {
      "Arrange": "Prepare a valid query parameter 'q=London' but no API key",
      "Act": "Send GET request to /v1/timezone.json?q=London without API key in header",
      "Assert": "Check for 401 status code and error code 1002 with message 'API key not provided'"
    },
    "Validation": "Ensures API correctly enforces authentication requirement"
  },
  {
    "ScenarioID": "9",
    "TestName": "testInvalidAPIKeyReturns401",
    "Description": "Test that providing an invalid API key returns a 401 error",
    "Execution": {
      "Arrange": "Prepare a valid query parameter 'q=London' and invalid API key 'invalid_key_12345'",
      "Act": "Send GET request to /v1/timezone.json?q=London with invalid API key in header",
      "Assert": "Check for 401 status code and error code 2006 with message 'API key provided is invalid'"
    },
    "Validation": "Ensures API correctly validates API key authenticity"
  },
  {
    "ScenarioID": "10",
    "TestName": "testExceededQuotaReturns403",
    "Description": "Test that exceeding the API call quota returns a 403 error",
    "Execution": {
      "Arrange": "Prepare a valid query parameter 'q=London' and API key that has exceeded its quota",
      "Act": "Send GET request to /v1/timezone.json?q=London with the quota-exceeded API key",
      "Assert": "Check for 403 status code and error code 2007 with message 'API key has exceeded calls per month quota'"
    },
    "Validation": "Ensures API correctly enforces usage quotas"
  },
  {
    "ScenarioID": "11",
    "TestName": "testDisabledAPIKeyReturns403",
    "Description": "Test that using a disabled API key returns a 403 error",
    "Execution": {
      "Arrange": "Prepare a valid query parameter 'q=London' and a disabled API key",
      "Act": "Send GET request to /v1/timezone.json?q=London with the disabled API key",
      "Assert": "Check for 403 status code and error code 2008 with message 'API key has been disabled'"
    },
    "Validation": "Ensures API correctly handles disabled API keys"
  },
  {
    "ScenarioID": "12",
    "TestName": "testInsufficientSubscriptionReturns403",
    "Description": "Test that using an API key without access to the resource returns a 403 error",
    "Execution": {
      "Arrange": "Prepare a valid query parameter 'q=London' and API key with insufficient subscription level",
      "Act": "Send GET request to /v1/timezone.json?q=London with the insufficient-access API key",
      "Assert": "Check for 403 status code and error code 2009 with message about API key not having access to the resource"
    },
    "Validation": "Ensures API correctly enforces subscription-based access control"
  },
  {
    "ScenarioID": "13",
    "TestName": "testSpecialCharactersInQueryParameter",
    "Description": "Test that query parameter with special characters is handled correctly",
    "Execution": {
      "Arrange": "Prepare a valid API key and query parameter with special characters 'q=New York, NY'",
      "Act": "Send GET request to /v1/timezone.json?q=New%20York,%20NY with API key in header",
      "Assert": "Check for 200 status code and response contains expected timezone data for New York"
    },
    "Validation": "Ensures API correctly handles special characters in query parameters"
  },
  {
    "ScenarioID": "14",
    "TestName": "testResponseSchemaValidation",
    "Description": "Test that the response schema matches the expected format",
    "Execution": {
      "Arrange": "Prepare a valid API key and query parameter 'q=Sydney'",
      "Act": "Send GET request to /v1/timezone.json?q=Sydney with API key in header",
      "Assert": "Check for 200 status code and validate all required fields (name, region, country, lat, lon, tz_id, localtime_epoch, localtime) are present and of correct type"
    },
    "Validation": "Ensures API response adheres to the documented schema"
  },
  {
    "ScenarioID": "15",
    "TestName": "testInvalidURLReturns400",
    "Description": "Test that an invalid API request URL returns a 400 error",
    "Execution": {
      "Arrange": "Prepare a valid API key and intentionally malformed URL",
      "Act": "Send GET request to /v1/timezone.json/invalid with API key in header",
      "Assert": "Check for 400 status code and error code 1005 with message 'API request url is invalid'"
    },
    "Validation": "Ensures API correctly handles invalid request URLs"
  }
]

*/

// ********RoostGPT********
package org.springframework.RoostTest;

import org.json.JSONObject;
import org.json.JSONArray;
import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.*;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;
import org.hamcrest.MatcherAssert;

public class TimezoneJsonGetTest {

    List<JSONObject> testCases = new ArrayList<>();

    @BeforeEach
    public void setUp() {
        TestdataLoader dataloader = new TestdataLoader();
        testCases = dataloader.loadJson("src/test/java/org/springframework/RoostTest/timezone.jsonGetTest.JSON");
    }


    @Test
    public void TimezoneJsonGet_Test() {
        this.setUp();
        Integer testNumber = 1;
        for (JSONObject testData : testCases) {
            RestAssured.baseURI = "https://api.weatherapi.com/v1";

            JSONObject requestHeader = testData.optJSONObject("request_header");
            JSONObject requestBody = testData.optJSONObject("request_body");
            JSONObject queryParams = testData.optJSONObject("query_params");
            JSONObject pathParams = testData.optJSONObject("path_params");
            String requestPath = "/timezone.json";

            if (pathParams != null) {
                for (String key : pathParams.keySet()) {
                    requestPath = requestPath.replace("{" + key + "}", pathParams.getString(key));
                }
            }

            io.restassured.specification.RequestSpecification req = given();

            // Resolve Authorization token priority: ENV > Param(RoostENV) > JSON
            String userEnvAuthToken = System.getenv("AUTH_TOKEN");
            String resolvedAuthToken = (userEnvAuthToken != null && !userEnvAuthToken.isEmpty()) ? userEnvAuthToken : "/var/tmp/Roost/RoostGPT/dm-rest-assured-test/31645934-e72e-4cf7-8afe-f2dd963d7f79/weather.yaml";

            boolean authSet = false;
            if (requestHeader != null) {
                Iterator<String> keys = requestHeader.keys();
                while (keys.hasNext()) {
                    String key = keys.next();
                    String value = requestHeader.getString(key);

                    if (key.equalsIgnoreCase("Authorization")) {
                        if (value.equalsIgnoreCase("${AUTH_TOKEN}") && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                            req.header("Authorization", "Bearer " + resolvedAuthToken);
                            authSet = true;
                        } else {
                            req.header(key, value);
                            authSet = true;
                        }
                    } else {
                        req.header(key, value);
                    }
                }
            }

            if (!authSet && resolvedAuthToken != null && !resolvedAuthToken.isEmpty()) {
                req.header("Authorization", "Bearer " + resolvedAuthToken);
            }

            if (queryParams != null) {
                for (String key : queryParams.keySet()) {
                    req.queryParam(key, queryParams.get(key));
                }
            }

            if (requestBody != null && requestBody.length() > 0) {
                req.body(requestBody.toString());
            }

            Response responseObj;
            switch ("get".toLowerCase()) {
              case "post":
                responseObj = req.when().post(requestPath);
                break;
              case "get":
                responseObj = req.when().get(requestPath);
                break;
              case "put":
                responseObj = req.when().put(requestPath);
                break;
              case "delete":
                responseObj = req.when().delete(requestPath);
                break;
              default:
                throw new RuntimeException("Unsupported HTTP method: " + "get");
            }

            responseObj = responseObj.then().extract().response();

            System.out.printf("Test Case %d: TimezoneJsonGet_Test\n", testNumber++);
            System.out.println("Request: GET " + requestPath);
            System.out.println("Status Code: " + responseObj.statusCode());

            if (testData.has("expected_status_code")) {
                int expectedCode = testData.getInt("expected_status_code");
                MatcherAssert.assertThat(
                    "Expected status code " + expectedCode + " but got " + responseObj.statusCode(),
                    responseObj.statusCode(),
                    equalTo(expectedCode)
                );
            }
        }
    }
}
