# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-aviation-weather using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-5-20250929-v1:0
# 
# Test file generated for /api/data/metar_get for http method type GET 
# RoostTestHash=23d1bed220
# 
# 

# ********RoostGPT********
"""
Test suite for METAR API endpoint
Tests the /api/data/metar endpoint with various scenarios
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator


# Load test data from JSON file
def load_test_data():
    """Load test data from api_data_metar.json"""
    test_data_path = Path(__file__).parent / "api_data_metar.json"
    with open(test_data_path, 'r') as f:
        return json.load(f)


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize schema validator with API spec"""
    spec_path = Path(__file__).parent / "api.json"
    return SwaggerSchemaValidator(str(spec_path))


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load endpoint-specific test data"""
    return load_test_data()


class TestMetarEndpoint:
    """Test class for METAR endpoint"""
    
    endpoint = "/api/data/metar"
    
    @pytest.mark.smoke
    @pytest.mark.parametrize("test_case", load_test_data())
    def test_metar_successful_responses(self, api_client, schema_validator, test_case):
        """
        Test METAR endpoint with valid data from JSON file
        Validates successful responses with status code 200
        """
        # Extract test parameters
        params = {}
        
        if "ids" in test_case:
            params["ids"] = test_case["ids"]
        
        if "format" in test_case:
            params["format"] = test_case["format"]
        
        expected_status = test_case.get("statusCode", 200)
        scenario = test_case.get("scenario", "")
        
        # Make API request
        response = api_client.get(self.endpoint, params=params)
        
        # Assert status code
        assert response.status_code == expected_status, (
            f"Expected {expected_status} but got {response.status_code}. "
            f"Scenario: {scenario}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code=str(expected_status),
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}. "
            f"Scenario: {scenario}"
        )
    
    def test_metar_with_bbox_parameter(self, api_client, schema_validator):
        """
        Test METAR endpoint with bbox parameter
        Uses bounding box instead of station IDs
        """
        params = {
            "bbox": "40,-90,45,-85"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200 but got {response.status_code}"
        )
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
    
    @pytest.mark.parametrize("format_type", [
        "raw", "decoded", "json", "geojson", "xml", "iwxxm"
    ])
    def test_metar_different_formats(self, api_client, schema_validator, format_type):
        """
        Test METAR endpoint with different format parameters
        Validates all supported format types
        """
        params = {
            "ids": "KORD",
            "format": format_type
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200 but got {response.status_code} for format={format_type}"
        )
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed for format={format_type}: "
            f"{validation_result.get('message')}"
        )
    
    def test_metar_with_optional_parameters(self, api_client, schema_validator):
        """
        Test METAR endpoint with optional parameters
        Includes taf, hours, and date parameters along with required ids
        """
        params = {
            "ids": "KORD",
            "taf": True,
            "hours": 2.0,
            "format": "json"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
    
    def test_metar_with_date_parameter(self, api_client, schema_validator):
        """
        Test METAR endpoint with date parameter
        Uses ISO 8601 date format
        """
        params = {
            "ids": "KJFK",
            "date": "2023-12-20T00:00:00.000Z"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
    
    def test_metar_missing_required_parameters(self, api_client, schema_validator):
        """
        Test METAR endpoint without required parameters
        Should return 400 - Bad Request
        """
        # No ids or bbox provided
        params = {}
        
        response = api_client.get(self.endpoint, params=params)
        
        # API should return 400 for missing required parameters
        assert response.status_code == 400, (
            f"Expected 400 for missing required params but got {response.status_code}"
        )
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="400",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
    
    def test_metar_invalid_station_id(self, api_client):
        """
        Test METAR endpoint with invalid station ID
        Tests error handling for non-existent stations
        """
        params = {
            "ids": "INVALID_STATION_ID_12345"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        # API may return 200 with empty results or 400 for invalid format
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 but got {response.status_code}"
        )
    
    def test_metar_multiple_station_ids(self, api_client, schema_validator):
        """
        Test METAR endpoint with multiple comma-separated station IDs
        Validates handling of multiple stations
        """
        params = {
            "ids": "KORD,KJFK,KLAX,KSEA",
            "format": "json"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
        
        # Verify response is a list/array
        if response.headers.get("Content-Type", "").startswith("application/json"):
            data = response.json()
            assert isinstance(data, list), "Response should be an array for multiple IDs"
    
    def test_metar_state_abbreviation(self, api_client, schema_validator):
        """
        Test METAR endpoint with state abbreviation parameter
        Uses @STATE format as per API specification
        """
        params = {
            "ids": "@WA",
            "format": "json"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
    
    @pytest.mark.parametrize("invalid_format", [
        "invalid_format",
        "pdf",
        "csv",
        "12345"
    ])
    def test_metar_invalid_format_parameter(self, api_client, invalid_format):
        """
        Test METAR endpoint with invalid format values
        Should handle invalid format gracefully
        """
        params = {
            "ids": "KORD",
            "format": invalid_format
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        # API may return 400 for invalid format or default to raw format
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for invalid format but got {response.status_code}"
        )
    
    def test_metar_boundary_hours_parameter(self, api_client, schema_validator):
        """
        Test METAR endpoint with boundary values for hours parameter
        Tests minimum and maximum reasonable hour values
        """
        params = {
            "ids": "KORD",
            "hours": 24,
            "format": "json"
        }
        
        response = api_client.get(self.endpoint, params=params)
        
        assert response.status_code == 200
        
        validation_result = schema_validator.validate_schema_by_response(
            endpoint=self.endpoint,
            method="GET",
            status_code="200",
            response=response
        )
        
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
    
    def test_metar_response_content_types(self, api_client):
        """
        Test METAR endpoint returns correct content types
        Validates Content-Type header matches requested format
        """
        test_cases = [
            ("json", "application/json"),
            ("xml", "application/xml"),
            ("geojson", "application/geo+json"),
            ("raw", "text/plain")
        ]
        
        for format_type, expected_content_type in test_cases:
            params = {
                "ids": "KORD",
                "format": format_type
            }
            
            response = api_client.get(self.endpoint, params=params)
            
            assert response.status_code == 200
            
            content_type = response.headers.get("Content-Type", "").split(";")[0].strip()
            assert expected_content_type in content_type, (
                f"Expected content type to contain {expected_content_type} "
                f"but got {content_type} for format={format_type}"
            )
