# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-aviation-weather using AI Type AWS Bedrock Runtime AI and AI Model global.anthropic.claude-sonnet-4-5-20250929-v1:0
# 
# Test file generated for /api/data/airport_get for http method type GET 
# RoostTestHash=761dae4ef2
# 
# 

# ********RoostGPT********
"""
Comprehensive pytest test suite for Airport API endpoint
Tests cover all response scenarios using table-driven testing approach
"""

import pytest
import json
import os
import yaml
import requests
from typing import Dict, Any
from validator import SwaggerSchemaValidator


# Load configuration
def load_config():
    """Load configuration from config.yml"""
    config_path = os.path.join(os.path.dirname(__file__), 'config.yml')
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)


# Load test data
def load_test_data():
    """Load test data from api_data_airport.json"""
    data_path = os.path.join(os.path.dirname(__file__), 'api_data_airport.json')
    with open(data_path, 'r') as f:
        return json.load(f)


@pytest.fixture(scope="module")
def config():
    """Fixture to provide configuration data"""
    return load_config()


@pytest.fixture(scope="module")
def validator():
    """Fixture to provide schema validator"""
    return SwaggerSchemaValidator('https://aviationweather.gov/data/schema/openapi.yaml')


@pytest.fixture(scope="module")
def test_data():
    """Fixture to provide test data from JSON file"""
    return load_test_data()


@pytest.fixture(scope="module")
def base_url(config):
    """Fixture to provide base URL from config"""
    return config['api']['base_url']


@pytest.fixture(scope="module")
def endpoint_path(config):
    """Fixture to provide endpoint path from config"""
    return config['api']['endpoints']['airport']


@pytest.fixture(scope="module")
def timeout(config):
    """Fixture to provide timeout configuration"""
    return config['api']['timeout']


@pytest.fixture(scope="module")
def retry_config(config):
    """Fixture to provide retry configuration"""
    return config['api']['retry']


class TestAirportEndpoint:
    """Test suite for /api/data/airport endpoint"""

    def test_airport_endpoint_all_scenarios(
        self, 
        base_url, 
        endpoint_path, 
        test_data, 
        validator, 
        timeout
    ):
        """
        Table-driven test for all airport endpoint scenarios
        
        This test iterates through all test cases from api_data_airport.json
        and validates:
        - Request parameters
        - Response status codes
        - Response schema compliance
        - Response data structure
        """
        full_url = f"{base_url}{endpoint_path}"
        
        for index, test_case in enumerate(test_data):
            scenario = test_case.get('scenario', 'Unknown scenario')
            expected_status = test_case['statusCode']
            
            # Build query parameters from test data
            params = {}
            if test_case.get('ids'):
                params['ids'] = test_case['ids']
            if test_case.get('bbox'):
                params['bbox'] = test_case['bbox']
            if test_case.get('format'):
                params['format'] = test_case['format']
            
            # Make API request
            try:
                response = requests.get(
                    full_url,
                    params=params,
                    timeout=timeout
                )
                
                # Validate status code
                assert response.status_code == expected_status, (
                    f"Test case {index + 1} ({scenario}): "
                    f"Expected status {expected_status}, got {response.status_code}. "
                    f"Response: {response.text}"
                )
                
                # Validate response based on status code
                if expected_status == 200:
                    self._validate_success_response(
                        response, 
                        validator, 
                        test_case, 
                        index, 
                        scenario
                    )
                elif expected_status == 400:
                    self._validate_error_response(
                        response, 
                        validator, 
                        test_case, 
                        index, 
                        scenario
                    )
                
            except requests.exceptions.Timeout:
                pytest.fail(
                    f"Test case {index + 1} ({scenario}): Request timed out"
                )
            except requests.exceptions.RequestException as e:
                pytest.fail(
                    f"Test case {index + 1} ({scenario}): Request failed - {str(e)}"
                )

    def _validate_success_response(
        self, 
        response: requests.Response, 
        validator: SwaggerSchemaValidator, 
        test_case: Dict[str, Any],
        index: int,
        scenario: str
    ):
        """
        Validate successful (200) response
        
        Validates:
        - Content type
        - Response schema
        - Data structure
        """
        # Check content type
        content_type = response.headers.get('Content-Type', '')
        
        # Parse response based on format
        response_format = test_case.get('format', 'json')
        
        if response_format in ['json', 'geojson', 'decoded']:
            assert 'application/json' in content_type or 'text/plain' in content_type, (
                f"Test case {index + 1} ({scenario}): "
                f"Expected JSON content type, got {content_type}"
            )
            
            try:
                response_data = response.json()
            except json.JSONDecodeError:
                pytest.fail(
                    f"Test case {index + 1} ({scenario}): "
                    f"Failed to parse JSON response"
                )
            
            # Validate response is an array
            assert isinstance(response_data, list), (
                f"Test case {index + 1} ({scenario}): "
                f"Expected array response, got {type(response_data)}"
            )
            
            # Validate each item in the array against schema
            if len(response_data) > 0:
                for item_index, item in enumerate(response_data):
                    try:
                        # Get the schema for airport items from OpenAPI spec
                        # The 200 response schema defines an array of airport objects
                        airport_schema = {
                            "type": "object",
                            "properties": {
                                "icaoId": {"type": "string"},
                                "iataId": {"type": "string"},
                                "faaId": {"type": "string"},
                                "name": {"type": "string"},
                                "state": {"type": "string"},
                                "country": {"type": "string"},
                                "source": {"type": "string"},
                                "type": {"type": "string"},
                                "lat": {"type": ["string", "number"]},
                                "lon": {"type": ["string", "number"]},
                                "elev": {"type": ["string", "number"]},
                                "magdec": {"type": "string"},
                                "owner": {"type": "string"},
                                "runways": {"type": "array"}
                            }
                        }
                        
                        validator.validate_with_schema(item, airport_schema)
                        
                    except Exception as e:
                        pytest.fail(
                            f"Test case {index + 1} ({scenario}): "
                            f"Schema validation failed for item {item_index}: {str(e)}"
                        )
        
        elif response_format == 'xml':
            assert 'application/xml' in content_type or 'text/xml' in content_type, (
                f"Test case {index + 1} ({scenario}): "
                f"Expected XML content type, got {content_type}"
            )
            # XML response validation - check that response is not empty
            assert len(response.text) > 0, (
                f"Test case {index + 1} ({scenario}): "
                f"Empty XML response"
            )

    def _validate_error_response(
        self, 
        response: requests.Response, 
        validator: SwaggerSchemaValidator, 
        test_case: Dict[str, Any],
        index: int,
        scenario: str
    ):
        """
        Validate error (400) response
        
        Validates:
        - Content type
        - Error response schema
        - Error message presence
        """
        content_type = response.headers.get('Content-Type', '')
        response_format = test_case.get('format', 'json')
        
        if 'application/json' in content_type or 'text/plain' in content_type:
            try:
                response_data = response.json()
            except json.JSONDecodeError:
                pytest.fail(
                    f"Test case {index + 1} ({scenario}): "
                    f"Failed to parse error JSON response"
                )
            
            # Validate error response schema
            error_schema = {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "string",
                        "enum": ["error"]
                    },
                    "error": {
                        "type": "string"
                    }
                }
            }
            
            try:
                validator.validate_with_schema(response_data, error_schema)
            except Exception as e:
                # Some error responses might have different structure
                # At minimum, verify it's an object with error information
                assert isinstance(response_data, (dict, list)), (
                    f"Test case {index + 1} ({scenario}): "
                    f"Expected error object or array, got {type(response_data)}"
                )
        
        elif 'application/xml' in content_type or 'text/xml' in content_type:
            # XML error response validation
            assert len(response.text) > 0, (
                f"Test case {index + 1} ({scenario}): "
                f"Empty XML error response"
            )
            # Check for error-related XML elements
            assert 'error' in response.text.lower() or 'warning' in response.text.lower(), (
                f"Test case {index + 1} ({scenario}): "
                f"XML response missing error indicators"
            )


class TestAirportEndpointParameterValidation:
    """Test suite for parameter validation scenarios"""

    def test_valid_single_icao_id(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test single ICAO ID parameter
        
        Validates that a single valid ICAO ID returns successful response
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'KMCI', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 200, (
            f"Single ICAO ID request failed: {response.status_code}"
        )
        
        response_data = response.json()
        assert isinstance(response_data, list), "Response should be an array"

    def test_valid_multiple_icao_ids(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test multiple ICAO IDs parameter
        
        Validates that comma-separated ICAO IDs return successful response
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'KMCI,KORD,KBOS', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 200, (
            f"Multiple ICAO IDs request failed: {response.status_code}"
        )
        
        response_data = response.json()
        assert isinstance(response_data, list), "Response should be an array"

    def test_valid_state_abbreviation(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test state abbreviation parameter
        
        Validates that state abbreviation (@XX) returns successful response
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': '@WA', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 200, (
            f"State abbreviation request failed: {response.status_code}"
        )
        
        response_data = response.json()
        assert isinstance(response_data, list), "Response should be an array"

    def test_valid_bbox_parameter(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test bounding box parameter
        
        Validates that valid bbox coordinates return successful response
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'bbox': '40,-90,45,-85', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 200, (
            f"Bounding box request failed: {response.status_code}"
        )
        
        response_data = response.json()
        assert isinstance(response_data, list), "Response should be an array"

    def test_all_format_types(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test all supported format types
        
        Validates that all format options (decoded, json, geojson) work correctly
        """
        full_url = f"{base_url}{endpoint_path}"
        formats = ['decoded', 'json', 'geojson']
        
        for fmt in formats:
            params = {'ids': 'KMCI', 'format': fmt}
            response = requests.get(full_url, params=params, timeout=timeout)
            
            assert response.status_code == 200, (
                f"Format '{fmt}' request failed: {response.status_code}"
            )


class TestAirportEndpointEdgeCases:
    """Test suite for edge cases and boundary conditions"""

    def test_empty_parameters(
        self, 
        base_url, 
        endpoint_path, 
        timeout
    ):
        """
        Test request with no parameters
        
        Validates behavior when no query parameters are provided
        """
        full_url = f"{base_url}{endpoint_path}"
        
        response = requests.get(full_url, timeout=timeout)
        
        # Should either succeed with all airports or return validation error
        assert response.status_code in [200, 400], (
            f"Unexpected status code: {response.status_code}"
        )

    def test_invalid_format_parameter(
        self, 
        base_url, 
        endpoint_path, 
        timeout
    ):
        """
        Test invalid format parameter
        
        Validates that invalid format values return appropriate error
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'KMCI', 'format': 'invalid_format'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 400, (
            f"Expected 400 for invalid format, got: {response.status_code}"
        )

    def test_malformed_bbox(
        self, 
        base_url, 
        endpoint_path, 
        timeout
    ):
        """
        Test malformed bounding box parameter
        
        Validates that invalid bbox format returns appropriate error
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'bbox': 'invalid_bbox_format', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 400, (
            f"Expected 400 for invalid bbox, got: {response.status_code}"
        )

    def test_out_of_range_bbox_coordinates(
        self, 
        base_url, 
        endpoint_path, 
        timeout
    ):
        """
        Test out-of-range bounding box coordinates
        
        Validates that bbox coordinates outside valid range return error
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'bbox': '200.0,100.0,-300.0,-200.0', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 400, (
            f"Expected 400 for out-of-range bbox, got: {response.status_code}"
        )

    def test_special_characters_in_ids(
        self, 
        base_url, 
        endpoint_path, 
        timeout
    ):
        """
        Test special characters in IDs parameter
        
        Validates that IDs with special characters are rejected
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'INVALID123@#$', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 400, (
            f"Expected 400 for invalid IDs, got: {response.status_code}"
        )

    def test_excessively_long_id(
        self, 
        base_url, 
        endpoint_path, 
        timeout
    ):
        """
        Test excessively long station ID
        
        Validates that overly long IDs are rejected
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'TOOLONGSTATIONIDTHATEXCEEDSLIMIT', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 400, (
            f"Expected 400 for excessively long ID, got: {response.status_code}"
        )


class TestAirportEndpointResponseStructure:
    """Test suite for response structure validation"""

    def test_successful_response_contains_required_fields(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test that successful responses contain expected airport fields
        
        Validates presence of key fields in airport objects
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'KMCI', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 200, (
            f"Request failed: {response.status_code}"
        )
        
        response_data = response.json()
        
        if len(response_data) > 0:
            airport = response_data[0]
            
            # Check for expected fields (based on OpenAPI spec)
            expected_fields = ['icaoId', 'name', 'lat', 'lon']
            
            for field in expected_fields:
                assert field in airport, (
                    f"Airport object missing expected field: {field}"
                )

    def test_response_data_types(
        self, 
        base_url, 
        endpoint_path, 
        validator, 
        timeout
    ):
        """
        Test that response fields have correct data types
        
        Validates data types of airport object fields
        """
        full_url = f"{base_url}{endpoint_path}"
        params = {'ids': 'KMCI', 'format': 'json'}
        
        response = requests.get(full_url, params=params, timeout=timeout)
        
        assert response.status_code == 200, (
            f"Request failed: {response.status_code}"
        )
        
        response_data = response.json()
        
        if len(response_data) > 0:
            airport = response_data[0]
            
            # Validate string fields
            string_fields = ['icaoId', 'iataId', 'faaId', 'name', 'state', 'country']
            for field in string_fields:
                if field in airport:
                    assert isinstance(airport[field], str), (
                        f"Field '{field}' should be string, got {type(airport[field])}"
                    )
            
            # Validate runways is an array
            if 'runways' in airport:
                assert isinstance(airport['runways'], list), (
                    f"Field 'runways' should be array, got {type(airport['runways'])}"
                )
