# ********RoostGPT********

# Test generated by RoostGPT for test roostgpt-apispec using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /test/event/{trigger_id}_get for http method type GET 
# RoostTestHash=0f3f0c41d6
# 
# 

# ********RoostGPT********
Feature: Test Event API - Get One Event

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: #('Bearer ' + karate.properties['bearer']) }

  Scenario Outline: Get event by trigger ID - Success
    Given path '/test/event/<trigger_id>'
    When method GET
    Then status 200
    And match response == '#object'

    Examples:
      | read('test_event_trigger_id_get.csv') |

  Scenario Outline: Get event by trigger ID - Not Found
    Given path '/test/event/<trigger_id>'
    When method GET
    Then status 404
    And match response == '#object'
    And match response.code == '#number'
    And match response.code == 404
    And match response.message == '#string'
    And match response.message == 'Not found'
    And match response.method == '#string'
    And match response.method == 'GET'
    And match response.path == '#string'
    And match response.path contains '/test/event/'
    And match response.timestamp == '#string'
    And match response.timestamp == '#? karate.match(_, "####-##-##T##:##:##").pass'

    Examples:
      | trigger_id  |
      | nonexistent |
      | invalid123  |
      | notfound456 |

  Scenario Outline: Get event by trigger ID - Client Error
    Given path '/test/event/<trigger_id>'
    When method GET
    Then status 400
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'
    And match response.method == '#string'
    And match response.method == 'GET'
    And match response.path == '#string'
    And match response.timestamp == '#string'
    And match response.timestamp == '#? karate.match(_, "####-##-##T##:##:##").pass'

    Examples:
      | trigger_id |
      |            |
      |            |

  Scenario Outline: Get event by trigger ID - Server Error
    Given path '/test/event/<trigger_id>'
    When method GET
    Then status 500
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'
    And match response.method == '#string'
    And match response.method == 'GET'
    And match response.path == '#string'
    And match response.timestamp == '#string'
    And match response.timestamp == '#? karate.match(_, "####-##-##T##:##:##").pass'

    Examples:
      | trigger_id  |
      | serverError |

  Scenario: Get event without authorization
    * configure headers = null
    Given path '/test/event/test123'
    When method GET
    Then status 401

  Scenario Outline: Get event with invalid authorization
    * configure headers = { Authorization: '<auth_header>' }
    Given path '/test/event/test123'
    When method GET
    Then status 401

    Examples:
      | auth_header    |
      | Bearer invalid |
      | Basic invalid  |
      | invalid_token  |

  Scenario Outline: Validate error response structure for different HTTP methods
    Given path '/test/event/test123'
    When method <method>
    Then status >= 400
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'
    And match response.method == '#string'
    And match response.method == '<method>'
    And match response.path == '#string'
    And match response.path contains '/test/event/'
    And match response.timestamp == '#string'
    And match response.timestamp == '#? karate.match(_, "####-##-##T##:##:##").pass'

    Examples:
      | method  |
      | POST    |
      | PUT     |
      | DELETE  |
      | PATCH   |
      | HEAD    |
      | OPTIONS |
