# ********RoostGPT********

# Test generated by RoostGPT for test Karate_Test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /GetAccountInfo_post for http method type POST 
# RoostTestHash=9598896c7c
# 
# 

# ********RoostGPT********
Feature: Get Account Information API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def headers = { Authorization: 'Bearer <token>', botId: '<botId>', accountId: '<accountId>' }

  Scenario Outline: Validate successful retrieval of account information
    Given path 'GetAccountInfo'
    And request
      """
      { 
        customerId: <customerId> 
      }
      """
    And headers headers
    When method POST
    Then status 200
    And match response == '#object'
    And match response.customerId == '#number'
    And match response.accounts == '#array'
    And match response.accounts[*].customerId == '#number'
    And match response.accounts[*].accountName == '#string'
    And match response.accounts[*].accountNickname == '#string'
    And match response.accounts[*].accountNumber == '#string'
    And match response.accounts[*].accountType == '#string'
    And match response.accounts[*].activatedDate == '#string'
    And match response.accounts[*].availableBalance == '#number'
    And match response.accounts[*].availableCash == '#number'
    And match response.accounts[*].availableCashLimit == '#number'
    And match response.accounts[*].availableCredit == '#number'
    And match response.accounts[*].bankName == '#string'
    And match response.accounts[*].branchName == '#string'
    And match response.accounts[*].cardName == '#string'
    And match response.accounts[*].cardNumber == '#string'
    And match response.accounts[*].cardStatus == '#string'
    And match response.accounts[*].cardType == '#string'
    And match response.accounts[*].creditLimit == '#number'
    And match response.accounts[*].currency == '#string'
    And match response.accounts[*].currentBalance == '#number'
    And match response.accounts[*].deactivatedDate == '#string'
    And match response.accounts[*].dueAmount == '#number'
    And match response.accounts[*].dueDate == '#string'
    And match response.accounts[*].earlyWithdrawalPenalty == '#number'
    And match response.accounts[*].email == '#string'
    And match response.accounts[*].expDate == '#string'
    And match response.accounts[*].fdType == '#string'
    And match response.accounts[*].image == '#string'
    And match response.accounts[*].interestRate == '#number'
    And match response.accounts[*].internalTransferFromEnabled == '#boolean'
    And match response.accounts[*].internalTransferToEnabled == '#boolean'
    And match response.accounts[*].isPrimaryMobile == '#boolean'
    And match response.accounts[*].isAlternateMobileNumber == '#boolean'
    And match response.accounts[*].isStatement == '#boolean'
    And match response.accounts[*].lastDrawDate == '#string'
    And match response.accounts[*].loanMaturityDate == '#string'
    And match response.accounts[*].loanOriginationDate == '#string'
    And match response.accounts[*].location == '#string'
    And match response.accounts[*].lastUpdated == '#string'
    And match response.accounts[*].maxTransactionLimit == '#string'
    And match response.accounts[*].maturityDate == '#string'
    And match response.accounts[*].minimumPaymentDue == '#string'
    And match response.accounts[*].minimumBalance == '#string'
    And match response.accounts[*].monthlyPayment == '#number'
    And match response.accounts[*].openingBalance == '#number'
    And match response.accounts[*].originalLoanAmount == '#number'
    And match response.accounts[*].P2PLimit == '#number'
    And match response.accounts[*].p2pEnabled == '#number'
    And match response.accounts[*].paybillEnabled == '#boolean'
    And match response.accounts[*].payoffAmount == '#number'
    And match response.accounts[*].personalBankerName == '#string'
    And match response.accounts[*].personalBankerContact == '#object'
    And match response.accounts[*].personalBankerContact.email == '#string'
    And match response.accounts[*].personalBankerContact.mobileNumber == '#string'
    And match response.accounts[*].phone == '#number'
    And match response.accounts[*].postedBalance == '#number'
    And match response.accounts[*].principalBalance == '#string'
    And match response.accounts[*].productCode == '#string'
    And match response.accounts[*].productName == '#string'
    And match response.accounts[*].propertyAddress == '#string'
    And match response.accounts[*].rewardPoints == '#string'
    And match response.accounts[*].routingNumber == '#string'
    And match response.accounts[*].statementDate == '#string'
    And match response.accounts[*].status == '#string'
    And match response.accounts[*].swiftCode == '#string'
    And match response.accounts[*].totalBalance == '#number'
    And match response.accounts[*].unbilledAmount == '#number'
    And match response.accounts[*].valueAtMaturity == '#number'
    And match response.accounts[*].holdAmount == '#number'
    And match response.accounts[*].unclearFundsAmount == '#number'
    And match response.accounts[*].averageMonthlyBalance == '#number'
    And match response.accounts[*].netWithdrawableBalance == '#number'
    And match response.accounts[*].totalTenure == '#string'
    And match response.accounts[*].remainingTenure == '#string'
    And match response.accounts[*].debitAccountNumber == '#string'
    And match response.accounts[*].lateFee == '#number'
    And match response.accounts[*].bounceCharge == '#number'
    And match response.accounts[*].totalCharges == '#number'
    And match response.accounts[*].overDueAmount == '#number'
    And match response.accounts[*].cardDetails == '#array'
    And match response.accounts[*].cardDetails[*].cardName == '#string'
    And match response.accounts[*].cardDetails[*].cardNumber == '#string'
    And match response.accounts[*].cardDetails[*].cardStatus == '#string'
    And match response.accounts[*].cardDetails[*].cardImage == '#string'
    And match response.accounts[*].cardDetails[*].cardType == '#string'
    And match response.accounts[*].cardDetails[*].expDate == '#string'
    And match response.accounts[*].cardDetails[*].displayCardStatus == '#string'
    And match response.accounts[*].cardDetails[*].primaryCard == '#string'
    And match response.accounts[*].cardDetails[*].cardChannelInfo == '#object'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.ATM == '#object'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.ATM.enable == '#boolean'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.ATM.limit == '#number'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.offline == '#object'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.offline.enable == '#boolean'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.offline.limit == '#number'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.international == '#object'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.international.enable == '#boolean'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.international.limit == '#number'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.online == '#object'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.online.enable == '#boolean'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.online.limit == '#number'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.contactless == '#object'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.contactless.enable == '#boolean'
    And match response.accounts[*].cardDetails[*].cardChannelInfo.contactless.limit == '#number'
    And match response.accounts[*].cardDetails[*].cardRestrictions == '#object'
    And match response.accounts[*].cardDetails[*].cardRestrictions.countries == '#array'
    And match response.accounts[*].cardDetails[*].cardRestrictions.countries[*].countrycode == '#string'
    And match response.accounts[*].cardDetails[*].cardRestrictions.MCC == '#array'
    And match response.accounts[*].cardDetails[*].cardRestrictions.MCC[*].name == '#string'
    And match response.accounts[*].cardDetails[*].cardRestrictions.MCC[*].description == '#string'
    And match response.accounts[*].cardDetails[*].blockReason == '#string'
    And match response.accounts[*].cardDetails[*].nameOnCard == '#string'
    And match response.accounts[*].cardDetails[*].cardNetwork == '#string'
    And match response.accounts[*].cardDetails[*].autopay == '#object'
    And match response.accounts[*].cardDetails[*].autopay.enabled == '#boolean'
    And match response.accounts[*].cardDetails[*].autopay.sourceAccountId == '#string'
    And match response.accounts[*].cardDetails[*].autopay.paymentType == '#string'
    And match response.accounts[*].cardDetails[*].autopay.onStatementDate == '#boolean'
    And match response.accounts[*].cardDetails[*].autopay.dayOfMonth == '#string'
    And match response.accounts[*].cardDetails[*].dueAmount == '#number'
    And match response.accounts[*].cardDetails[*].dueDate == '#string'
    And match response.accounts[*].cardDetails[*].minimumPaymentDue == '#number'
    And match response.accounts[*].cardDetails[*].partialPaymentPaid == '#number'
    And match response.accounts[*].IsCrossAccount == '#boolean'

    Examples:
      | read('GetAccountInfo_post.csv') |

  Scenario: Validate unauthorized access
    Given path 'GetAccountInfo'
    And request
      """
      { 
        customerId: 1045300 
      }
      """
    And headers
      """
      { 
        botId: '<botId>', 
        accountId: '<accountId>' 
      }
      """
    When method POST
    Then status 401
    And match response == '#object'
    And match response.err == '#object'
    And match response.err.message == '#string'

  Scenario: Validate not found error
    Given path 'GetAccountInfo'
    And request
      """
      { 
        customerId: 9999999 
      }
      """
    And headers headers
    When method POST
    Then status 404
    And match response == '#object'
    And match response.err == '#object'
    And match response.err.message == '#string'
