# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-karate-github-v3 using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /user/repos_post for http method type POST 
# RoostTestHash=96512b79aa
# 
# 

# ********RoostGPT********
Feature: Testing the /user/repos API endpoint

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Create a repository with valid payload
    Given path 'user/repos'
    And request
      """
      {
        "name": <repoName>
      }
      """
    When method POST
    Then status 200
    And match response == '#object'
    And match response.name == '#string'
    And match response.url == '#string'
    And match response.id == '#number'
    And match response.permissions == '#object'
    And match response.permissions.admin == '#boolean'
    And match response.permissions.push == '#boolean'
    And match response.permissions.pull == '#boolean'

    Examples:
      | read('user_repos_post.csv') |
