# ********RoostGPT********

# Test generated by RoostGPT for test Karate_Test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /insights/{project-slug}/workflows/{workflow-name}/jobs_get for http method type GET 
# RoostTestHash=f1a60c8fec
# 
# 

# ********RoostGPT********
Feature: Insights API - Workflow Job Metrics

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: 'Basic REPLACE_BASIC_AUTH' }

  Scenario Outline: Get summary metrics for a project workflow's jobs
    Given path 'insights', '<project-slug>', 'workflows', '<workflow-name>', 'jobs'
    And param page-token = <page-token>
    And param all-branches = <all-branches>
    And param branch = '<branch>'
    And param reporting-window = '<reporting-window>'
    And param job-name = '<job-name>'
    When method GET
    Then status 200
    And match response.items == '#[] object'
    And match response.items[*].name == '#string'
    And match response.items[*].metrics.total_runs == '#number'
    And match response.items[*].metrics.failed_runs == '#number'
    And match response.items[*].metrics.successful_runs == '#number'
    And match response.items[*].metrics.duration_metrics.min == '#number'
    And match response.items[*].metrics.duration_metrics.mean == '#number'
    And match response.items[*].metrics.duration_metrics.median == '#number'
    And match response.items[*].metrics.duration_metrics.p95 == '#number'
    And match response.items[*].metrics.duration_metrics.max == '#number'
    And match response.items[*].metrics.duration_metrics.standard_deviation == '#number'
    And match response.items[*].metrics.success_rate == '#number'
    And match response.items[*].metrics.total_credits_used == '#number'
    And match response.items[*].metrics.throughput == '#number'
    And match response.items[*].window_start == '#string'
    And match response.items[*].window_end == '#string'
    And match response.next_page_token == '#string?'

    Examples:
      | read('insights_project-slug_workflows_workflow-name_jobs_get.csv') |

  Scenario: Error response for invalid project slug
    Given path 'insights', 'invalid-slug', 'workflows', 'build-and-test', 'jobs'
    When method GET
    Then status 404
    And match response.message == '#string'

  Scenario: Error response for invalid workflow name
    Given path 'insights', 'gh/CircleCI-Public/api-preview-docs', 'workflows', 'invalid-workflow', 'jobs'
    When method GET
    Then status 404
    And match response.message == '#string'
