# ********RoostGPT********

# Test generated by RoostGPT for test Karate_Test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /jobs/{job-id}/cancel_post for http method type POST 
# RoostTestHash=647b98788e
# 
# 

# ********RoostGPT********
Feature: Cancel Job by Job ID
  This feature tests the cancel job endpoint for various scenarios including successful cancellation, invalid job ID, unauthorized access, and other error conditions.

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * header Authorization = 'Basic REPLACE_BASIC_AUTH'

  Scenario Outline: Cancel job with valid job ID
    Given path 'jobs', '<job-id>', 'cancel'
    When method POST
    Then status 200
    And match response == { message: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | read('jobs_job-id_cancel_post.csv') |

  Scenario Outline: Cancel job with invalid job ID
    Given path 'jobs', '<job-id>', 'cancel'
    When method POST
    Then status 404
    And match response == { message: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

    Examples:
      | job-id         |
      | invalid-job-id |

  Scenario: Cancel job without authorization
    Given path 'jobs', '123e4567-e89b-12d3-a456-426614174000', 'cancel'
    And header Authorization = ''
    When method POST
    Then status 401
    And match response == { message: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Cancel job with forbidden access
    Given path 'jobs', '123e4567-e89b-12d3-a456-426614174000', 'cancel'
    And header Authorization = 'Basic INVALID_AUTH'
    When method POST
    Then status 403
    And match response == { message: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Cancel job with bad request
    Given path 'jobs', '', 'cancel'
    When method POST
    Then status 400
    And match response == { message: '#string' }
    And match responseHeaders['Content-Type'] contains 'application/json'
