# ********RoostGPT********

# Test generated by RoostGPT for test Karate_Test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /webhook_get for http method type GET 
# RoostTestHash=6d6b46d312
# 
# 

# ********RoostGPT********
Feature: Webhook API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: 'Basic REPLACE_BASIC_AUTH' }

  Scenario Outline: Validate GET /webhook with valid parameters
    Given path 'webhook'
    And param scope-id = '<scopeId>'
    And param scope-type = '<scopeType>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.items == '#array'
    And match response.next_page_token == '#string?'
    And match response.items[*].id == '#uuid'
    And match response.items[*].scope == '#object'
    And match response.items[*].scope.id == '#uuid'
    And match response.items[*].scope.type == '#string'
    And match response.items[*].name == '#string'
    And match response.items[*].events == '#array'
    And match response.items[*].events[*] == '#string'
    And match response.items[*].url == '#string'
    And match response.items[*].verify-tls == '#boolean'
    And match response.items[*].signing-secret == '#string'
    And match response.items[*].created-at == '#string'
    And match response.items[*].updated-at == '#string'

    Examples:
      | read('webhook_get.csv') |

  Scenario: Validate GET /webhook with invalid scope-id
    Given path 'webhook'
    And param scope-id = 'invalid-uuid'
    And param scope-type = 'project'
    When method GET
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Validate GET /webhook with missing scope-type
    Given path 'webhook'
    And param scope-id = '123e4567-e89b-12d3-a456-426614174000'
    When method GET
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Validate GET /webhook with unsupported scope-type
    Given path 'webhook'
    And param scope-id = '123e4567-e89b-12d3-a456-426614174000'
    And param scope-type = 'unsupported'
    When method GET
    Then status 400
    And match response == '#object'
    And match response.message == '#string'
