# ********RoostGPT********

# Test generated by RoostGPT for test Karate_Test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /workflow/{id}/job_get for http method type GET 
# RoostTestHash=4e844ec00b
# 
# 

# ********RoostGPT********
Feature: Workflow Jobs API Tests
  This feature file contains tests for the Workflow Jobs API endpoint.

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authHeader = { Authorization: 'Basic REPLACE_BASIC_AUTH' }

  Scenario Outline: Get Workflow Jobs with Valid ID
    Given path 'workflow', '<id>', 'job'
    And headers authHeader
    When method GET
    Then status 200
    And match response == '#object'
    And match response.items == '#array'
    And match response.items[*].id == '#string'
    And match response.items[*].name == '#string'
    And match response.items[*].started_at == '#string'
    And match response.items[*].dependencies == '#array'
    And match response.items[*].project_slug == '#string'
    And match response.items[*].status == '#string'
    And match response.items[*].type == '#string'
    And match response.next_page_token == '#string?'

    Examples:
      | read('workflow_id_job_get.csv') |

  Scenario Outline: Get Workflow Jobs with Invalid ID
    Given path 'workflow', '<id>', 'job'
    And headers authHeader
    When method GET
    Then status 404
    And match response == '#object'
    And match response.message == '#string'

    Examples:
      | id         |
      | invalid-id |

  Scenario Outline: Get Workflow Jobs without Authorization
    Given path 'workflow', '<id>', 'job'
    When method GET
    Then status 401
    And match response == '#object'
    And match response.message == '#string'

    Examples:
      | id                                   |
      | 5034460f-c7c4-4c43-9457-de07e2029e7b |
