# ********RoostGPT********

# Test generated by RoostGPT for test Karate_Test using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /workflow/{id}_get for http method type GET 
# RoostTestHash=f69681bea0
# 
# 

# ********RoostGPT********
Feature: Workflow API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: 'Basic REPLACE_BASIC_AUTH' }

  Scenario Outline: Get Workflow by ID
    Given path 'workflow', '<id>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.id == '#uuid'
    And match response.name == '#string'
    And match response.status == '#string'
    And match response.created_at == '#date-time'
    And match response.stopped_at == '#? _ == null || _ == "#date-time"'
    And match response.pipeline_id == '#uuid'
    And match response.pipeline_number == '#number'
    And match response.project_slug == '#string'
    And match response.started_by == '#uuid'
    And match response.canceled_by == '#? _ == null || _ == "#uuid"'
    And match response.errored_by == '#? _ == null || _ == "#uuid"'
    And match response.tag == '#? _ == null || _ == "setup"'
    And match response.headers['Content-Type'] == 'application/json'

    Examples:
      | read('workflow_id_get.csv') |

  Scenario Outline: Get Workflow by Invalid ID
    Given path 'workflow', '<id>'
    When method GET
    Then status 404
    And match response == '#object'
    And match response.message == '#string'

    Examples:
      | id                                   |
      | invalid-id                           |
      | 00000000-0000-0000-0000-000000000000 |
