# ********RoostGPT********

# Test generated by RoostGPT for test api-test-weather using AI Type deepseek_ai and AI Model deepseek-chat
# 
# Test file generated for /api/data/gairmet_get for http method type GET 
# RoostTestHash=0ad69ad110
# 
# 

# ********RoostGPT********
import pytest
import json
from datetime import datetime, timezone


class TestGairmetAPI:
    """Test suite for /api/data/gairmet endpoint"""
    
    # Test data configurations
    VALID_HAZARDS = ["IFR", "MTN_OBSCN", "TURB", "ICE", "SFC_WND", "LLWS"]
    VALID_FORMATS = ["raw", "json", "geo+json", "xml"]
    VALID_TYPES = ["gairmet", "airmet"]
    
    @pytest.fixture
    def base_endpoint(self):
        return "/api/data/gairmet"
    
    @pytest.fixture
    def valid_date_strings(self):
        """Generate valid date strings for testing"""
        now = datetime.now(timezone.utc)
        date_str = now.strftime("%Y%m%d_%H%M")
        iso_date = now.strftime("%Y-%m-%dT%H:%M:%S.%fZ")[:-3] + "Z"
        return {
            "datetime": date_str,
            "iso": iso_date
        }
    
    @pytest.fixture
    def invalid_date_strings(self):
        """Generate invalid date strings for testing"""
        return {
            "invalid_format": "2023-13-45T25:61:61Z",
            "empty": "",
            "wrong_separator": "2023/12/20_00:00"
        }
    
    @pytest.fixture
    def sample_valid_params(self, valid_date_strings):
        """Sample valid parameter combinations"""
        return [
            {},  # No parameters
            {"format": "json"},
            {"format": "geo+json"},
            {"hazard": "IFR"},
            {"type": "gairmet"},
            {"date": valid_date_strings["datetime"]},
            {"date": valid_date_strings["iso"]},
            {"format": "json", "hazard": "TURB", "type": "gairmet"}
        ]
    
    @pytest.fixture
    def sample_invalid_params(self, invalid_date_strings):
        """Sample invalid parameter combinations"""
        return [
            {"format": "invalid_format"},
            {"date": invalid_date_strings["invalid_format"]},
            {"hazard": "INVALID_HAZARD"},
            {"type": "invalid_type"}
        ]

    # Happy Path Tests
    @pytest.mark.parametrize("params", [
        {},
        {"format": "json"},
        {"format": "geo+json"},
        {"hazard": "IFR"},
        {"type": "gairmet"},
        {"format": "json", "hazard": "TURB"}
    ])
    def test_get_gairmet_success(self, api_client, base_endpoint, params):
        """Test successful GET requests with various valid parameters"""
        response = api_client.get(base_endpoint, params=params)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        assert response.headers['Content-Type'] is not None
        
        # Validate response format based on requested format
        if params.get('format') == 'json':
            assert 'application/json' in response.headers['Content-Type']
            data = response.json()
            assert isinstance(data, list)
        elif params.get('format') == 'geo+json':
            assert 'application/geo+json' in response.headers['Content-Type']
            data = response.json()
            assert 'type' in data
            assert 'features' in data
        else:  # raw format (default)
            assert response.text is not None

    @pytest.mark.parametrize("format_type", ["json", "geo+json", "raw", "xml"])
    def test_get_gairmet_different_formats(self, api_client, base_endpoint, format_type):
        """Test GET requests with different format parameters"""
        params = {"format": format_type}
        response = api_client.get(base_endpoint, params=params)
        
        assert response.status_code == 200
        assert response.text is not None
        
        # Basic content validation based on format
        if format_type == "json":
            try:
                json_data = response.json()
                assert isinstance(json_data, list)
            except json.JSONDecodeError:
                pytest.fail("Response is not valid JSON")
        elif format_type == "geo+json":
            try:
                geo_json = response.json()
                assert 'type' in geo_json
            except json.JSONDecodeError:
                pytest.fail("Response is not valid GeoJSON")

    @pytest.mark.parametrize("hazard", ["IFR", "TURB", "ICE", "MTN_OBSCN"])
    def test_get_gairmet_different_hazards(self, api_client, base_endpoint, hazard):
        """Test GET requests with different hazard parameters"""
        params = {"hazard": hazard, "format": "json"}
        response = api_client.get(base_endpoint, params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        
        # If we have data, verify hazard field matches
        if data:
            for item in data:
                assert 'hazard' in item
                # Note: Some items might have different hazards in the response

    @pytest.mark.parametrize("date_param", [
        "202312200000",
        "2023-12-20T00:00:00.000Z"
    ])
    def test_get_gairmet_valid_dates(self, api_client, base_endpoint, date_param):
        """Test GET requests with valid date formats"""
        params = {"date": date_param, "format": "json"}
        response = api_client.get(base_endpoint, params=params)
        
        assert response.status_code in [200, 400]  # Could be valid or no data

    # Error Path Tests
    @pytest.mark.parametrize("invalid_params", [
        {"format": "invalid_format"},
        {"hazard": "INVALID_HAZARD_TYPE"},
        {"type": "unsupported_type"},
        {"date": "invalid_date_format"}
    ])
    def test_get_gairmet_bad_requests(self, api_client, base_endpoint, invalid_params):
        """Test GET requests with invalid parameters that should return 400"""
        response = api_client.get(base_endpoint, params=invalid_params)
        
        # Some invalid parameters might still return 200 with empty data
        # Only assert 400 for clearly invalid formats
        if invalid_params.get('format') == 'invalid_format':
            assert response.status_code == 400
            error_data = response.json()
            assert 'error' in error_data or 'errors' in error_data

    def test_get_gairmet_malformed_date(self, api_client, base_endpoint):
        """Test GET request with malformed date parameter"""
        params = {"date": "not_a_date", "format": "json"}
        response = api_client.get(base_endpoint, params=params)
        
        # Could be 400 or 200 with no data
        assert response.status_code in [200, 400]

    # Response Schema Validation Tests
    def test_gairmet_json_schema_validation(self, api_client, base_endpoint):
        """Validate JSON response schema against specification"""
        params = {"format": "json"}
        response = api_client.get(base_endpoint, params=params)
        
        if response.status_code == 200:
            data = response.json()
            
            if data:  # Only validate if we have data
                sample_item = data[0]
                
                # Check required fields from specification
                assert 'tag' in sample_item
                assert 'forecastHour' in sample_item
                assert 'validTime' in sample_item
                assert 'hazard' in sample_item
                assert 'geometryType' in sample_item
                assert 'latlonpairs' in sample_item
                assert 'due_to' in sample_item
                assert 'receiptTime' in sample_item
                assert 'issueTime' in sample_item
                assert 'expireTime' in sample_item
                assert 'product' in sample_item
                assert 'coords' in sample_item
                
                # Validate data types
                assert isinstance(sample_item['tag'], str)
                assert isinstance(sample_item['forecastHour'], int)
                assert isinstance(sample_item['validTime'], str)
                assert isinstance(sample_item['hazard'], str)
                assert isinstance(sample_item['coords'], list)

    def test_gairmet_geojson_schema_validation(self, api_client, base_endpoint):
        """Validate GeoJSON response schema against specification"""
        params = {"format": "geo+json"}
        response = api_client.get(base_endpoint, params=params)
        
        if response.status_code == 200:
            data = response.json()
            
            # Validate GeoJSON structure
            assert 'type' in data
            assert 'features' in data
            assert isinstance(data['features'], list)
            
            if data['features']:
                feature = data['features'][0]
                
                # Validate feature structure
                assert 'type' in feature
                assert 'id' in feature
                assert 'properties' in feature
                assert 'geometry' in feature
                
                # Validate properties
                props = feature['properties']
                assert 'tag' in props
                assert 'forecastHour' in props
                assert 'receiptTime' in props
                assert 'issueTime' in props
                assert 'validTime' in props
                assert 'hazard' in props
                assert 'due_to' in props
                assert 'product' in props
                
                # Validate geometry
                geometry = feature['geometry']
                assert 'type' in geometry
                assert 'coordinates' in geometry
                assert isinstance(geometry['coordinates'], list)

    # Edge Case Tests
    def test_get_gairmet_empty_parameters(self, api_client, base_endpoint):
        """Test GET request with empty parameter values"""
        params = {
            "type": "",
            "format": "",
            "hazard": "",
            "date": ""
        }
        response = api_client.get(base_endpoint, params=params)
        
        assert response.status_code in [200, 400]

    def test_get_gairmet_special_characters(self, api_client, base_endpoint):
        """Test GET request with special characters in parameters"""
        params = {
            "hazard": "IFR&TURB",
            "type": "gairmet-test"
        }
        response = api_client.get(base_endpoint, params=params)
        
        assert response.status_code in [200, 400]

    # Performance and Reliability Tests
    def test_get_gairmet_response_time(self, api_client, base_endpoint):
        """Test that response time is within acceptable limits"""
        import time
        
        start_time = time.time()
        response = api_client.get(base_endpoint)
        end_time = time.time()
        
        response_time = end_time - start_time
        assert response.status_code == 200
        assert response_time < 10  # Should respond within 10 seconds

    def test_get_gairmet_concurrent_requests(self, api_client, base_endpoint):
        """Test handling of concurrent requests"""
        import concurrent.futures
        
        def make_request():
            return api_client.get(base_endpoint, params={"format": "json"})
        
        # Make multiple concurrent requests
        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
            futures = [executor.submit(make_request) for _ in range(5)]
            results = [future.result() for future in concurrent.futures.as_completed(futures)]
        
        # All requests should succeed
        for result in results:
            assert result.status_code in [200, 400]

    # Header and Content-Type Tests
    @pytest.mark.parametrize("accept_header,expected_content_type", [
        ("application/json", "application/json"),
        ("application/geo+json", "application/geo+json"),
        ("text/plain", "text/plain"),
        ("application/xml", "application/xml")
    ])
    def test_get_gairmet_accept_headers(self, api_client, base_endpoint, accept_header, expected_content_type):
        """Test GET requests with different Accept headers"""
        headers = {"Accept": accept_header}
        response = api_client.get(base_endpoint, headers=headers)
        
        assert response.status_code == 200
        assert expected_content_type in response.headers.get('Content-Type', '')

    # Default Value Tests
    def test_get_gairmet_default_format(self, api_client, base_endpoint):
        """Test that default format is applied when not specified"""
        response = api_client.get(base_endpoint)  # No format parameter
        
        assert response.status_code == 200
        # Default format should be raw (text/plain)
        assert 'text/plain' in response.headers.get('Content-Type', '')
