# ********RoostGPT********

# Test generated by RoostGPT for test api-test-weather using AI Type deepseek_ai and AI Model deepseek-chat
# 
# Test file generated for /api/data/navaid_get for http method type GET 
# RoostTestHash=44811d1d10
# 
# 

# ********RoostGPT********
import pytest
import requests


class TestNavaidAPI:
    """Test suite for /api/data/navaid endpoint"""
    
    def test_get_navaid_success_no_params(self, api_client):
        """Test successful GET request without parameters"""
        response = api_client.get("/api/data/navaid")
        
        assert response.status_code == 200
        assert response.headers['Content-Type'] == 'application/json'
        assert isinstance(response.json(), list)
    
    def test_get_navaid_with_valid_ids(self, api_client):
        """Test GET request with valid ids parameter"""
        params = {"ids": "MCI"}
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        if len(data) > 0:
            assert data[0]['id'] == 'MCI'
    
    def test_get_navaid_with_valid_bbox(self, api_client):
        """Test GET request with valid bounding box"""
        params = {"bbox": "40,-90,45,-85"}
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
    
    def test_get_navaid_with_format_param(self, api_client):
        """Test GET request with format parameter"""
        params = {"format": "raw"}
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code == 200
        assert response.headers['Content-Type'] == 'application/json'
    
    @pytest.mark.parametrize("ids_param", ["ABC", "XYZ", "123"])
    def test_get_navaid_with_different_ids(self, api_client, ids_param):
        """Test GET request with various ids parameters"""
        params = {"ids": ids_param}
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code in [200, 400]
    
    @pytest.mark.parametrize("bbox_param", [
        "40,-90,45,-85",
        "35,-120,40,-115",
        "0,0,10,10"
    ])
    def test_get_navaid_with_different_bbox(self, api_client, bbox_param):
        """Test GET request with various bounding boxes"""
        params = {"bbox": bbox_param}
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code in [200, 400]
    
    def test_get_navaid_with_multiple_params(self, api_client):
        """Test GET request with multiple parameters"""
        params = {
            "ids": "MCI",
            "bbox": "40,-90,45,-85",
            "format": "raw"
        }
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
    
    def test_get_navaid_response_schema_validation(self, api_client):
        """Test response schema validation"""
        response = api_client.get("/api/data/navaid")
        
        assert response.status_code == 200
        data = response.json()
        
        if len(data) > 0:
            item = data[0]
            assert 'id' in item
            assert 'type' in item
            assert 'name' in item
            assert 'state' in item
            assert 'country' in item
            assert 'lat' in item
            assert 'lon' in item
            assert 'elev' in item
            assert 'freq' in item
            assert 'mag_dec' in item
    
    def test_get_navaid_with_invalid_bbox_format(self, api_client):
        """Test GET request with invalid bounding box format"""
        params = {"bbox": "invalid_format"}
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code == 400
    
    def test_get_navaid_with_empty_string_params(self, api_client):
        """Test GET request with empty string parameters"""
        params = {
            "ids": "",
            "bbox": "",
            "format": ""
        }
        response = api_client.get("/api/data/navaid", params=params)
        
        assert response.status_code in [200, 400]
    
    def test_get_navaid_response_time(self, api_client):
        """Test response time performance"""
        import time
        start_time = time.time()
        response = api_client.get("/api/data/navaid")
        end_time = time.time()
        
        assert response.status_code == 200
        assert (end_time - start_time) < 5  # Should respond within 5 seconds
    
    @pytest.mark.parametrize("invalid_param", [
        {"invalid_param": "value"},
        {"ids": "TOO_LONG_IDENTIFIER"},
        {"bbox": "90,180,91,181"}  # Invalid coordinates
    ])
    def test_get_navaid_with_invalid_parameters(self, api_client, invalid_param):
        """Test GET request with various invalid parameters"""
        response = api_client.get("/api/data/navaid", params=invalid_param)
        
        assert response.status_code in [200, 400]
