# ********RoostGPT********

# Test generated by RoostGPT for test api-test-weather using AI Type deepseek_ai and AI Model deepseek-chat
# 
# Test file generated for /api/data/gairmet_get for http method type GET 
# RoostTestHash=0ad69ad110
# 
# 

# ********RoostGPT********
import pytest
import json
from datetime import datetime, timedelta

class TestGairmetAPI:
    """Test suite for /api/data/gairmet endpoint"""
    
    # Test data configurations
    VALID_HAZARDS = ["IFR", "MTN_OBSCN", "TURB", "ICE", "SFC_WND", "LLWS"]
    VALID_FORMATS = ["raw", "json", "application/json", "application/geo+json", "application/xml", "text/plain"]
    
    @pytest.fixture
    def valid_date_strings(self):
        """Generate valid date strings for testing"""
        now = datetime.utcnow()
        return {
            "yyyymmdd_hhmm": now.strftime("%Y%m%d_%H%M"),
            "iso_8601": now.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
            "past_date": (now - timedelta(days=1)).strftime("%Y%m%d_0000")
        }
    
    @pytest.fixture
    def invalid_date_strings(self):
        """Generate invalid date strings for testing"""
        return {
            "invalid_format": "2023-13-45T25:61:61.000Z",
            "malformed": "not_a_date",
            "empty": ""
        }
    
    @pytest.fixture
    def sample_gairmet_payload(self):
        """Sample valid payload for testing"""
        return {
            "type": "gairmet",
            "format": "json",
            "hazard": "IFR",
            "date": datetime.utcnow().strftime("%Y%m%d_0000")
        }

    # Happy path tests
    def test_get_gairmet_success_default_params(self, api_client):
        """Test GET /api/data/gairmet with default parameters"""
        response = api_client.get("/api/data/gairmet")
        
        assert response.status_code == 200
        assert response.headers['Content-Type'] in ['text/plain', 'application/json', 'application/geo+json', 'application/xml']
    
    @pytest.mark.parametrize("format_type", VALID_FORMATS)
    def test_get_gairmet_different_formats(self, api_client, format_type):
        """Test GET /api/data/gairmet with different format parameters"""
        params = {"format": format_type}
        response = api_client.get("/api/data/gairmet", params=params)
        
        assert response.status_code == 200
        
        content_type = response.headers.get('Content-Type', '')
        if format_type == "json" or format_type == "application/json":
            assert "application/json" in content_type
            if response.content:  # Only validate JSON if there's content
                json_data = response.json()
                assert isinstance(json_data, (list, dict))
        elif format_type == "application/geo+json":
            assert "application/geo+json" in content_type or "application/json" in content_type
        elif format_type == "application/xml":
            assert "application/xml" in content_type or "text/xml" in content_type
        elif format_type == "text/plain":
            assert "text/plain" in content_type
    
    @pytest.mark.parametrize("hazard", VALID_HAZARDS)
    def test_get_gairmet_different_hazards(self, api_client, hazard):
        """Test GET /api/data/gairmet with different hazard parameters"""
        params = {"hazard": hazard, "format": "json"}
        response = api_client.get("/api/data/gairmet", params=params)
        
        assert response.status_code == 200
        if response.content:
            data = response.json()
            if data and isinstance(data, list) and len(data) > 0:
                for item in data:
                    if "hazard" in item:
                        assert item["hazard"] == hazard
    
    def test_get_gairmet_with_valid_dates(self, api_client, valid_date_strings):
        """Test GET /api/data/gairmet with valid date parameters"""
        for date_type, date_value in valid_date_strings.items():
            params = {"date": date_value, "format": "json"}
            response = api_client.get("/api/data/gairmet", params=params)
            
            assert response.status_code in [200, 400]  # Could be valid but no data
    
    def test_get_gairmet_combined_parameters(self, api_client, sample_gairmet_payload):
        """Test GET /api/data/gairmet with combined valid parameters"""
        response = api_client.get("/api/data/gairmet", params=sample_gairmet_payload)
        
        assert response.status_code == 200
    
    # Error scenario tests
    def test_get_gairmet_invalid_date_format(self, api_client, invalid_date_strings):
        """Test GET /api/data/gairmet with invalid date formats"""
        for date_type, date_value in invalid_date_strings.items():
            params = {"date": date_value}
            response = api_client.get("/api/data/gairmet", params=params)
            
            # Should either return 400 or handle gracefully with 200
            assert response.status_code in [200, 400]
            if response.status_code == 400:
                error_data = response.json()
                assert "error" in error_data or "errors" in error_data
    
    def test_get_gairmet_invalid_hazard(self, api_client):
        """Test GET /api/data/gairmet with invalid hazard parameter"""
        params = {"hazard": "INVALID_HAZARD_TYPE", "format": "json"}
        response = api_client.get("/api/data/gairmet", params=params)
        
        assert response.status_code in [200, 400]
        if response.status_code == 400:
            error_data = response.json()
            assert "error" in error_data or "errors" in error_data
    
    def test_get_gairmet_invalid_format(self, api_client):
        """Test GET /api/data/gairmet with invalid format parameter"""
        params = {"format": "invalid_format"}
        response = api_client.get("/api/data/gairmet", params=params)
        
        assert response.status_code in [200, 400]
    
    # Response validation tests
    def test_gairmet_json_response_structure(self, api_client):
        """Validate JSON response structure against OpenAPI spec"""
        params = {"format": "json"}
        response = api_client.get("/api/data/gairmet", params=params)
        
        if response.status_code == 200 and response.content:
            data = response.json()
            
            if isinstance(data, list) and len(data) > 0:
                first_item = data[0]
                
                # Check required fields from spec
                expected_fields = ["tag", "forecastHour", "validTime", "hazard", "geometryType", 
                                 "latlonpairs", "due_to", "receiptTime", "issueTime", "expireTime", "product"]
                
                for field in expected_fields:
                    if field in first_item:
                        # Type validation based on spec
                        if field == "tag":
                            assert isinstance(first_item[field], str)
                        elif field == "forecastHour":
                            assert isinstance(first_item[field], int)
                        elif field == "validTime":
                            assert isinstance(first_item[field], str)
                        elif field == "hazard":
                            assert isinstance(first_item[field], str)
                        elif field == "geometryType":
                            assert isinstance(first_item[field], str)
                        elif field == "latlonpairs":
                            assert isinstance(first_item[field], int)
                        elif field == "due_to":
                            assert isinstance(first_item[field], str)
                        elif field in ["receiptTime", "issueTime", "expireTime"]:
                            assert isinstance(first_item[field], int)
                        elif field == "product":
                            assert isinstance(first_item[field], str)
                
                # Check coordinates structure if present
                if "coords" in first_item and first_item["coords"]:
                    coord_item = first_item["coords"][0]
                    assert "lat" in coord_item
                    assert "lon" in coord_item
                    assert isinstance(coord_item["lat"], (int, float))
                    assert isinstance(coord_item["lon"], (int, float))
    
    def test_gairmet_geojson_response_structure(self, api_client):
        """Validate GeoJSON response structure against OpenAPI spec"""
        params = {"format": "application/geo+json"}
        response = api_client.get("/api/data/gairmet", params=params)
        
        if response.status_code == 200 and response.content:
            data = response.json()
            
            # Validate GeoJSON structure
            assert "type" in data
            assert "features" in data
            assert isinstance(data["features"], list)
            
            if len(data["features"]) > 0:
                feature = data["features"][0]
                
                # Check feature structure
                assert "type" in feature
                assert "id" in feature
                assert "properties" in feature
                assert "geometry" in feature
                
                # Check properties
                props = feature["properties"]
                expected_props = ["tag", "forecastHour", "receiptTime", "issueTime", 
                                "validTime", "hazard", "due_to", "product"]
                
                for prop in expected_props:
                    if prop in props:
                        if prop in ["forecastHour"]:
                            assert isinstance(props[prop], int)
                        else:
                            assert isinstance(props[prop], str)
                
                # Check geometry
                geometry = feature["geometry"]
                assert "type" in geometry
                assert "coordinates" in geometry
                assert isinstance(geometry["coordinates"], list)
                if len(geometry["coordinates"]) >= 4:
                    for coord in geometry["coordinates"]:
                        assert isinstance(coord, (int, float))
    
    # Edge case tests
    def test_get_gairmet_empty_parameters(self, api_client):
        """Test GET /api/data/gairmet with empty parameter values"""
        test_cases = [
            {"type": ""},
            {"format": ""},
            {"hazard": ""},
            {"date": ""}
        ]
        
        for params in test_cases:
            response = api_client.get("/api/data/gairmet", params=params)
            assert response.status_code in [200, 400]
    
    def test_get_gairmet_special_characters(self, api_client):
        """Test GET /api/data/gairmet with special characters in parameters"""
        special_cases = [
            {"type": "test@#$%"},
            {"hazard": "IFR&TURB"},
            {"date": "2023-12-20T00:00:00.000Z&test=1"}
        ]
        
        for params in special_cases:
            response = api_client.get("/api/data/gairmet", params=params)
            assert response.status_code in [200, 400]
    
    # Performance and reliability tests
    def test_gairmet_response_time(self, api_client):
        """Test that gairmet endpoint responds within reasonable time"""
        import time
        
        start_time = time.time()
        response = api_client.get("/api/data/gairmet")
        end_time = time.time()
        
        response_time = end_time - start_time
        assert response.status_code == 200
        assert response_time < 10  # Should respond within 10 seconds
    
    def test_gairmet_concurrent_requests(self, api_client):
        """Test multiple concurrent requests to gairmet endpoint"""
        import concurrent.futures
        
        def make_request():
            return api_client.get("/api/data/gairmet")
        
        with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
            futures = [executor.submit(make_request) for _ in range(5)]
            results = [future.result() for future in concurrent.futures.as_completed(futures)]
        
        for response in results:
            assert response.status_code in [200, 400, 429]  # 429 for rate limiting
    
    # Content negotiation tests
    def test_gairmet_accept_header_negotiation(self, api_client):
        """Test content negotiation using Accept header"""
        accept_headers = [
            "application/json",
            "application/geo+json", 
            "application/xml",
            "text/plain",
            "*/*"
        ]
        
        for accept_header in accept_headers:
            headers = {"Accept": accept_header}
            response = api_client.get("/api/data/gairmet", headers=headers)
            
            assert response.status_code == 200
            # Verify content type matches or is compatible with requested type
            content_type = response.headers.get('Content-Type', '')
            if accept_header != "*/*":
                assert accept_header in content_type or content_type.startswith('text/plain')

# Test configuration and utilities
@pytest.fixture(scope="session")
def test_config():
    """Load test configuration"""
    import yaml
    import os
    from pathlib import Path
    
    config_path = Path(__file__).parent / 'config.yml'
    with open(config_path, 'r') as file:
        config = yaml.safe_load(file)
    
    return config

def test_config_loading(test_config):
    """Test that configuration is properly loaded"""
    assert 'api' in test_config
    assert 'host' in test_config['api']
    assert test_config['api']['host'] is not None

if __name__ == "__main__":
    # Instructions for running tests
    print("To run these tests:")
    print("1. Set API_HOST environment variable")
    print("2. Run: pytest test_gairmet_api.py -v")
    print("3. For specific test: pytest test_gairmet_api.py::TestGairmetAPI::test_get_gairmet_success_default_params -v")
    print("4. For coverage: pytest test_gairmet_api.py --cov=.")
