# ********RoostGPT********

# Test generated by RoostGPT for test weatherTest using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
Feature: Astronomy API Tests

Background:
    * def baseURL = karate.properties['WEATHER_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = karate.properties['key']
    * configure headers = { 'Accept': 'application/json' }

Scenario Outline: Get astronomy data for valid location and date
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param q = '<location>'
    And param dt = '<date>'
    When method GET
    Then status 200
    And match response.location != null
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.astronomy != null
    And match response.astronomy.astro != null
    And match response.astronomy.astro.sunrise == '#string'
    And match response.astronomy.astro.sunset == '#string'
    And match response.astronomy.astro.moonrise == '#string'
    And match response.astronomy.astro.moonset == '#string'
    And match response.astronomy.astro.moon_phase == '#string'
    And match response.astronomy.astro.moon_illumination == '#string'

    Examples:
    | location   | date       |
    | London     | 2023-11-01 |
    | 10005      | 2023-11-01 |
    | 51.5,-0.12 | 2023-11-01 |

Scenario: Get astronomy data without location parameter
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param dt = '2023-11-01'
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == 'Parameter \'q\' not provided.'

Scenario: Get astronomy data without date parameter
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param q = 'London'
    When method GET
    Then status 400
    And match response.code == '#number'
    And match response.message == '#string'

Scenario: Get astronomy data with invalid location
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param q = 'InvalidLocation123'
    And param dt = '2023-11-01'
    When method GET
    Then status 400
    And match response.code == 1006
    And match response.message == '#string'

Scenario: Get astronomy data with invalid date format
    Given path '/v1/astronomy.json'
    And param key = authToken
    And param q = 'London'
    And param dt = '2023/11/01'
    When method GET
    Then status 400
    And match response.code == '#number'
    And match response.message == '#string'

Scenario: Get astronomy data with invalid API key
    Given path '/v1/astronomy.json'
    And param key = 'invalid_key'
    And param q = 'London'
    And param dt = '2023-11-01'
    When method GET
    Then status 401
    And match response.code == 2006
    And match response.message == '#string'

Scenario: Get astronomy data without API key
    Given path '/v1/astronomy.json'
    And param q = 'London'
    And param dt = '2023-11-01'
    When method GET
    Then status 401
    And match response.code == 1002
    And match response.message == 'API key not provided'
