# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-karate-circle-ci using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /insights/pages/{project-slug}/summary_get for http method type GET 
# RoostTestHash=d36b00fabb
# 
# 

# ********RoostGPT********
Feature: Test Summary Metrics and Trends for a Project via the /insights/pages/{project-slug}/summary endpoint

  Background:
    * def baseURL = karate.properties['CIRCLECI_API_BASE_URL'] || karate.properties['API_HOST_URL']
    * url baseURL

  Scenario Outline: Validate Get Summary Metrics and Trends for Project with API Key Auth
    Given path 'insights/pages/<projectSlug>/summary'
    And param reporting-window = <reportingWindow>
    And param branches = <branches>
    And param workflow-names = <workflowNames>
    * def authToken = karate.properties['Circle-Token']
    * configure headers =
      """
      {
        Circle-Token: '#(authToken)'
      }
      """
    When method GET
    Then status 200
    And match response.org_id == '##string'
    And match response.project_id == '##string'
    And match response.project_data.metrics.total_runs == '#number'
    And match response.project_data.metrics.total_duration_secs == '#number'
    And match response.project_data.metrics.total_credits_used == '#number'
    And match response.project_data.metrics.success_rate == '#number'
    And match response.project_data.metrics.throughput == '#number'
    And match response.project_data.trends.total_runs == '#number'
    And match response.project_data.trends.total_duration_secs == '#number'
    And match response.project_data.trends.total_credits_used == '#number'
    And match response.project_data.trends.success_rate == '#number'
    And match response.project_data.trends.throughput == '#number'
    And match response.project_workflow_data[*].workflow_name == '##string'
    And match response.project_workflow_data[*].metrics.total_credits_used == '#number'
    And match response.project_workflow_data[*].metrics.p95_duration_secs == '#number'
    And match response.project_workflow_data[*].metrics.total_runs == '#number'
    And match response.project_workflow_data[*].metrics.success_rate == '#number'
    And match response.project_workflow_data[*].trends.total_credits_used == '#number'
    And match response.project_workflow_data[*].trends.p95_duration_secs == '#number'
    And match response.project_workflow_data[*].trends.total_runs == '#number'
    And match response.project_workflow_data[*].trends.success_rate == '#number'
    And match response.project_workflow_branch_data[*].workflow_name == '##string'
    And match response.project_workflow_branch_data[*].branch == '##string'
    And match response.project_workflow_branch_data[*].metrics.total_credits_used == '#number'
    And match response.project_workflow_branch_data[*].metrics.p95_duration_secs == '#number'
    And match response.project_workflow_branch_data[*].metrics.total_runs == '#number'
    And match response.project_workflow_branch_data[*].metrics.success_rate == '#number'
    And match response.project_workflow_branch_data[*].trends.total_credits_used == '#number'
    And match response.project_workflow_branch_data[*].trends.p95_duration_secs == '#number'
    And match response.project_workflow_branch_data[*].trends.total_runs == '#number'
    And match response.project_workflow_branch_data[*].trends.success_rate == '#number'
    And match response.all_branches == '##array'
    And match response.all_workflows == '##array'

    Examples:
      | read('insights_pages_project-slug_summary_get.csv') |

  Scenario Outline: Validate Get Summary Metrics and Trends for Project with Basic Auth
    Given path 'insights/pages/<projectSlug>/summary'
    And param reporting-window = <reportingWindow>
    And param branches = <branches>
    And param workflow-names = <workflowNames>
    * def username = karate.properties['USER_NAME_AKSHAT']
    * def password = ''
    * def credentials = username + ':' + password
    * def encoded =
      """
      Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
      """
    * def authHeader = 'Basic ' + encoded
    * configure headers =
      """
      {
        Authorization: '#(authHeader)'
      }
      """
    When method GET
    Then status 200
    And match response.org_id == '##string'
    And match response.project_id == '##string'

    Examples:
      | read('insights_pages_project-slug_summary_get.csv') |

  Scenario Outline: Validate Default Error Response
    Given path 'insights/pages/<projectSlug>/summary'
    And param reporting-window = <reportingWindow>
    And param branches = <branches>
    * def authToken = karate.properties['Circle-Token']
    * configure headers =
      """
      {
        Circle-Token: '#(authToken)'
      }
      """
    When method GET
    Then status != 200
    And match response.message == '##string'

    Examples:
      | projectSlug                | reportingWindow | branches    |
      | 'invalid-slug'             | 'last-90-days'  | ['main']    |
      | 'gh/CircleCI-Public/other' | 'last-30-days'  | ['feature'] |
