# ********RoostGPT********

# Test generated by RoostGPT for test circle-ci-akshat-1 using AI Type Azure Open AI and AI Model Inference
# 
# Feature file generated for /me/collaborations_get for http method type GET 
# RoostTestHash=ff854080c5
# 
# 

# ********RoostGPT********
Feature: Collaborations API

  Background:
    * def baseURL = karate.properties['CIRCLECI_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Get Collaborations with API Key Authorization
    * def authToken = karate.properties['Circle-Token']
    * configure headers = { Circle-Token: '#(authToken)' }
    Given path '/me/collaborations'
    When method GET
    Then status 200
    And match response == '##array'
    And match each response[*].id == '##string'
    And match each response[*].vcs-type == '##string'
    And match each response[*].name == '##string'
    And match each response[*].avatar_url == '##string'
    And match each response[*].slug == '##string'

  Scenario Outline: Get Collaborations with Basic Authorization
    * def username = karate.properties['BASIC_USERNAME']
    * def password = karate.properties['BASIC_PASSWORD']
    * def credentials = username + ':' + password
    * def encoded = Java.type('java.util.Base64').getEncoder().encodeToString(credentials.getBytes())
    * def authHeader = 'Basic ' + encoded
    * configure headers = { Authorization: '#(authHeader)' }
    Given path '/me/collaborations'
    When method GET
    Then status 200
    And match response == '##array'
    And match each response[*].id == '##string'
    And match each response[*].vcs-type == '##string'
    And match each response[*].name == '##string'
    And match each response[*].avatar_url == '##string'
    And match each response[*].slug == '##string'

  Scenario Outline: Get Collaborations with Query Parameter Authorization
    * def authToken = karate.properties['circle-token']
    Given path '/me/collaborations'
    And param circle-token = authToken
    When method GET
    Then status 200
    And match response == '##array'
    And match each response[*].id == '##string'
    And match each response[*].vcs-type == '##string'
    And match each response[*].name == '##string'
    And match each response[*].avatar_url == '##string'
    And match each response[*].slug == '##string'

  Scenario: Get Collaborations with Invalid Authorization
    * configure headers = { Circle-Token: 'invalid_token' }
    Given path '/me/collaborations'
    When method GET
    Then status >= 400
    And match response == '##object'
    And match response.message == '##string'
