# ********RoostGPT********

# Test generated by RoostGPT for test karateTest using AI Type Claude AI and AI Model claude-3-5-sonnet-20241022
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=4940f5c55b
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Tests

Background:
* def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
* url baseURL
* configure headers = { 'Accept': 'application/json' }

Scenario Outline: Get Nobel Prizes with valid query parameters
Given path '/2.1/nobelPrizes'
And param offset = <offset>
And param limit = <limit>
And param sort = '<sort>'
And param nobelPrizeYear = <nobelPrizeYear>
And param yearTo = <yearTo>
And param nobelPrizeCategory = '<nobelPrizeCategory>'
When method GET
Then status 200
And match response.nobelPrizes == '#[]'
And match each response.nobelPrizes[*].awardYear == '#number'
And match each response.nobelPrizes[*].category == '#object'
And match each response.nobelPrizes[*].category.en == '##string'
And match each response.nobelPrizes[*].category.se == '##string'
And match each response.nobelPrizes[*].categoryFullName == '#object'
And match each response.nobelPrizes[*].dateAwarded == '##string'
And match each response.nobelPrizes[*].prizeAmount == '#number'
And match each response.nobelPrizes[*].prizeAmountAdjusted == '#number'
And match each response.nobelPrizes[*].topMotivation == '#object'
And match each response.nobelPrizes[*].laureates == '#[]'
And match each response.nobelPrizes[*].laureates[*].id == '#number'
And match each response.nobelPrizes[*].laureates[*].portion == '#? _ == "1" || _ == "1/2" || _ == "1/3" || _ == "1/4"'
And match each response.nobelPrizes[*].laureates[*].sortOrder == '#? _ == "1" || _ == "2" || _ == "3"'
And match response.meta.offset == <offset>
And match response.meta.limit == <limit>
And match response.meta.nobelPrizeYear == <nobelPrizeYear>
And match response.meta.yearTo == <yearTo>
And match response.meta.nobelPrizeCategory == '<nobelPrizeCategory>'
And match response.meta.count == '#number'
And match response.links == '#[]'

Examples:
| offset | limit | sort   | nobelPrizeYear | yearTo | nobelPrizeCategory |
| 0      | 10    | 'asc'  | 1901          | 1910   | 'che'             |
| 10     | 20    | 'desc' | 1950          | 1960   | 'eco'             |
| 20     | 30    | 'asc'  | 2000          | 2010   | 'lit'             |

Scenario: Get Nobel Prizes without query parameters
Given path '/2.1/nobelPrizes'
When method GET
Then status 200
And match response.nobelPrizes == '#[]'
And match response.meta == '#object'
And match response.links == '#[]'

Scenario Outline: Get Nobel Prizes with invalid parameters - Bad Request
Given path '/2.1/nobelPrizes'
And param <param> = <value>
When method GET
Then status 400
And match response.code == '#string'
And match response.message == '#string'

Examples:
| param            | value  |
| offset           | -1     |
| limit            | 0      |
| sort             | 'invalid' |
| nobelPrizeYear   | 1900   |

Scenario: Get Nobel Prizes with non-existent year - Not Found
Given path '/2.1/nobelPrizes'
And param nobelPrizeYear = 2999
When method GET
Then status 404
And match response.code == '#string'
And match response.message == '#string'

Scenario: Get Nobel Prizes with invalid parameter combination - Unprocessable Entity
Given path '/2.1/nobelPrizes'
And param yearTo = 1901
When method GET
Then status 422
And match response.code == '#string'
And match response.message == '#string'
