# ********RoostGPT********

# Test generated by RoostGPT for test api-testing-karate-circle-ci using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /context/{context-id}/environment-variable_get for http method type GET 
# RoostTestHash=cbf5028a22
# 
# 

# ********RoostGPT********
Feature: List environment variables from a context
  This feature tests the GET /context/{context-id}/environment-variable endpoint for retrieving environment variable details from a context.

  Background:
    * def urlBase = karate.properties['API_HOST_URL']
    * url urlBase

  Scenario Outline: Verify successful retrieval of environment variables with valid context ID
    Given path 'context/<context-id>/environment-variable'
    And param 'page-token' = <page-token>
    When method GET
    Then status 200
    And match response.items == '#[]'
    And match response.items[0].variable == '#string'
    And match response.items[0].created_at == '#string'
    And match response.items[0].updated_at == '#string'
    And match response.items[0].context_id == '#uuid'
    And match response.items[*].variable contains 'POSTGRES_USER'
    And match response.next_page_token == '#string?'

    Examples:
      | read('context_context-id_environment-variable_get.csv') |

  Scenario: Verify error response with invalid context ID
    Given path 'context/invalid-context-id/environment-variable'
    When method GET
    Then status 404
    And match response.message == '#string'

  Scenario Outline: Verify error response for invalid page-token query parameter
    Given path 'context/<context-id>/environment-variable'
    And param 'page-token' = <page-token>
    When method GET
    Then status <status>
    And match response.message == '#string'

    Examples:
      | context-id                           | page-token         | status |
      | 123e4567-e89b-12d3-a456-426614174000 | INVALID_PAGE_TOKEN |    400 |
      | 123e4567-e89b-12d3-a456-426614174000 |                    |    400 |

  Scenario: Verify the presence of mandatory response headers
    Given path 'context/123e4567-e89b-12d3-a456-426614174000/environment-variable'
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['Date'] == '#string'
