# ********RoostGPT********

# Test generated by RoostGPT for test karateCircleCIFile using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219
# 
# Feature file generated for /organization/{org-slug-or-id}/url-orb-allow-list/{allow-list-entry-id}_delete for http method type DELETE 
# RoostTestHash=c8868eae41
# 
# 

# ********RoostGPT********
Feature: Remove an entry from the org's URL orb allow-list

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * def tokenAuth = call read('classpath:helpers/token-auth.js')
    * configure headers = tokenAuth

  Scenario: Successfully remove a URL orb allow-list entry
    Given url urlBase
    And path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list', 'ba98990a-5a00-4cad-b55e-b44117b92e0c'
    When method DELETE
    Then status 200
    And match response == { id: '#string', message: '#string' }
    And match response.id == '#notnull'
    And match response.message == '#notnull'
    And match response.id == 'ba98990a-5a00-4cad-b55e-b44117b92e0c'

  Scenario Outline: Successfully remove a URL orb allow-list entry with different org identifiers
    Given url urlBase
    And path 'organization', '<org-slug-or-id>', 'url-orb-allow-list', '<allow-list-entry-id>'
    When method DELETE
    Then status 200
    And match response == { id: '#string', message: '#string' }
    And match response.id == '#notnull'
    And match response.message == '#notnull'
    And match response.id == '<allow-list-entry-id>'

    Examples:
      | read('organization_org-slug-or-id_url-orb-allow-list_allow-list-entry-id_delete.csv') |

  Scenario: Attempt to remove a non-existent URL orb allow-list entry
    Given url urlBase
    And path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list', 'non-existent-id'
    When method DELETE
    Then status 404
    And match response == { message: '#string' }
    And match response.message contains 'not found'

  Scenario: Attempt to remove a URL orb allow-list entry with invalid org
    Given url urlBase
    And path 'organization', 'invalid-org', 'url-orb-allow-list', 'ba98990a-5a00-4cad-b55e-b44117b92e0c'
    When method DELETE
    Then status 404
    And match response == { message: '#string' }
    And match response.message contains 'not found'

  Scenario: Attempt to remove a URL orb allow-list entry without authentication
    Given url urlBase
    And path 'organization', 'gh/CircleCI-Public', 'url-orb-allow-list', 'ba98990a-5a00-4cad-b55e-b44117b92e0c'
    And configure headers = null
    When method DELETE
    Then status 401
    And match response == { message: '#string' }
    And match response.message contains 'unauthorized'
