# ********RoostGPT********

# Test generated by RoostGPT for test karateCircleCIFile using AI Type Claude AI and AI Model claude-3-7-sonnet-20250219
# 
# Feature file generated for /pipeline/{pipeline-id}/config_get for http method type GET 
# RoostTestHash=1b2cb0abc0
# 
# 

# ********RoostGPT********
Feature: Pipeline Configuration API

  Background:
    * def urlBase = karate.properties['API_HOST_URL']
    * def pipelineId = '5034460f-c7c4-4c43-9457-de07e2029e7b'
    * def authHeader = { Authorization: 'Basic REPLACE_BASIC_AUTH' }

  Scenario: Get a pipeline's configuration successfully
    Given url urlBase
    And path '/pipeline', pipelineId, 'config'
    And headers authHeader
    When method GET
    Then status 200
    And match response == '#object'
    And match response.source == '#string'
    And match response.compiled == '#string'
    And match response['setup-config'] == '##string'
    And match response['compiled-setup-config'] == '##string'
    And match response contains { source: '#string', compiled: '#string' }
    And match response.source != null
    And match response.compiled != null

  Scenario: Get a pipeline's configuration with invalid pipeline ID
    Given url urlBase
    And path '/pipeline', 'invalid-uuid', 'config'
    And headers authHeader
    When method GET
    Then status 400
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Get a pipeline's configuration with non-existent pipeline ID
    Given url urlBase
    And path '/pipeline', '00000000-0000-0000-0000-000000000000', 'config'
    And headers authHeader
    When method GET
    Then status 404
    And match response == '#object'
    And match response.message == '#string'

  Scenario: Get a pipeline's configuration without authentication
    Given url urlBase
    And path '/pipeline', pipelineId, 'config'
    When method GET
    Then status 401
    And match response == '#object'
    And match response.message == '#string'

  Scenario Outline: Get pipeline configurations with different pipeline IDs
    Given url urlBase
    And path '/pipeline', '<pipelineId>', 'config'
    And headers authHeader
    When method GET
    Then status 200
    And match response == '#object'
    And match response.source == '#string'
    And match response.compiled == '#string'
    And match response contains { source: '#string', compiled: '#string' }
    And match response.source != null
    And match response.compiled != null

    Examples:
      | read('pipeline_pipeline-id_config_get.csv') |
