{
    "swagger": "2.0",
    "x-explorer-enabled": false,
    "info": {
        "title": "vidaoo API",
        "description": "VIDAOO provides the best Unified Meeting Experience platform that brings HD video conferencing, mobility and web meetings together as a cloud service.",
        "contact": {
            "name": "Vidaoo Customer Support",
            "url": "https://xcally.atlassian.net/servicedesk/customer/portal/4"
        },
        "x-logo": {
            "url": "./logo.png",
            "altText": "Vidaoo Logo"
        },
        "license": {
            "name": "EULA",
            "url": "https://vidaoo.xcally.com/"
        },
        "version": "2.13.0"
    },
    "host": "api-vidaoo.xcally.com",
    "schemes": [
        "https"
    ],
    "paths": {
        "/api/v1​​​​​​​​/accounts​​​​​​​​/:id/recording​​​​​​​​": {
            "put": {
                "summary": "Update recording config",
                "description": "Update recording config",
                "operationId": "v1.accounts.updateRecording",
                "tags": [
                    "Accounts"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$account"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/change-password​​​​​​​​": {
            "put": {
                "summary": "Change account's password",
                "description": "Change account's password",
                "operationId": "v1.accounts.changePassword",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/checkout-session​​​​​​​​": {
            "post": {
                "summary": "Create a checkout session",
                "description": "Stripe hosted payment page. It is possible to pay for one-time purchase subscription to Vidaoo",
                "operationId": "v1.accounts.stripeCreateCheckoutSession",
                "tags": [
                    "Accounts"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$account",
                            "$checkout"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/customer-portal​​​​​​​​": {
            "post": {
                "summary": "Get customer portal URL",
                "description": "The customer portal is a Stripe-hosted UI for subscription and billing management.",
                "operationId": "v1.accounts.stripeGetCustomerPortal",
                "tags": [
                    "Accounts"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$account"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/forgot-password​​​​​​​​": {
            "get": {
                "summary": "Forgot account's password",
                "description": "Forgot account's password",
                "operationId": "v1.accounts.forgotPassword",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.accounts.health",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/login​​​​​​​​": {
            "post": {
                "summary": "Retrieve a account's token",
                "description": "Retrieve a account's token",
                "operationId": "v1.accounts.login",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/me​​​​​​​​": {
            "get": {
                "summary": "Own account's details",
                "description": "Own account's details",
                "operationId": "v1.accounts.me",
                "tags": [
                    "Accounts"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$account"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/register​​​​​​​​": {
            "post": {
                "summary": "Register an account",
                "description": "Register an account",
                "operationId": "v1.accounts.register",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/reset-password​​​​​​​​": {
            "post": {
                "summary": "Reset account's password",
                "description": "Reset account's password",
                "operationId": "v1.accounts.resetPassword",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/accounts​​​​​​​​/verify​​​​​​​​": {
            "post": {
                "summary": "Verify an account's token",
                "description": "Verify an account's token",
                "operationId": "v1.accounts.verify",
                "tags": [
                    "Accounts"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/automations​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a automation",
                "description": "Retrieve a automations details",
                "operationId": "v1.automations.get",
                "tags": [
                    "Automations"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "automations.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update an automation",
                "description": "Update an automation",
                "operationId": "v1.automations.update",
                "tags": [
                    "Automations"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "automations.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Remove an automation",
                "description": "Remove an automation",
                "operationId": "v1.automations.remove",
                "tags": [
                    "Automations"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "automations.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/automations​​​​​​​​/events​​​​​​​​": {
            "get": {
                "summary": "List of events",
                "description": "List of events",
                "operationId": "v1.automations.listEvents",
                "tags": [
                    "Automations"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/automations​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.automations.health",
                "tags": [
                    "Automations"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/automations​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List of automations",
                "description": "List of automations",
                "operationId": "v1.automations.list",
                "tags": [
                    "Automations"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "automations.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create an automation",
                "description": "Create an automation",
                "operationId": "v1.automations.create",
                "tags": [
                    "Automations"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "automations.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/backgrounds​​​​​​​​/:id/download​​​​​​​​": {
            "get": {
                "summary": "Download a background",
                "description": "Generate a signed URL to download the background",
                "operationId": "v1.backgrounds.download",
                "tags": [
                    "Backgrounds"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/backgrounds​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a background",
                "description": "Retrieve background's details",
                "operationId": "v1.backgrounds.get",
                "tags": [
                    "Backgrounds"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "backgrounds.get"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a background",
                "description": "Delete a background",
                "operationId": "v1.backgrounds.remove",
                "tags": [
                    "Backgrounds"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "backgrounds.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/backgrounds​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List backgrounds",
                "description": "List backgrounds",
                "operationId": "v1.backgrounds.list",
                "tags": [
                    "Backgrounds"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/buttons​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a button",
                "description": "Retrieve a button's details",
                "operationId": "v1.buttons.get",
                "tags": [
                    "Buttons"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "buttons.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update a button",
                "description": "Update a button",
                "operationId": "v1.buttons.update",
                "tags": [
                    "Buttons"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "buttons.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a button",
                "description": "Delete a button",
                "operationId": "v1.buttons.remove",
                "tags": [
                    "Buttons"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "buttons.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/buttons​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.buttons.health",
                "tags": [
                    "Buttons"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/buttons​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List of buttons",
                "description": "List of buttons",
                "operationId": "v1.buttons.list",
                "tags": [
                    "Buttons"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "buttons.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a button",
                "description": "Create a custom button",
                "operationId": "v1.buttons.create",
                "tags": [
                    "Buttons"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "buttons.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/devices​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a device",
                "description": "Retrieve a device's details",
                "operationId": "v1.devices.get",
                "tags": [
                    "Devices"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "devices.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update a device",
                "description": "Update a device",
                "operationId": "v1.devices.update",
                "tags": [
                    "Devices"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "devices.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a device",
                "description": "Delete a device",
                "operationId": "v1.devices.remove",
                "tags": [
                    "Devices"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "devices.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/devices​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.devices.health",
                "tags": [
                    "Devices"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/devices​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List devices",
                "description": "List devices",
                "operationId": "v1.devices.list",
                "tags": [
                    "Devices"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "devices.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a device",
                "description": "Create a device",
                "operationId": "v1.devices.create",
                "tags": [
                    "Devices"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "devices.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/extmessages​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.extmessages.health",
                "tags": [
                    "Extmessages"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/logs​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a log",
                "description": "Retrieve a logs details",
                "operationId": "v1.logs.get",
                "tags": [
                    "Logs"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "logs.get"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/logs​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.logs.health",
                "tags": [
                    "Logs"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/logs​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List of logs",
                "description": "List of logs",
                "operationId": "v1.logs.list",
                "tags": [
                    "Logs"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "logs.list"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/:id/close​​​​​​​​": {
            "post": {
                "summary": "Close meeting",
                "description": "Close meeting",
                "operationId": "v1.meetings.close",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.close"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/:id/feedback​​​​​​​​": {
            "post": {
                "summary": "Give a feedback on meeting",
                "description": "Give a feedback on meeting",
                "operationId": "v1.meetings.feedback",
                "tags": [
                    "Meetings"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a meeting",
                "description": "Retrieve a meeting's details",
                "operationId": "v1.meetings.get",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update a meeting",
                "description": "Update a meeting",
                "operationId": "v1.meetings.update",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a meeting",
                "description": "Delete a meeting",
                "operationId": "v1.meetings.remove",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.meetings.health",
                "tags": [
                    "Meetings"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/reports/:id/download​​​​​​​​": {
            "get": {
                "summary": "Download a report of meetings",
                "description": "Generate a signed URL with which download the report of meetings",
                "operationId": "v1.meetings.reports.download",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.reports.download"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/reports/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a report of meetings",
                "description": "Retrieve a report's details",
                "operationId": "v1.meetings.reports.get",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.reports.get"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a report of meetings",
                "description": "Delete a report",
                "operationId": "v1.meetings.reports.remove",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.reports.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​/reports​​​​​​​​": {
            "post": {
                "summary": "Create a report of meetings",
                "description": "Create a report of meetings",
                "operationId": "v1.meetings.reports.create",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.reports.create"
                        ]
                    }
                ]
            },
            "get": {
                "summary": "List of reports of meetings",
                "description": "List of reports of meetings",
                "operationId": "v1.meetings.reports.list",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.reports.list"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/meetings​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List meetings",
                "description": "List live meetings or past meetings",
                "operationId": "v1.meetings.list",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a meeting",
                "description": "Create a meeting",
                "operationId": "v1.meetings.create",
                "tags": [
                    "Meetings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "meetings.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/plans​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.plans.health",
                "tags": [
                    "Plans"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/plans​​​​​​​​/me​​​​​​​​": {
            "get": {
                "summary": "Own plan's details",
                "description": "Own plan's details",
                "operationId": "v1.plans.me",
                "tags": [
                    "Plans"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$account"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/plans​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List plans",
                "description": "List plans",
                "operationId": "v1.plans.list",
                "tags": [
                    "Plans"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$account"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/recordings​​​​​​​​/:id/download​​​​​​​​": {
            "get": {
                "summary": "Download a recording",
                "description": "Generate a signed URL to download the recording",
                "operationId": "v1.recordings.download",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.get"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/recordings​​​​​​​​/:id/stop​​​​​​​​": {
            "post": {
                "summary": "Stop a recording",
                "description": "Stop a recording",
                "operationId": "v1.recordings.stop",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/recordings​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a recording",
                "description": "Retrieve a recording's details",
                "operationId": "v1.recordings.get",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update a recording",
                "description": "Update a recording",
                "operationId": "v1.recordings.update",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a recording",
                "description": "Delete a recording",
                "operationId": "v1.recordings.remove",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/recordings​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.recordings.health",
                "tags": [
                    "Recordings"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/recordings​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List recordings",
                "description": "List recordings",
                "operationId": "v1.recordings.list",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Start a recording",
                "description": "Start a recording",
                "operationId": "v1.recordings.create",
                "tags": [
                    "Recordings"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "recordings.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/reports​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.reports.health",
                "tags": [
                    "Reports"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/roles​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a role",
                "description": "Retrieve a role's details",
                "operationId": "v1.roles.get",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "roles.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update a role",
                "description": "Update a role",
                "operationId": "v1.roles.update",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "roles.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a role",
                "description": "Delete a role",
                "operationId": "v1.roles.remove",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "roles.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/roles​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.roles.health",
                "tags": [
                    "Roles"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/roles​​​​​​​​/permissions​​​​​​​​": {
            "get": {
                "summary": "List of permissions",
                "description": "List of permissions",
                "operationId": "v1.roles.listPermissions",
                "tags": [
                    "Roles"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/roles​​​​​​​​​​​​​​​​": {
            "get": {
                "operationId": "v1.roles.list",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "roles.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a role",
                "description": "Create a role",
                "list": {
                    "summary": "List of roles",
                    "description": "List of roles"
                },
                "operationId": "v1.roles.create",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "roles.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/sessions​​​​​​​​/:id/close​​​​​​​​": {
            "post": {
                "summary": "Close own session",
                "description": "Close own session",
                "operationId": "v1.sessions.close",
                "tags": [
                    "Sessions"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "sessions.close"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/sessions​​​​​​​​/:id/owner​​​​​​​​": {
            "put": {
                "summary": "Update a session's owner",
                "description": "Update a session's owner",
                "operationId": "v1.sessions.updateOwner",
                "tags": [
                    "Sessions"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "sessions.update"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/sessions​​​​​​​​/:id/token​​​​​​​​": {
            "get": {
                "summary": "Retrieve a session's token",
                "description": "Retrieve a session's token",
                "operationId": "v1.sessions.token",
                "tags": [
                    "Sessions"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/sessions​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a session",
                "description": "Retrieve a session's details",
                "operationId": "v1.sessions.get",
                "tags": [
                    "Sessions"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "sessions.get"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/sessions​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.sessions.health",
                "tags": [
                    "Sessions"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/sessions​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List sessions",
                "description": "List live sessions or past sessions",
                "operationId": "v1.sessions.list",
                "tags": [
                    "Sessions"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "sessions.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a session",
                "description": "Create a session for a device",
                "operationId": "v1.sessions.create",
                "tags": [
                    "Sessions"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "sessions.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/tickets​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a ticket",
                "description": "Retrieve a ticket's details",
                "operationId": "v1.tickets.get",
                "tags": [
                    "Tickets"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tickets.get"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a ticket",
                "description": "Delete a ticket",
                "operationId": "v1.tickets.remove",
                "tags": [
                    "Tickets"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tickets.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/tickets​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.tickets.health",
                "tags": [
                    "Tickets"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/tickets​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List tickets",
                "description": "List tickets",
                "operationId": "v1.tickets.list",
                "tags": [
                    "Tickets"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tickets.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a ticket",
                "description": "Create a ticket",
                "operationId": "v1.tickets.create",
                "tags": [
                    "Tickets"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tickets.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/tokens​​​​​​​​/:id​​​​​​​​": {
            "delete": {
                "summary": "Delete a token",
                "description": "Delete a token",
                "operationId": "v1.tokens.remove",
                "tags": [
                    "Tokens"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tokens.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/tokens​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.tokens.health",
                "tags": [
                    "Tokens"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/tokens​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List of tokens",
                "description": "List of tokens",
                "operationId": "v1.tokens.list",
                "tags": [
                    "Tokens"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tokens.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a token",
                "description": "Create a custom token",
                "operationId": "v1.tokens.create",
                "tags": [
                    "Tokens"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "tokens.create"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​/:id/reset-password​​​​​​​​": {
            "post": {
                "summary": "Reset user's password",
                "description": "Reset user's password",
                "operationId": "v1.users.resetPassword",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "users.update"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​/:id​​​​​​​​": {
            "get": {
                "summary": "Retrieve a user",
                "description": "Retrieve a user's details",
                "operationId": "v1.users.get",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "users.get"
                        ]
                    }
                ]
            },
            "put": {
                "summary": "Update a user",
                "description": "Update a user",
                "operationId": "v1.users.update",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "users.update"
                        ]
                    }
                ]
            },
            "delete": {
                "summary": "Delete a user",
                "description": "Delete a user",
                "operationId": "v1.users.remove",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "users.remove"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​/change-password​​​​​​​​": {
            "put": {
                "summary": "Change user's password",
                "description": "Change user's password",
                "operationId": "v1.users.changePassword",
                "tags": [
                    "Users"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​/health​​​​​​​​": {
            "get": {
                "summary": "Health check API endpoint",
                "description": "Health check API endpoint",
                "operationId": "v1.users.health",
                "tags": [
                    "Users"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​/login​​​​​​​​": {
            "post": {
                "summary": "Retrieve a user's token",
                "description": "Retrieve a user's token",
                "operationId": "v1.users.login",
                "tags": [
                    "Users"
                ],
                "security": []
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​/me​​​​​​​​": {
            "get": {
                "summary": "Own user's details",
                "description": "Own user's details",
                "operationId": "v1.users.me",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "$user"
                        ]
                    }
                ]
            }
        },
        "/api/v1​​​​​​​​/users​​​​​​​​​​​​​​​​": {
            "get": {
                "summary": "List users",
                "description": "List users",
                "operationId": "v1.users.list",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "users.list"
                        ]
                    }
                ]
            },
            "post": {
                "summary": "Create a user",
                "description": "Create a user",
                "operationId": "v1.users.create",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": [
                            "users.create"
                        ]
                    }
                ]
            }
        },
        "/upload/v1​​​​​​​​/backgrounds​​​​​​​​/v1/backgrounds​​​​​​​​": {
            "post": {
                "basePath": "/upload/v1",
                "summary": "Upload background image",
                "description": "Upload background image",
                "operationId": "v1.backgrounds.upload",
                "tags": [
                    "Backgrounds"
                ],
                "security": []
            }
        }
    },
    "securityDefinitions": {
        "bearerAuth": {
            "description": "<p>For accessing the API a valid JWT token must be passed in all the queries in the 'Authorization' header.<p>                                <p>The following syntax must be used in the '<b>Authorization</b>' header:</p>                                <p><code>Bearer xxxxxx.yyyyyyy.zzzzzz</code></p>",
            "type": "http",
            "scheme": "bearer"
        },
        "apiKey": {
            "description": "<p>For accessing the API a valid KEY must be passed in all the queries in the 'X-APIKEY' header.<p>                                <p>The following syntax must be used in the '<b>X-APIKEY</b>' header:</p>                                <p><code>b2904ce8b97f4b736a435e71ff552f71dfd37f5597ec0f598e</code></p>",
            "type": "apiKey",
            "name": "X-APIKEY",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "Recordings",
            "description": "Recordings operations"
        }
    ]
}