# ********RoostGPT********

# Test generated by RoostGPT for test karate-pet using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /store/inventory_get for http method type GET 
# RoostTestHash=a66f7079af
# 
# 

# ********RoostGPT********
Feature: Store Inventory API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: karate.properties['AUTH_TOKEN'] }

  Scenario: Get Inventory - Successful Operation
    Given path 'v2/store/inventory'
    When method GET
    Then status 200
    And match response == '#object'
    And match each response[*] == '#number'

  Scenario Outline: Get Inventory - Invalid HTTP Method
    Given path 'v2/store/inventory'
    When method <httpMethod>
    Then status 405

    Examples:
      | httpMethod |
      | POST       |
      | PUT        |
      | DELETE     |
