# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /pet_post for http method type POST 
# RoostTestHash=68c053e0a8
# 
# 

# ********RoostGPT********
"""
This module contains pytest test cases for testing the Petstore API.
The tests are based on the provided OpenAPI specification and use pytest fixtures
defined in conftest.py for configuration and API client management.

Instructions for running the tests:
- Ensure pytest and required dependencies are installed.
- Execute `pytest` in the command line from the directory containing this file.
"""

import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load the OpenAPI spec for validation
api_spec_path = 'api.json'
swagger_validator = SwaggerSchemaValidator(api_spec_path)

# Load test data from JSON file
TEST_DATA_FILENAME = 'pet.json'
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME

def _load_json_file(filepath):
    with open(filepath, 'r') as file:
        return json.load(file)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case['scenario'] for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_add_pet(api_client, config_test_data, scenario_case):
    """
    Test the /pet endpoint for adding a new pet to the store.
    """

    # Prepare the request payload
    payload = {
        'name': scenario_case.get('name', config_test_data['petId']),
        'photoUrls': scenario_case.get('photoUrls', []),
    }

    if 'id' in scenario_case:
        payload['id'] = scenario_case['id']
    if 'category' in scenario_case:
        payload['category'] = scenario_case['category']
    if 'tags' in scenario_case:
        payload['tags'] = scenario_case['tags']
    if 'status' in scenario_case:
        payload['status'] = scenario_case['status']

    # Perform the API request
    response = api_client.post('/pet', json=payload)

    # Validate response status code
    assert response.status_code == scenario_case['statusCode'], f"Expected status code {scenario_case['statusCode']}, got {response.status_code}"

    # Validate response schema
    schema_validation = swagger_validator.validate_schema_by_response('/pet', 'post', str(scenario_case['statusCode']), response)
    assert schema_validation['valid'], f"Schema validation failed: {schema_validation.get('message')}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_add_pet_invalid_auth(api_client, scenario_case):
    """
    Test the /pet endpoint with invalid authentication.
    """

    # Prepare the request payload
    payload = {
        'name': scenario_case.get('name', 'default_name'),
        'photoUrls': scenario_case.get('photoUrls', []),
    }

    # Perform the API request with invalid auth
    response = api_client.post('/pet', json=payload, headers={'Authorization': 'Bearer invalid_token'})

    # Validate response status code for unauthorized access
    assert response.status_code == 401, f"Expected status code 401, got {response.status_code}"
