# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /pet_post for http method type POST 
# RoostTestHash=68c053e0a8
# 
# 

# ********RoostGPT********
import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Load JSON test data
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / 'pet.json'
with open(_endpoint_data_path, 'r') as f:
    _ENDPOINT_DATA = json.load(f)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"Scenario: {case['scenario']}" for case in _ENDPOINT_DATA]

# Swagger Schema Validator
swagger_validator = SwaggerSchemaValidator("api.json")

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_add_pet(api_client, api_host, petstore_auth, config_test_data, scenario_case):
    """
    Test for adding a new pet to the store.
    """

    # Prepare request data
    request_data = {
        "name": scenario_case.get("name"),
        "photoUrls": scenario_case.get("photoUrls"),
    }
    if "id" in scenario_case:
        request_data["id"] = scenario_case["id"]
    if "category" in scenario_case:
        request_data["category"] = scenario_case["category"]
    if "tags" in scenario_case:
        request_data["tags"] = scenario_case["tags"]
    if "status" in scenario_case:
        request_data["status"] = scenario_case["status"]

    # Validate request data
    validation_result = swagger_validator.validate_json(request_data, "Pet")
    assert validation_result['valid'], f"Request validation error: {validation_result.get('message')}"

    # Make API request
    response = api_client.post("/pet", data=request_data)

    # Validate response status code
    expected_status_code = scenario_case["statusCode"]
    assert response.status_code == expected_status_code, f"Unexpected status code: {response.status_code}"

    # Validate response schema
    response_validation = swagger_validator.validate_schema_by_response(
        endpoint="/pet", method="POST", status_code=str(response.status_code), response=response
    )
    assert response_validation['valid'], f"Response validation error: {response_validation.get('message')}"

# Instructions for running the tests
"""
To execute the tests, ensure you have pytest installed and run the following command in the terminal:
pytest <test_file_name>.py
"""
