# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
"""
Test Suite for Pet API using pytest and OpenAPI specification

This module contains tests for the Pet API defined by the OpenAPI specification.
The tests are designed to cover various scenarios including successful requests,
authentication, edge cases, and error responses.

Instructions for running the tests:
- Ensure pytest is installed in your environment.
- Place this file in the test directory alongside `conftest.py`.
- Run the tests using the command: pytest <this_file_name>.py

Dependencies:
- pytest
- requests
- yaml
- jsonschema

Ensure the required environment variables are set for configuration.
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Constants
TEST_DATA_FILENAME = "pet_petId.json"
SPEC_FILE = "api.json"

# Load test data
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME

def _load_json_file(filepath):
    with open(filepath, 'r') as f:
        return json.load(f)

# Load endpoint test data
_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [str(case['scenario']) for case in _ENDPOINT_DATA]

# Initialize SwaggerSchemaValidator
swagger_validator = SwaggerSchemaValidator(SPEC_FILE)

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pet_by_id(api_client, host, api_key, petstore_auth, scenario_case):
    """
    Test GET /pet/{petId} endpoint with various scenarios.
    """
    pet_id = scenario_case['petId']
    expected_status_code = scenario_case['statusCode']
    endpoint = f"/pet/{pet_id}"

    # Prepare headers
    headers = {
        'Authorization': f'Bearer {petstore_auth}',
        'api_key': api_key
    }

    # Validate request schema
    request_params = {'petId': pet_id}
    swagger_validator.validate_json(request_params, 'PetIdParameter')

    # Make API request
    response = api_client.get(endpoint, headers=headers)

    # Validate response status code
    assert response.status_code == expected_status_code, (
        f"Expected status code {expected_status_code}, got {response.status_code}"
    )

    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(
        endpoint, 'GET', str(response.status_code), response
    )
    assert validation_result['valid'], validation_result.get('message', 'Schema validation failed')

    # Additional assertions based on expected status code
    if expected_status_code == 200:
        data = response.json()
        assert 'name' in data, "Response JSON should contain 'name'"
        assert 'photoUrls' in data, "Response JSON should contain 'photoUrls'"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pet_by_id_invalid_auth(api_client, host, scenario_case):
    """
    Test GET /pet/{petId} endpoint with invalid authentication.
    """
    pet_id = scenario_case['petId']
    endpoint = f"/pet/{pet_id}"

    # Prepare headers with invalid auth
    headers = {
        'Authorization': 'Bearer invalid_token',
        'api_key': 'invalid_key'
    }

    # Make API request
    response = api_client.get(endpoint, headers=headers)

    # Validate response status code
    assert response.status_code == 401, (
        f"Expected status code 401, got {response.status_code}"
    )

    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(
        endpoint, 'GET', str(response.status_code), response
    )
    assert validation_result['valid'], validation_result.get('message', 'Schema validation failed')

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pet_by_id_missing_auth(api_client, host, scenario_case):
    """
    Test GET /pet/{petId} endpoint with missing authentication.
    """
    pet_id = scenario_case['petId']
    endpoint = f"/pet/{pet_id}"

    # Make API request without auth headers
    response = api_client.get(endpoint)

    # Validate response status code
    assert response.status_code == 401, (
        f"Expected status code 401, got {response.status_code}"
    )

    # Validate response schema
    validation_result = swagger_validator.validate_schema_by_response(
        endpoint, 'GET', str(response.status_code), response
    )
    assert validation_result['valid'], validation_result.get('message', 'Schema validation failed')
