# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/findByTags_get for http method type GET 
# RoostTestHash=7439f031be
# 
# 

# ********RoostGPT********
"""
Module for testing the /pet/findByTags API endpoint using pytest.
Ensure the following:
- conftest.py is set up correctly with necessary fixtures.
- validator.py is available for request and response validation.
- pet_findByTags.json is present in the same directory for test data.

Instructions for running the tests:
1. Install pytest: pip install pytest
2. Run tests: pytest <test_file_name>.py
"""

import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Constants
TEST_DATA_FILENAME = "pet_findByTags.json"
API_SPEC_PATH = "api.json"  # Path to the OpenAPI spec

# Load endpoint test data
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME

def _load_json_file(file_path):
    with open(file_path, 'r') as file:
        return json.load(file)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [case["scenario"] for case in _ENDPOINT_DATA]

# Initialize SwaggerSchemaValidator
validator = SwaggerSchemaValidator(API_SPEC_PATH)

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_find_pets_by_tags(api_client, petstore_auth, scenario_case):
    """
    Test the /pet/findByTags endpoint for various scenarios.
    """
    endpoint = "/pet/findByTags"
    headers = {"Authorization": f"Bearer {petstore_auth}"}
    params = {"tags": [tag["name"] for tag in scenario_case.get("tags", [])]}
    
    # Validate request before sending
    request_validation = validator.validate_json({"tags": params["tags"]}, "findPetsByTags")
    assert request_validation["valid"], f"Request validation failed: {request_validation.get('message')}"
    
    response = api_client.get(endpoint, headers=headers, params=params)
    
    # Assert status code
    expected_status_code = scenario_case["statusCode"]
    assert response.status_code == expected_status_code, f"Expected {expected_status_code}, got {response.status_code}"
    
    # Validate response schema
    response_validation = validator.validate_schema_by_response(endpoint, "GET", str(expected_status_code), response)
    assert response_validation["valid"], f"Response validation failed: {response_validation.get('message')}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_find_pets_by_tags_invalid_auth(api_client, scenario_case):
    """
    Test the /pet/findByTags endpoint with invalid authentication.
    """
    endpoint = "/pet/findByTags"
    headers = {"Authorization": "Bearer invalid_token"}
    params = {"tags": [tag["name"] for tag in scenario_case.get("tags", [])]}
    
    response = api_client.get(endpoint, headers=headers, params=params)
    
    # Assert status code
    assert response.status_code == 401, f"Expected 401 Unauthorized, got {response.status_code}"
    
    # Validate response schema
    response_validation = validator.validate_schema_by_response(endpoint, "GET", "default", response)
    assert response_validation["valid"], f"Response validation failed: {response_validation.get('message')}"
