# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /pet/{petId}_get for http method type GET 
# RoostTestHash=bc8f34e70c
# 
# 

# ********RoostGPT********
"""
Test suite for the /pet/{petId} endpoint of the Petstore API.

Setup:
- Ensure `conftest.py` and `validator.py` are in the same directory.
- Update `config.yml` with valid API host and authentication details.

Instructions:
- Run the tests using pytest.

Expected output:
- Tests will validate various scenarios for the /pet/{petId} endpoint.
"""

import pytest
from pathlib import Path
import json
from validator import SwaggerSchemaValidator

# Load the OpenAPI spec
api_spec_path = 'api.json'
swagger_validator = SwaggerSchemaValidator(api_spec_path)

# Load test data from JSON file
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / 'pet_petId.json'
with open(_endpoint_data_path, 'r') as f:
    _ENDPOINT_DATA = json.load(f)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"petId={case['petId']}, statusCode={case['statusCode']}" for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_pet_by_id(api_client, scenario_case, config_test_data):
    """
    Test the GET /pet/{petId} endpoint.
    """

    petId = scenario_case.get('petId', config_test_data['petId'])
    expected_status_code = scenario_case['statusCode']

    # Construct the endpoint
    endpoint = f"/pet/{petId}"

    # Make the GET request
    response = api_client.get(endpoint)

    # Validate the response status code
    assert response.status_code == expected_status_code, f"Unexpected status code: {response.status_code}"

    # Validate the response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, 'GET', str(expected_status_code), response)

    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

def test_get_pet_by_id_invalid_id(api_client):
    """
    Test the GET /pet/{petId} endpoint with an invalid ID.
    """
    invalid_pet_id = 'invalid'
    endpoint = f"/pet/{invalid_pet_id}"

    response = api_client.get(endpoint)

    assert response.status_code == 400, "Expected status code 400 for invalid ID"

    # Validate the response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, 'GET', '400', response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

def test_get_pet_by_id_not_found(api_client):
    """
    Test the GET /pet/{petId} endpoint with a non-existent pet ID.
    """
    non_existent_pet_id = 999999
    endpoint = f"/pet/{non_existent_pet_id}"

    response = api_client.get(endpoint)

    assert response.status_code == 404, "Expected status code 404 for non-existent pet ID"

    # Validate the response schema
    validation_result = swagger_validator.validate_schema_by_response(endpoint, 'GET', '404', response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"

def test_get_pet_by_id_missing_auth(api_client):
    """
    Test the GET /pet/{petId} endpoint without authentication.
    """
    pet_id = 10
    endpoint = f"/pet/{pet_id}"

    # Make the GET request without auth
    response = api_client.get(endpoint, headers={'Authorization': ''})

    assert response.status_code == 401, "Expected status code 401 for missing authentication"

    # Validate the response schema, if defined for 401
    validation_result = swagger_validator.validate_schema_by_response(endpoint, 'GET', 'default', response)
    assert validation_result['valid'], f"Schema validation failed: {validation_result.get('message')}"
