# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-petstore-v3 using AI Type Open AI and AI Model gpt-4o
# 
# Test file generated for /store/order/{orderId}_get for http method type GET 
# RoostTestHash=d35051238a
# 
# 

# ********RoostGPT********
"""
Test suite for the /store/order/{orderId} API endpoint using pytest.
Tests are based on the OpenAPI specification and cover various scenarios.
"""

import pytest
import json
from pathlib import Path
from validator import SwaggerSchemaValidator

# Constants
TEST_DATA_FILENAME = 'store_order_orderId.json'
SPEC_FILE = 'api.json'

# Load API specification and test data
_here = Path(__file__).resolve().parent
_endpoint_data_path = _here / TEST_DATA_FILENAME
_SPEC = SwaggerSchemaValidator(SPEC_FILE)

def _load_json_file(file_path):
    with open(file_path, 'r') as f:
        return json.load(f)

_ENDPOINT_DATA = _load_json_file(_endpoint_data_path)

# Reusable parametrize args
_PARAM_CASES = _ENDPOINT_DATA
_PARAM_IDS = [f"{case['scenario']}_{case['orderId']}" for case in _ENDPOINT_DATA]

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_order_by_id(api_client, config_test_data, scenario_case):
    """
    Test the /store/order/{orderId} endpoint for various scenarios.
    """
    order_id = scenario_case.get('orderId')
    expected_status_code = scenario_case.get('statusCode')

    # Validate request parameters
    request_params = {'orderId': order_id}
    validation_result = _SPEC.validate_json(request_params, 'getOrderByIdRequest')
    assert validation_result['valid'], f"Request validation failed: {validation_result.get('message')}"

    # Perform API request
    endpoint = f"/store/order/{order_id}"
    response = api_client.get(endpoint)

    # Validate response status code
    assert response.status_code == expected_status_code, f"Unexpected status code: {response.status_code}"

    # Validate response schema
    schema_validation = _SPEC.validate_schema_by_response(endpoint, 'get', str(response.status_code), response)
    assert schema_validation['valid'], f"Response validation failed: {schema_validation.get('message')}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_order_by_id_invalid_auth(api_client, scenario_case):
    """
    Test the /store/order/{orderId} endpoint with invalid authentication.
    """
    order_id = scenario_case.get('orderId')

    # Perform API request with invalid auth
    endpoint = f"/store/order/{order_id}"
    headers = {'Authorization': 'Bearer invalid_token'}
    response = api_client.get(endpoint, headers=headers)

    # Assert 401 Unauthorized for invalid auth
    assert response.status_code == 401, f"Unexpected status code for invalid auth: {response.status_code}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_order_by_id_missing_auth(api_client, scenario_case):
    """
    Test the /store/order/{orderId} endpoint with missing authentication.
    """
    order_id = scenario_case.get('orderId')

    # Perform API request without auth
    endpoint = f"/store/order/{order_id}"
    response = api_client.get(endpoint)

    # Assert 401 Unauthorized for missing auth
    assert response.status_code == 401, f"Unexpected status code for missing auth: {response.status_code}"

@pytest.mark.parametrize("scenario_case", _PARAM_CASES, ids=_PARAM_IDS)
def test_get_order_by_id_invalid_id(api_client, scenario_case):
    """
    Test the /store/order/{orderId} endpoint with invalid order ID.
    """
    invalid_order_id = 9999  # Assuming 9999 is an invalid ID for the test

    # Perform API request with invalid order ID
    endpoint = f"/store/order/{invalid_order_id}"
    response = api_client.get(endpoint)

    # Assert 404 Not Found for invalid order ID
    assert response.status_code == 404, f"Unexpected status code for invalid ID: {response.status_code}"
