# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-weather using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /history.json_get for http method type GET 
# RoostTestHash=6ba88fbe10
# 
# 

# ********RoostGPT********
# =================================================================================================
# File: test_history_api.py
# =================================================================================================
# Summary - Identified Endpoints and Security Schemas (from provided API specification)
# - Endpoint:
#   - GET /v1/history.json (operationId: history-weather)
# - Security:
#   - ApiKeyAuth (API Key authentication; key expected via query or header depending on server config)
# - Query Parameters:
#   - Required:
#     - q: string
#     - Exactly one of: dt (string, date) OR unixdt (integer)
#   - Optional:
#     - end_dt (string, date) XOR unixend_dt (integer)
#     - hour (integer 0..23)
#     - lang (string)
# - Response Status Codes:
#   - 200 Ok (Forecast object)
#   - 400 Bad Request (error object: code, message)
#   - 401 Unauthorized (error object: code, message)
#   - 403 Forbidden (error object: code, message)
#
# Notes:
# - Table-driven test data is read from history_json.json in the same directory.
# - Authentication-focused tests are intentionally skipped here as per instruction (handled in a dedicated file).
# - All requests are validated before sending using SwaggerSchemaValidator.validate_with_schema.
# - All responses are validated after receiving using SwaggerSchemaValidator.validate_with_schema.
# - Base URL and credentials are read via conftest fixtures and config.yml with env substitution.
# =================================================================================================

import json
import os
from pathlib import Path
from typing import Any, Dict, List

import pytest
import requests
from jsonschema.exceptions import ValidationError as JSONSchemaValidationError

from validator import SwaggerSchemaValidator


# -----------------------------
# Utilities
# -----------------------------
def _here() -> Path:
    return Path(__file__).resolve().parent


def _load_json_cases() -> List[Dict[str, Any]]:
    # Load table-driven inputs from history_json.json located in the same directory as this file
    json_path = os.path.join(str(_here()), "history_json.json")
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        if not isinstance(data, list):
            raise ValueError("history_json.json must contain a JSON array")
        return data


# Prepare param IDs from the JSON file for better readability
_JSON_CASES = _load_json_cases()
_PARAM_IDS = [c.get("scenario") or c.get("q") or f"case_{i}" for i, c in enumerate(_JSON_CASES)]


# -----------------------------
# Fixtures (function/class scoped as appropriate)
# -----------------------------
@pytest.fixture(scope="session")
def api_spec_validator() -> SwaggerSchemaValidator:
    """
    Create a SwaggerSchemaValidator bound to api.json co-located with the tests.
    This validator is used for both request validation (ad-hoc schemas) and response validation.
    """
    spec_path = os.path.join(str(_here()), "api.json")
    return SwaggerSchemaValidator(spec_path)


@pytest.fixture(scope="session")
def endpoints() -> Dict[str, str]:
    """
    Endpoint registry for the API under test. Update here to add/modify endpoints.
    """
    return {
        "history": "/v1/history.json",
    }


@pytest.fixture(scope="session")
def request_schema_history() -> Dict[str, Any]:
    """
    JSON Schema for validating the query parameters for GET /v1/history.json requests.

    Rules:
    - q is required.
    - Exactly one of dt (date string) or unixdt (integer) must be present.
    - For range queries, either end_dt OR unixend_dt, or neither; but not both simultaneously.
    - hour is 0..23 when provided.
    """
    cond_dt_only = {
        "allOf": [
            {"required": ["dt"]},
            {"not": {"required": ["unixdt"]}},
        ]
    }
    cond_unixdt_only = {
        "allOf": [
            {"required": ["unixdt"]},
            {"not": {"required": ["dt"]}},
        ]
    }
    cond_end_dt_only = {
        "allOf": [
            {"required": ["end_dt"]},
            {"not": {"required": ["unixend_dt"]}},
        ]
    }
    cond_unixend_dt_only = {
        "allOf": [
            {"required": ["unixend_dt"]},
            {"not": {"required": ["end_dt"]}},
        ]
    }

    schema: Dict[str, Any] = {
        "type": "object",
        "properties": {
            "q": {"type": "string"},
            "dt": {"type": "string"},
            "unixdt": {"type": "integer"},
            "end_dt": {"type": "string"},
            "unixend_dt": {"type": "integer"},
            "hour": {"type": "integer", "minimum": 0, "maximum": 23},
            "lang": {"type": "string"},
            # Common API key param (if provided via query). If API uses header-based key, this will be absent.
            "key": {"type": "string"},
        },
        "required": ["q"],
        "allOf": [
            {"oneOf": [cond_dt_only, cond_unixdt_only]},
            # end range is optional; if provided, it must be either end_dt or unixend_dt (but not both).
            {"anyOf": [cond_end_dt_only, cond_unixend_dt_only, {}]},
        ],
        "additionalProperties": True,
    }
    return schema


@pytest.fixture(scope="session")
def response_schemas_history() -> Dict[int, Dict[str, Any]]:
    """
    Response schemas for GET /v1/history.json based on the provided spec.
    """
    schema_200 = {
        "type": "object",
        "properties": {
            "location": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "region": {"type": "string"},
                    "country": {"type": "string"},
                    "lat": {"type": "number"},
                    "lon": {"type": "number"},
                    "tz_id": {"type": "string"},
                    "localtime_epoch": {"type": "integer"},
                    "localtime": {"type": "string"},
                },
                "additionalProperties": True,
            },
            "forecast": {
                "type": "object",
                "properties": {
                    "forecastday": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "date": {"type": "string"},
                                "date_epoch": {"type": "integer"},
                                "day": {
                                    "type": "object",
                                    "properties": {
                                        "maxtemp_c": {"type": "number"},
                                        "maxtemp_f": {"type": "number"},
                                        "mintemp_c": {"type": "number"},
                                        "mintemp_f": {"type": "number"},
                                        "avgtemp_c": {"type": "number"},
                                        "avgtemp_f": {"type": "number"},
                                        "maxwind_mph": {"type": "number"},
                                        "maxwind_kph": {"type": "number"},
                                        "totalprecip_mm": {"type": "number"},
                                        "totalprecip_in": {"type": "number"},
                                        "avgvis_km": {"type": "number"},
                                        "avgvis_miles": {"type": "number"},
                                        "avghumidity": {"type": "number"},
                                        "daily_will_it_rain": {"type": "integer"},
                                        "daily_chance_of_rain": {"type": "number"},
                                        "daily_will_it_snow": {"type": "integer"},
                                        "daily_chance_of_snow": {"type": "number"},
                                        "condition": {
                                            "type": "object",
                                            "properties": {
                                                "text": {"type": "string"},
                                                "icon": {"type": "string"},
                                                "code": {"type": "integer"},
                                            },
                                            "additionalProperties": True,
                                        },
                                        "uv": {"type": "integer"},
                                    },
                                    "additionalProperties": True,
                                },
                                "astro": {
                                    "type": "object",
                                    "properties": {
                                        "sunrise": {"type": "string"},
                                        "sunset": {"type": "string"},
                                        "moonrise": {"type": "string"},
                                        "moonset": {"type": "string"},
                                        "moon_phase": {"type": "string"},
                                        "moon_illumination": {"type": "string"},
                                    },
                                    "additionalProperties": True,
                                },
                                "hour": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "time_epoch": {"type": "integer"},
                                            "time": {"type": "string"},
                                            "temp_c": {"type": "number"},
                                            "temp_f": {"type": "number"},
                                            "is_day": {"type": "integer"},
                                            "condition": {
                                                "type": "object",
                                                "properties": {
                                                    "text": {"type": "string"},
                                                    "icon": {"type": "string"},
                                                    "code": {"type": "integer"},
                                                },
                                                "additionalProperties": True,
                                            },
                                            "wind_mph": {"type": "number"},
                                            "wind_kph": {"type": "number"},
                                            "wind_degree": {"type": "number"},
                                            "wind_dir": {"type": "string"},
                                            "pressure_mb": {"type": "number"},
                                            "pressure_in": {"type": "number"},
                                            "precip_mm": {"type": "number"},
                                            "precip_in": {"type": "number"},
                                            "humidity": {"type": "number"},
                                            "cloud": {"type": "number"},
                                            "feelslike_c": {"type": "number"},
                                            "feelslike_f": {"type": "number"},
                                            "windchill_c": {"type": "number"},
                                            "windchill_f": {"type": "number"},
                                            "heatindex_c": {"type": "number"},
                                            "heatindex_f": {"type": "number"},
                                            "dewpoint_c": {"type": "number"},
                                            "dewpoint_f": {"type": "number"},
                                            "will_it_rain": {"type": "integer"},
                                            "chance_of_rain": {"type": "number"},
                                            "will_it_snow": {"type": "integer"},
                                            "chance_of_snow": {"type": "number"},
                                            "vis_km": {"type": "number"},
                                            "vis_miles": {"type": "number"},
                                            "gust_mph": {"type": "number"},
                                            "gust_kph": {"type": "number"},
                                            "uv": {"type": "integer"},
                                        },
                                        "additionalProperties": True,
                                    },
                                },
                            },
                            "additionalProperties": True,
                        },
                    }
                },
                "additionalProperties": True,
            },
        },
        "additionalProperties": True,
    }

    schema_error = {
        "type": "object",
        "properties": {
            "code": {"type": "integer"},
            "message": {"type": "string"},
        },
        "required": ["code", "message"],
        "additionalProperties": True,
    }

    # For non-specified statuses (like 404/405), we will fallback to a permissive schema at runtime: {}

    return {
        200: schema_200,
        400: schema_error,
        401: schema_error,
        403: schema_error,
    }


@pytest.fixture(scope="class")
def test_retries(config: Dict[str, Any]) -> int:
    """
    Optional retry count loaded from config.yml -> test.retries, default 0.
    """
    tests_cfg = config.get("test", {}) if isinstance(config, dict) else {}
    retries = tests_cfg.get("retries", 0)
    try:
        retries = int(retries)
    except Exception:
        retries = 0
    return max(0, retries)


# -----------------------------
# Helper functions for building requests
# -----------------------------
def build_params_from_case(
    case: Dict[str, Any],
    use_unixdt: bool,
    include_end: bool,
    api_key: str | None,
) -> Dict[str, Any]:
    """
    Construct query params from table-driven case.
    - use_unixdt toggles whether we pick dt or unixdt.
    - include_end toggles whether we include end_dt or unixend_dt if present.
    - api_key if provided is included as 'key' param (commonly used by many weather APIs).
    """
    params: Dict[str, Any] = {}
    if "q" in case:
        params["q"] = case["q"]

    # Choose one of dt/unixdt
    if use_unixdt:
        if "unixdt" in case:
            params["unixdt"] = case["unixdt"]
        # If unixdt not in case but dt is, fall back to dt to keep request reasonable
        elif "dt" in case:
            params["dt"] = case["dt"]
    else:
        if "dt" in case:
            params["dt"] = case["dt"]
        elif "unixdt" in case:
            params["unixdt"] = case["unixdt"]

    # Optional end range
    if include_end:
        if not use_unixdt and "end_dt" in case:
            params["end_dt"] = case["end_dt"]
        elif use_unixdt and "unixend_dt" in case:
            params["unixend_dt"] = case["unixend_dt"]

    # Optional hour/lang
    if "hour" in case:
        params["hour"] = case["hour"]
    if "lang" in case:
        params["lang"] = case["lang"]

    # API key (if available and if API expects it in query)
    if api_key:
        params["key"] = api_key

    return params


def _request_with_retries(api_helper, endpoint: str, method: str, params: Dict[str, Any], retries: int) -> requests.Response:
    last_exc = None
    attempt = 0
    while True:
        try:
            return api_helper.make_request(endpoint=endpoint, method=method, params=params)
        except requests.RequestException as exc:
            last_exc = exc
            attempt += 1
            if attempt > retries:
                raise
    # Should never reach here
    raise last_exc  # noqa: B018


# -----------------------------
# Test Suite
# -----------------------------
@pytest.mark.usefixtures("api_client")
class TestHistoryAPI:
    """
    Comprehensive tests for the /v1/history.json endpoint using table-driven data from history_json.json.

    Authentication tests are intentionally skipped in this module as per instruction.
    """

    @pytest.mark.parametrize("case", _JSON_CASES, ids=_PARAM_IDS)
    def test_get_history_success_with_dt(
        self,
        case: Dict[str, Any],
        api_client,
        api_helper,
        endpoints: Dict[str, str],
        api_spec_validator: SwaggerSchemaValidator,
        request_schema_history: Dict[str, Any],
        response_schemas_history: Dict[int, Dict[str, Any]],
        valid_api_key: str | None,
        test_retries: int,
    ):
        """
        GET /v1/history.json - success (using dt) - iterates through all cases from history_json.json
        """
        if not valid_api_key:
            pytest.skip("valid_api_key not configured; skipping success path tests as per requirements")

        params = build_params_from_case(case, use_unixdt=False, include_end=True, api_key=valid_api_key)

        # Validate request before sending
        api_spec_validator.validate_with_schema(params, request_schema_history)

        # Send request
        resp = _request_with_retries(api_helper, endpoints["history"], "GET", params, test_retries)

        # Validate response
        assert resp.status_code == case.get("statusCode", 200)
        body = resp.json()
        api_spec_validator.validate_with_schema(body, response_schemas_history.get(200, {}))

    @pytest.mark.parametrize("case", _JSON_CASES, ids=_PARAM_IDS)
    def test_get_history_success_with_unixdt(
        self,
        case: Dict[str, Any],
        api_client,
        api_helper,
        endpoints: Dict[str, str],
        api_spec_validator: SwaggerSchemaValidator,
        request_schema_history: Dict[str, Any],
        response_schemas_history: Dict[int, Dict[str, Any]],
        valid_api_key: str | None,
        test_retries: int,
    ):
        """
        GET /v1/history.json - success (using unixdt) - iterates through all cases from history_json.json
        """
        if not valid_api_key:
            pytest.skip("valid_api_key not configured; skipping success path tests as per requirements")

        params = build_params_from_case(case, use_unixdt=True, include_end=True, api_key=valid_api_key)

        # Validate request before sending
        api_spec_validator.validate_with_schema(params, request_schema_history)

        # Send request
        resp = _request_with_retries(api_helper, endpoints["history"], "GET", params, test_retries)

        # Validate response
        assert resp.status_code == case.get("statusCode", 200)
        body = resp.json()
        api_spec_validator.validate_with_schema(body, response_schemas_history.get(200, {}))

    @pytest.mark.parametrize("case", _JSON_CASES, ids=_PARAM_IDS)
    def test_get_history_400_both_dt_and_unixdt_present(
        self,
        case: Dict[str, Any],
        api_client,
        api_helper,
        endpoints: Dict[str, str],
        api_spec_validator: SwaggerSchemaValidator,
        request_schema_history: Dict[str, Any],
        response_schemas_history: Dict[int, Dict[str, Any]],
        valid_api_key: str | None,
        test_retries: int,
    ):
        """
        GET /v1/history.json - 400 when both dt and unixdt are provided - iterates through all cases.
        Requires a valid API key; otherwise server may return 401 before parameter validation.
        """
        if not valid_api_key:
            pytest.skip("valid_api_key not configured; skipping parameter error tests that require authenticated calls")

        # Force both dt and unixdt from the case where available
        params = {}
        if "q" in case:
            params["q"] = case["q"]
        if "dt" in case:
            params["dt"] = case["dt"]
        if "unixdt" in case:
            params["unixdt"] = case["unixdt"]
        if "lang" in case:
            params["lang"] = case["lang"]
        if "hour" in case:
            params["hour"] = case["hour"]
        if "end_dt" in case:
            params["end_dt"] = case["end_dt"]
        if "unixend_dt" in case:
            params["unixend_dt"] = case["unixend_dt"]
        params["key"] = valid_api_key

        # Validate request before sending; this should fail the oneOf constraint
        with pytest.raises(JSONSchemaValidationError):
            api_spec_validator.validate_with_schema(params, request_schema_history)

        # Still send to assert server-side 400 behavior
        resp = _request_with_retries(api_helper, endpoints["history"], "GET", params, test_retries)

        assert resp.status_code == 400
        body = resp.json()
        api_spec_validator.validate_with_schema(body, response_schemas_history.get(400, {}))

    @pytest.mark.parametrize("case", _JSON_CASES, ids=_PARAM_IDS)
    def test_get_history_400_missing_q(
        self,
        case: Dict[str, Any],
        api_client,
        api_helper,
        endpoints: Dict[str, str],
        api_spec_validator: SwaggerSchemaValidator,
        request_schema_history: Dict[str, Any],
        response_schemas_history: Dict[int, Dict[str, Any]],
        valid_api_key: str | None,
        test_retries: int,
    ):
        """
        GET /v1/history.json - 400 when 'q' is missing - iterates through all cases.
        Requires a valid API key; otherwise server may return 401 instead of 400.
        """
        if not valid_api_key:
            pytest.skip("valid_api_key not configured; skipping parameter error tests that require authenticated calls")

        # Build params but intentionally omit 'q'
        params = build_params_from_case(case, use_unixdt=False, include_end=False, api_key=valid_api_key)
        params.pop("q", None)

        # Validate request before sending; should fail due to missing required 'q'
        with pytest.raises(JSONSchemaValidationError):
            api_spec_validator.validate_with_schema(params, request_schema_history)

        resp = _request_with_retries(api_helper, endpoints["history"], "GET", params, test_retries)

        assert resp.status_code == 400
        body = resp.json()
        api_spec_validator.validate_with_schema(body, response_schemas_history.get(400, {}))

    @pytest.mark.parametrize("case", _JSON_CASES, ids=_PARAM_IDS)
    @pytest.mark.parametrize("method", ["POST", "PUT", "DELETE", "PATCH"], ids=lambda m: f"method_{m}")
    def test_history_unsupported_methods(
        self,
        case: Dict[str, Any],
        method: str,
        api_helper,
        endpoints: Dict[str, str],
        api_spec_validator: SwaggerSchemaValidator,
        request_schema_history: Dict[str, Any],
        valid_api_key: str | None,
        test_retries: int,
    ):
        """
        Non-GET methods on /v1/history.json should not be allowed.
        Acceptable statuses include 400/401/403/404/405 depending on server behavior.
        """
        params = build_params_from_case(case, use_unixdt=False, include_end=False, api_key=valid_api_key)

        # Validate request before sending
        # (Method is not part of the schema; we validate the query params only)
        api_spec_validator.validate_with_schema(params, request_schema_history)

        resp = _request_with_retries(api_helper, endpoints["history"], method, params, test_retries)

        assert resp.status_code in {400, 401, 403, 404, 405}
        # Validate with a permissive schema when server returns HTML or unknown shape
        try:
            body = resp.json()
            api_spec_validator.validate_with_schema(body, {})  # Accept any JSON structure
        except ValueError:
            # Non-JSON response; acceptable for method-not-allowed or 404 responses.
            pass


# =================================================================================================
# How to run
# -------------------------------------------------------------------------------------------------
# 1) Ensure the following files exist in the same directory as this test file:
#    - conftest.py (provided)
#    - validator.py (provided)
#    - api.json (OpenAPI/Swagger spec with components/definitions)
#    - config.yml (provided; uses env substitution for api.host)
#    - history_json.json (provided; table-driven test cases)
#
# 2) Set environment variables as needed:
#    - API_HOST: Base URL host, e.g. "api.weatherapi.com"
#    - Optionally set API key through config.yml under api.key or via other supported keys
#      (api.api_key, api.key, api.apikey, api.token) or via environment by templating config.yml.
#      Example config.yml:
#        api:
#          host: ${API_HOST}
#          key: ${API_KEY}
#
# 3) Install dependencies:
#    - pip install -r requirements.txt
#      (Ensure pytest, requests, pyyaml, jsonschema are installed)
#
# 4) Run tests:
#    - pytest -q
#
# Notes:
# - Authentication tests (valid/invalid/missing/expired token) are intentionally handled in a separate
#   test_authentication.py as per the instructions.
# =================================================================================================
