# ********RoostGPT********

# Test generated by RoostGPT for test pyapi-weather using AI Type Open AI and AI Model gpt-5
# 
# Test file generated for /ip.json_get for http method type GET 
# RoostTestHash=5693e62dd1
# 
# 

# ********RoostGPT********
# test_ip_lookup_api.py
# =======================================================================================
# Summary of API specification (derived from the provided OpenAPI snippet)
# - Endpoint:
#   - GET /v1/ip.json
# - Security Schemas:
#   - ApiKeyAuth (API Key-based authentication). Auth-specific tests are skipped here.
# - Request:
#   - Query parameter: q (string, required) — IP address or location query.
# - Responses:
#   - 200 Ok: JSON object containing IP and location metadata.
#   - 400 Bad Request: JSON error object (fields: code, message) for invalid/missing 'q' or other issues.
#   - 401 Unauthorized: JSON error object (fields: code, message) for missing/invalid API key.
#   - 403 Forbidden: JSON error object (fields: code, message) for quota/plan/resource access issues.
#
# Note:
# - Table-driven tests read from ip.json.json in the same folder.
# - Authentication behavior is not tested in this file (handled in test_authentication.py).
# - Request/response validation uses ONLY SwaggerSchemaValidator from validator.py.
# - All requests are validated before sending; all responses are validated after receiving.
# - No hardcoded request payloads/headers/expected data; dynamic values come from ip.json.json and config.
# =======================================================================================

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import pytest

from validator import SwaggerSchemaValidator

# ---------------------------------------------------------------------------------------
# Fixtures and helpers
# ---------------------------------------------------------------------------------------

@pytest.fixture(scope="session")
def api_spec_validator() -> SwaggerSchemaValidator:
    """
    Initialize the validator using the OpenAPI spec path 'api.json' located
    in the same directory as this test file (per instruction: same directory as validator).
    """
    base_dir = Path(__file__).resolve().parent
    # validator.py and api.json are placed in the same directory per instructions.
    spec_path = os.path.join(str(base_dir), "api.json")
    return SwaggerSchemaValidator(spec_path)


@pytest.fixture(scope="session")
def endpoint(config: Dict[str, Any]) -> str:
    """
    Resolve endpoint path with overrides:
    - Prefer config.test.endpoints.ip
    - Else env var IP_ENDPOINT
    - Else default to '/v1/ip.json'
    """
    # Default path from API spec
    default_endpoint = "/v1/ip.json"

    test_cfg = (config.get("test") or {})
    endpoints_cfg = (test_cfg.get("endpoints") or {})
    cfg_endpoint = endpoints_cfg.get("ip")

    env_endpoint = os.environ.get("IP_ENDPOINT")
    return (cfg_endpoint or env_endpoint or default_endpoint).strip()


@pytest.fixture(scope="session")
def retries(config: Dict[str, Any]) -> int:
    """
    Configure retry attempts for transient errors.
    - Prefer config.test.retries
    - Else env var TEST_RETRIES
    - Else 0
    """
    test_cfg = (config.get("test") or {})
    cfg_retries = test_cfg.get("retries")
    env_retries = os.environ.get("TEST_RETRIES")
    try:
        return int(cfg_retries if cfg_retries is not None else (env_retries if env_retries is not None else 0))
    except ValueError:
        return 0


@pytest.fixture(scope="session")
def timeout_seconds(config: Dict[str, Any]) -> int:
    """
    Configure request timeout.
    - Prefer config.test.timeout
    - Else env var TEST_TIMEOUT
    - Else fallback to APIHelper default handled in conftest
    """
    test_cfg = (config.get("test") or {})
    cfg_timeout = test_cfg.get("timeout")
    env_timeout = os.environ.get("TEST_TIMEOUT")
    try:
        return int(cfg_timeout if cfg_timeout is not None else (env_timeout if env_timeout is not None else 30))
    except ValueError:
        return 30


@pytest.fixture(scope="session")
def ip_test_vectors() -> List[Dict[str, Any]]:
    """
    Load table-driven test data from 'ip.json.json' located in the same directory as this test file.
    The file contains objects with fields such as:
      - q: query string (required)
      - statusCode: expected HTTP status code
      - scenario: human-readable label
    """
    base_dir = Path(__file__).resolve().parent
    data_path = os.path.join(str(base_dir), "ip.json.json")
    if not Path(data_path).exists():
        pytest.fail(f"Test data file not found: {data_path}", pytrace=False)
    try:
        with open(data_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            if not isinstance(data, list):
                pytest.fail("ip.json.json must contain a JSON array.", pytrace=False)
            return data
    except json.JSONDecodeError as e:
        pytest.fail(f"Invalid JSON in ip.json.json: {e}", pytrace=False)


@pytest.fixture(scope="session")
def request_query_schema() -> Dict[str, Any]:
    """
    JSON Schema for request query parameters. Built from the provided spec:
    - q: string, required
    - key: optional (API key, if provided via query param)
    Additional properties are allowed to support extensibility.
    """
    return {
        "type": "object",
        "properties": {
            "q": {"type": "string"},
            "key": {"type": ["string", "null"]},
        },
        "required": ["q"],
        "additionalProperties": True,
    }


@pytest.fixture(scope="session")
def response_schemas() -> Dict[int, Dict[str, Any]]:
    """
    JSON Schemas for responses per status code. Derived from the provided API spec.
    Uses flexible property type validation to reduce brittleness while staying consistent with field names.
    """
    schema_200 = {
        "type": "object",
        "properties": {
            "ip": {},
            "type": {},
            "continent_code": {},
            "continent_name": {},
            "country_code": {},
            "country_name": {},
            "is_eu": {},
            "geoname_id": {},
            "city": {},
            "region": {},
            "lat": {},
            "lon": {},
            "tz_id": {},
            "localtime_epoch": {},
            "localtime": {},
        },
        "additionalProperties": True,
    }

    error_schema = {
        "type": "object",
        "properties": {
            "code": {},
            "message": {},
        },
        "required": ["code", "message"],
        "additionalProperties": True,
    }

    return {
        200: schema_200,
        400: error_schema,
        401: error_schema,
        403: error_schema,
    }


def _compose_params(base_params: Dict[str, Any], valid_api_key: Optional[str]) -> Dict[str, Any]:
    """
    Compose query parameters by optionally adding API key as 'key' query parameter.
    Authentication behavior is not tested here; presence of key depends on config/env.
    """
    params = dict(base_params)
    if valid_api_key:
        # Conventional query parameter for API key is 'key' (based on config/env naming).
        params["key"] = valid_api_key
    return params


def _send_with_retries(
    api_client,
    method: str,
    endpoint: str,
    params: Dict[str, Any],
    headers: Optional[Dict[str, str]],
    retries: int,
):
    """
    Wrapper to send request with simple retry on transient 5xx/429 errors.
    """
    attempt = 0
    last_response = None
    while attempt <= retries:
        if method.upper() == "GET":
            last_response = api_client.get(endpoint=endpoint, headers=headers, params=params)
        else:
            # Only GET is defined in the spec for this endpoint; other methods are not covered here.
            last_response = api_client.get(endpoint=endpoint, headers=headers, params=params)

        if last_response.status_code < 500 and last_response.status_code != 429:
            break
        attempt += 1
    return last_response


# ---------------------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------------------

@pytest.mark.parametrize("vector", argvalues=lambda ip_test_vectors: ip_test_vectors, indirect=["vector"])
def test_ip_lookup_get_table_driven(
    api_client,
    endpoint: str,
    ip_test_vectors: List[Dict[str, Any]],
    request_query_schema: Dict[str, Any],
    response_schemas: Dict[int, Dict[str, Any]],
    api_spec_validator: SwaggerSchemaValidator,
    valid_api_key: Optional[str],
    retries: int,
    timeout_seconds: int,
):
    """
    Table-driven test for GET /v1/ip.json, iterating all scenarios from ip.json.json.
    - Validates request parameters against schema before sending.
    - Sends request using API client/fixtures from conftest.py.
    - Validates response status code against expected from test vector.
    - Validates response JSON against the appropriate status schema.
    """
    # Iterate over all provided test vectors
    for vector in ip_test_vectors:
        scenario = vector.get("scenario", "Unnamed scenario")
        q_value = vector.get("q")
        expected_status = int(vector.get("statusCode"))

        base_params = {"q": q_value}
        params = _compose_params(base_params, valid_api_key)

        # Validate request schema before sending
        try:
            api_spec_validator.validate_with_schema(params, request_query_schema)
        except Exception as e:
            pytest.fail(f"[{scenario}] Request validation failed for params={params}: {e}", pytrace=False)

        # Prepare headers (none required by spec beyond Accept; APIHelper sets defaults)
        headers = {}

        # Send with retries for transient failures
        response = _send_with_retries(
            api_client=api_client,
            method="GET",
            endpoint=endpoint,
            params=params,
            headers=headers,
            retries=retries,
        )

        # Assert HTTP status
        assert response.status_code == expected_status, f"[{scenario}] Expected {expected_status}, got {response.status_code}"

        # Parse JSON body; tolerate empty body
        try:
            body = response.json() if response.content else {}
        except ValueError:
            pytest.fail(f"[{scenario}] Response is not valid JSON: {response.text}", pytrace=False)

        # Validate response against schema for the received status code
        status_schema = response_schemas.get(response.status_code)
        if status_schema is None:
            # If an unexpected status code is returned, fail with details
            pytest.fail(f"[{scenario}] No schema registered for status code {response.status_code}", pytrace=False)

        try:
            api_spec_validator.validate_with_schema(body, status_schema)
        except Exception as e:
            pytest.fail(
                f"[{scenario}] Response validation failed for status {response.status_code}: {e}\nBody: {json.dumps(body, indent=2)}",
                pytrace=False,
            )


@pytest.mark.parametrize("vector", argvalues=lambda ip_test_vectors: ip_test_vectors, indirect=["vector"])
def test_ip_lookup_request_schema_validation_only(
    ip_test_vectors: List[Dict[str, Any]],
    request_query_schema: Dict[str, Any],
    api_spec_validator: SwaggerSchemaValidator,
    valid_api_key: Optional[str],
):
    """
    Validates that all table-driven request vectors conform to the request schema.
    This does not perform network calls; it validates requests preemptively.
    """
    for vector in ip_test_vectors:
        scenario = vector.get("scenario", "Unnamed scenario")
        q_value = vector.get("q")
        base_params = {"q": q_value}
        params = _compose_params(base_params, valid_api_key)
        try:
            api_spec_validator.validate_with_schema(params, request_query_schema)
        except Exception as e:
            pytest.fail(f"[{scenario}] Request validation failed for params={params}: {e}", pytrace=False)


# ---------------------------------------------------------------------------------------
# Instructions (as comments)
# ---------------------------------------------------------------------------------------
# Setup:
# 1) Ensure the following files are present in the same directory as this test:
#    - conftest.py (provided)
#    - validator.py (provided)
#    - api.json (OpenAPI spec used by SwaggerSchemaValidator)
#    - config.yml (provided; uses ${API_HOST} and ${key})
#    - ip.json.json (test vectors; sample provided)
#
# 2) Set environment variables as needed:
#    - API_HOST: Base URL of the API (e.g., https://api.example.com)
#    - key: Your API key (if required by the service)
#    Optional:
#    - IP_ENDPOINT: Override endpoint path (default: /v1/ip.json)
#    - TEST_RETRIES: Number of retries for transient errors (default: 0)
#    - TEST_TIMEOUT: Timeout in seconds (default: 30)
#
# 3) Optionally configure config.yml or add 'test' section for retries, timeouts, etc.
#
# Running the tests:
# - Install dependencies: pytest, requests, pyyaml, jsonschema
# - Execute:
#     pytest -q
# ---------------------------------------------------------------------------------------
