# ********RoostGPT********

# Test generated by RoostGPT for test kuvera_karate_get_api using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /api/v3/funds/tags/top_watchlist.json_get for http method type GET 
# RoostTestHash=bee3a3b3c5
# 
# 

# ********RoostGPT********
Feature: Top Watched Funds API Feature

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario: Verify API supports GET method
    Given path '/api/v3/funds/tags/top_watchlist.json'
    When method GET
    Then status 200
    And match response == '#[]'
    And match response[*] == '#string'

  Scenario Outline: Validate response structure and schema for given top watched funds
    Given path '/api/v3/funds/tags/top_watchlist.json'
    When method GET
    Then status 200
    And match response == '#[]'
    And match response[*] contains '<fund_code>'
    And match response[*] == '#string'
    And match response[*].matches('^[A-Z0-9-]+')

    Examples:
      | read('api_v3_funds_tags_top_watchlist.json_get.csv') |

  Scenario: Validate incorrect HTTP method response
    Given path '/api/v3/funds/tags/top_watchlist.json'
    When method POST
    Then status 405
    And match response == null
    And match responseHeaders['Allow'] == '#string ^GET$'

  Scenario: Validate mutual fund codes formatting for top watched funds
    Given path '/api/v3/funds/tags/top_watchlist.json'
    When method GET
    Then status 200
    And match response != null
    And match response[*] == '#string'
    And match response[*].matches('^[A-Z0-9-]+')
    And assert response[*].length > 0
