# ********RoostGPT********

# Test generated by RoostGPT for test kuvera_karate_get_api using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /fixed_deposit/api/v1/plans.json_get for http method type GET 
# RoostTestHash=61d05eb750
# 
# 

# ********RoostGPT********
Feature: Fixed Deposit Plans API Tests

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario: Verify GET /fixed_deposit/api/v1/plans.json returns valid response
    Given path 'fixed_deposit/api/v1/plans.json'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.data == '#array'
    And match response.data[*].id == '#string'
    And match response.data[*].type == '#string'
    And match response.data[*].attributes == '#object'
    And match response.data[*].attributes.name == '#string'
    And match response.data[*].attributes.risk_level == '#string'
    And match response.data[*].attributes.partner_id == '#string'
    And match response.data[*].attributes.interest_rate == '#number'
    And match response.data[*].attributes.senior_citizen_interest_rate == '#number'
    And match response.data[*].attributes.tenure_from == '#number'
    And match response.data[*].attributes.tenure_to == '#number'
    And match response.data[*].attributes.tenure_from_in_months == '#number'
    And match response.data[*].attributes.tenure_to_in_months == '#number'
    And match response.data[*].attributes.min_amount == '#string'
    And match response.data[*].attributes.min_amount contains '#regex \\d+\\.\\d{2}?'
    And match response.data[*].attributes.compounding == '#string'
    And match response.data[*].attributes.compounding contains ['annually', 'monthly', 'daily']
    And match response.data[*].attributes.max_amount == '#string'
    And match response.data[*].attributes.max_amount contains '#regex \\d+\\.\\d{2}?'
    And match response.data[*].attributes.status == '#string'
    And match response.data[*].attributes.status contains ['registered', 'active']
    And match response.data[*].attributes.lockin_period == '#string'
    And match response.data[*].attributes.lockin_period contains '#regex \\d+'
